 server {
    listen 80;
    server_name localhost;

    root /data/;

    location = /config.js {
       limit_except GET { deny all; }
    }

    location ~* ^/(code|auth|admin|algorithm|file|push|app|platform|schedule|data|gen) {
       proxy_pass http://smart-gateway:9990;
       #proxy_set_header Host $http_host;
       proxy_connect_timeout 30s;
       proxy_send_timeout 30s;
       proxy_read_timeout 30s;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
