security:
  oauth2:
    client:
      client-id: "${SMART_BRIDGE_ISC_OAUTH_CLIENT_ID:${SMART_OAUTH_CLIENT_ID:}}"
      client-secret: "${SMART_BRIDGE_ISC_OAUTH_CLIENT_SECRET:${SMART_OAUTH_CLIENT_SECRET:}}"
      scope: server
      ignore-urls:
      - "/**"
smart:
  image:
    expire: 90
  hik:
    host: "${SMART_HIK_HOST:}"
    app-key: "${SMART_HIK_APP_KEY:}"
    app-secret: "${SMART_HIK_APP_SECRET:}"
    event-subscribe-enabled: "${SMART_HIK_EVENT_SUBSCRIBE_ENABLED:false}"
    callback-url: "${SMART_HIK_CALLBACK_URL:http://host.docker.internal:6060/bridge/handle}"
hbase:
  zookeeper:
    znode: "${SMART_HBASE_ZOOKEEPER_ZNODE:/hbase}"
    port: "${SMART_HBASE_ZOOKEEPER_PORT:2181}"
    quorum: "${SMART_HBASE_ZOOKEEPER_QUORUM:smart-hbase}"
