security:
  oauth2:
    client:
      client-id: "${SMART_ALGORITHM_OAUTH_CLIENT_ID:${SMART_OAUTH_CLIENT_ID:}}"        # smart
      client-secret: "${SMART_ALGORITHM_OAUTH_CLIENT_SECRET:${SMART_OAUTH_CLIENT_SECRET:}}"    # smart
      scope: server
        # 放行url
      ignore-urls:
        - /**
#      ignore-urls:
#        - /webjars/**                         #swagger
#        - /swagger-resources                  #swagger
#        - /doc.html                           #swagger
#        - /v2/api-docs                        #swagger
#        - /actuator/**
#        - /inner/**
#        - /test/**

# 数据源
spring:
  datasource:
    type: "${SMART_ALGORITHM_DB_TYPE:com.zaxxer.hikari.HikariDataSource}"
    driver-class-name: "${SMART_ALGORITHM_DB_DRIVER:oracle.jdbc.driver.OracleDriver}"
    username: "${SMART_ALGORITHM_DB_USERNAME:${SMART_DB_USERNAME:}}"
    password: "${SMART_ALGORITHM_DB_PASSWORD:${SMART_DB_PASSWORD:}}"
    url: "${SMART_ALGORITHM_DB_URL:${SMART_DB_URL:}}"

  thymeleaf:
    cache: false  # 开发阶段务必关闭缓存 (=false)
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
record:
  save: false  #是否储存识别记录
# Logger Config
logging:
  level:
    com.tce.smart.algorithm.mapper: debug