security:
  oauth2:
    client:
      client-id: "${SMART_DISPATCHER_OAUTH_CLIENT_ID:${SMART_OAUTH_CLIENT_ID:}}"
      client-secret: "${SMART_DISPATCHER_OAUTH_CLIENT_SECRET:${SMART_OAUTH_CLIENT_SECRET:}}"
      scope: server
      ignore-urls:
      - "/**"
server:
  port: 8082
