CREATE TABLE SMT_CLIENT_RELEASE (
    RELEASE_ID VARCHAR2(128 CHAR) NOT NULL,
    STATUS VARCHAR2(32 CHAR) NOT NULL,
    RELEASE_VERSION NUMBER(19) NOT NULL,
    SNAPSHOT_JSON CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT SMT_CREL_PK PRIMARY KEY (RELEASE_ID),
    CONSTRAINT SMT_CREL_VER_CK CHECK (RELEASE_VERSION > 0)
);

CREATE TABLE SMT_CLIENT_RELEASE_EVENT (
    EVENT_ID VARCHAR2(128 CHAR) NOT NULL,
    RELEASE_ID VARCHAR2(128 CHAR) NOT NULL,
    RELEASE_VERSION NUMBER(19) NOT NULL,
    ACTION VARCHAR2(32 CHAR) NOT NULL,
    ACTOR_ID VARCHAR2(128 CHAR) NOT NULL,
    OCCURRED_AT TIMESTAMP(6) NOT NULL,
    EVENT_JSON CLOB NOT NULL,
    CONSTRAINT SMT_CREL_EVT_PK PRIMARY KEY (EVENT_ID),
    CONSTRAINT SMT_CREL_EVT_REL_FK FOREIGN KEY (RELEASE_ID)
        REFERENCES SMT_CLIENT_RELEASE (RELEASE_ID),
    CONSTRAINT SMT_CREL_EVT_VER_UK UNIQUE (RELEASE_ID, RELEASE_VERSION),
    CONSTRAINT SMT_CREL_EVT_VER_CK CHECK (RELEASE_VERSION > 0)
);

CREATE TABLE SMT_CLIENT_RELEASE_COMMAND (
    SERVICE_SCOPE VARCHAR2(128 CHAR) NOT NULL,
    ACTOR_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(200 CHAR) NOT NULL,
    REQUEST_DIGEST VARCHAR2(64 CHAR) NOT NULL,
    RELEASE_ID VARCHAR2(128 CHAR) NOT NULL,
    RESPONSE_JSON CLOB,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT SMT_CREL_CMD_PK PRIMARY KEY (SERVICE_SCOPE, ACTOR_ID, IDEMPOTENCY_KEY),
    CONSTRAINT SMT_CREL_CMD_DIG_CK CHECK (LENGTH(REQUEST_DIGEST) = 64)
);
