CREATE TABLE SMT_CLIENT_SUP_PRESENCE (
    PERSON_ID VARCHAR2(128 CHAR) NOT NULL,
    AREA_ID VARCHAR2(128 CHAR) NOT NULL,
    PRESENCE_STATE VARCHAR2(16 CHAR) NOT NULL,
    VERSION_NO NUMBER(19, 0) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_SCS_PRES PRIMARY KEY (PERSON_ID, AREA_ID),
    CONSTRAINT CK_SCS_PRES_STATE CHECK (PRESENCE_STATE IN ('OUTSIDE', 'INSIDE')),
    CONSTRAINT CK_SCS_PRES_VER CHECK (VERSION_NO >= 0)
);

CREATE TABLE SMT_CLIENT_SUP_VERIFY (
    VERIFICATION_ID VARCHAR2(128 CHAR) NOT NULL,
    OPERATOR_ID VARCHAR2(128 CHAR) NOT NULL,
    POST_ID VARCHAR2(128 CHAR) NOT NULL,
    AREA_ID VARCHAR2(128 CHAR) NOT NULL,
    BADGE_ID VARCHAR2(128 CHAR) NOT NULL,
    PERSON_ID VARCHAR2(128 CHAR) NOT NULL,
    COMPANY_ID VARCHAR2(128 CHAR) NOT NULL,
    ADMISSION_ID VARCHAR2(128 CHAR) NOT NULL,
    QUALIFICATION_JSON CLOB NOT NULL,
    PRESENCE_STATE VARCHAR2(16 CHAR) NOT NULL,
    PRESENCE_VERSION NUMBER(19, 0) NOT NULL,
    VERIFIED_AT TIMESTAMP(6) NOT NULL,
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    CONSUMED_FLAG NUMBER(1, 0) DEFAULT 0 NOT NULL,
    CONSUMED_EVENT_ID VARCHAR2(128 CHAR),
    CONSUMED_AT TIMESTAMP(6),
    CONSTRAINT PK_SCS_VERIFY PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT FK_SCS_VER_PRES FOREIGN KEY (PERSON_ID, AREA_ID)
        REFERENCES SMT_CLIENT_SUP_PRESENCE (PERSON_ID, AREA_ID),
    CONSTRAINT CK_SCS_VER_STATE CHECK (PRESENCE_STATE IN ('OUTSIDE', 'INSIDE')),
    CONSTRAINT CK_SCS_VER_VERSION CHECK (PRESENCE_VERSION >= 0),
    CONSTRAINT CK_SCS_VER_USED CHECK (CONSUMED_FLAG IN (0, 1))
);

CREATE TABLE SMT_CLIENT_SUP_EVENT (
    EVENT_ID VARCHAR2(128 CHAR) NOT NULL,
    VERIFICATION_ID VARCHAR2(128 CHAR) NOT NULL,
    OPERATOR_ID VARCHAR2(128 CHAR) NOT NULL,
    POST_ID VARCHAR2(128 CHAR) NOT NULL,
    AREA_ID VARCHAR2(128 CHAR) NOT NULL,
    DIRECTION_CODE VARCHAR2(16 CHAR) NOT NULL,
    PERSON_ID VARCHAR2(128 CHAR) NOT NULL,
    BADGE_ID VARCHAR2(128 CHAR) NOT NULL,
    COMPANY_ID VARCHAR2(128 CHAR) NOT NULL,
    ADMISSION_ID VARCHAR2(128 CHAR) NOT NULL,
    QUALIFICATION_JSON CLOB NOT NULL,
    OCCURRED_AT TIMESTAMP(6) NOT NULL,
    VERSION_NO NUMBER(19, 0) NOT NULL,
    CONSTRAINT PK_SCS_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_SCS_EVT_VERIFY FOREIGN KEY (VERIFICATION_ID)
        REFERENCES SMT_CLIENT_SUP_VERIFY (VERIFICATION_ID),
    CONSTRAINT UQ_SCS_EVT_VERIFY UNIQUE (VERIFICATION_ID),
    CONSTRAINT UQ_SCS_EVT_VERSION UNIQUE (PERSON_ID, AREA_ID, VERSION_NO),
    CONSTRAINT CK_SCS_EVT_DIR CHECK (DIRECTION_CODE IN ('ENTER', 'LEAVE')),
    CONSTRAINT CK_SCS_EVT_VERSION CHECK (VERSION_NO > 0)
);

CREATE TABLE SMT_CLIENT_SUP_COMMAND (
    SCOPE_ID VARCHAR2(128 CHAR) NOT NULL,
    OPERATOR_ID VARCHAR2(128 CHAR) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    REQUEST_HASH VARCHAR2(64 CHAR) NOT NULL,
    REPLY_JSON CLOB,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_SCS_COMMAND PRIMARY KEY (SCOPE_ID, OPERATOR_ID, IDEMPOTENCY_KEY)
);
