ALTER TABLE SMT_CLIENT_SUP_PRESENCE DROP CONSTRAINT CK_SCS_PRES_STATE;
ALTER TABLE SMT_CLIENT_SUP_PRESENCE ADD CONSTRAINT CK_SCS_PRES_STATE
    CHECK (PRESENCE_STATE IN ('UNKNOWN', 'OUTSIDE', 'INSIDE'));

ALTER TABLE SMT_CLIENT_SUP_VERIFY DROP CONSTRAINT CK_SCS_VER_STATE;
ALTER TABLE SMT_CLIENT_SUP_VERIFY ADD CONSTRAINT CK_SCS_VER_STATE
    CHECK (PRESENCE_STATE IN ('UNKNOWN', 'OUTSIDE', 'INSIDE'));
