<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>smart-app-biz</artifactId>
	<packaging>jar</packaging>

	<name>smart-app-biz</name>
	<description>APP后台管理服务</description>

	<parent>
		<groupId>com.tce</groupId>
		<artifactId>smart-app</artifactId>
		<version>${revision}</version>
	</parent>

	<dependencies>
	    <!--data api、vo 模块-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-data-api</artifactId>
		</dependency>
		<!--admin api、vo 模块-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-upms-api</artifactId>
		</dependency>
		<!--platform api、vo 模块-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-platform-api</artifactId>
		</dependency>
		<!--bridge api、vo 模块-->
<!--		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-bridge-api</artifactId>
			<scope>provided</scope>
		</dependency>-->
		<!--app api、vo 模块-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-app-api</artifactId>
		</dependency>
		<!--日志处理-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-common-log</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-common-data</artifactId>
		</dependency>
		<!--web 模块-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!--undertow容器-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-common-swagger</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-common-security</artifactId>
		</dependency>
		<!-- 如需显式添加Spring Security依赖 -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<!--mybatis-->
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
		</dependency>
		<!--数据库-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>oracle</artifactId>

		</dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
	         <dependency>
			    <groupId>com.icbc</groupId>
			    <artifactId>icbc-api-sdk-cop-io</artifactId>
			</dependency>
			<dependency>
			    <groupId>com.icbc</groupId>
			    <artifactId>icbc-api-sdk-cop</artifactId>
			</dependency>
		<!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
		<dependency>
		    <groupId>commons-codec</groupId>
		    <artifactId>commons-codec</artifactId>
		</dependency>
		<!--IDEA开发工具,热加载调试用-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>springloaded</artifactId>-->
<!--			<version>1.2.8.RELEASE</version>-->
<!--			<scope>runtime</scope>-->
<!--		</dependency>-->
        <dependency>
            <groupId>com.tce</groupId>
            <artifactId>smart-algorithm-api</artifactId>
        </dependency>
		<!-- alibaba的druid数据库连接池 -->
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid-spring-boot-starter</artifactId>
		</dependency>

    </dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<includeSystemScope>true</includeSystemScope>
					<mainClass>com.tce.smart.app.SmartAppApplication</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
