<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>smart-data</artifactId>
		<groupId>com.tce</groupId>
		<version>${revision}</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>smart-ehrview-core</artifactId>
	<name>${project.artifactId}</name>
	<packaging>jar</packaging>
	<description>EHR视图查询模块</description>

	<dependencies>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-extension</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis</artifactId>
		</dependency>
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-common-core</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
					<groupId>org.springframework.cloud</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-common</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-tool</artifactId>
			<version>${tool.version}</version>
		</dependency>
		<!--数据库-->
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.name}</finalName>
	</build>
</project>
