<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.tce</groupId>
		<artifactId>smart-module</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>smart-tool</artifactId>
	<packaging>jar</packaging>

	<description>智慧园区服务公共模块</description>


	<dependencies>
		<!--core 工具类-->
		<dependency>
			<groupId>com.tce</groupId>
			<artifactId>smart-common-core</artifactId>
		</dependency>

		<dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <version>3.3.3</version>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.3.3</version>
        </dependency>
		<!--导入导出工具类-->
		<dependency>
			<groupId>cn.afterturn</groupId>
			<artifactId>easypoi-base</artifactId>
			<version>4.1.3</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.hibernate/hibernate -->
		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate</artifactId>
		    <version>3.2.6.ga</version>
			<!-- 去除版本不一致的传递依赖包 -->
			<exclusions>
				<exclusion>
					<groupId>javax.transaction</groupId>
					<artifactId>jta</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
	    <groupId>javax.transaction</groupId>
		    <artifactId>jta</artifactId>
		    <version>1.1</version>
		</dependency>
		<dependency>
			<groupId>net.coobird</groupId>
			<artifactId>thumbnailator</artifactId>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.samba.jcifs/jcifs -->
		<dependency>
			<groupId>org.samba.jcifs</groupId>
			<artifactId>jcifs</artifactId>
			<version>1.3.3</version>
		</dependency>
		<dependency>
			<groupId>com.huaweicloud</groupId>
			<artifactId>esdk-obs-java-bundle</artifactId>
			<version>3.24.3</version>
		</dependency>
	</dependencies>
</project>
