package com.tce.smart.platform.service.print;
/** 仅隔离H2测试使用，禁止用作实际数据库迁移。 */
final class PrintJobTestSchema { static void create(org.springframework.jdbc.core.JdbcTemplate jdbc){
  jdbc.execute("CREATE TABLE SMT_PRINT_PRINTER_PROFILE (PRINTER_PROFILE_ID VARCHAR(128) PRIMARY KEY,PARK_ID VARCHAR(128),DEVICE_IDENTITY VARCHAR(128),STATUS VARCHAR(128),ACTIVE_JOB_ID VARCHAR(128),CONFIG_JSON CLOB,CONFIG_REVISION BIGINT)");
  jdbc.execute("CREATE TABLE SMT_PRINT_JOB (JOB_ID VARCHAR(128) PRIMARY KEY,PARK_ID VARCHAR(128),CREATED_BY VARCHAR(128),PRINTER_PROFILE_ID VARCHAR(128),DEVICE_IDENTITY VARCHAR(128),SUBJECT_TYPE VARCHAR(128),SUBJECT_ID VARCHAR(128),ACTIVE_SUBJECT_KEY VARCHAR(512),PRINT_ITEM_TYPE VARCHAR(128),PRINT_MODE VARCHAR(128),STATUS VARCHAR(128),SNAPSHOT_JSON CLOB,TEMPLATE_SNAPSHOT_HASH VARCHAR(128),PRINTER_SNAPSHOT_HASH VARCHAR(128),CURRENT_ATTEMPT_ID VARCHAR(128),CLAIM_ID VARCHAR(128),CLIENT_INSTANCE_ID VARCHAR(128),ARTIFACTS_JSON CLOB,OPERATOR_CHECK_ID VARCHAR(128),ERROR_CODE VARCHAR(128),STATE_JSON CLOB,CREATED_AT TIMESTAMP,UPDATED_AT TIMESTAMP,LEASE_EXPIRES_AT TIMESTAMP,UNIQUE(CLAIM_ID),UNIQUE(ACTIVE_SUBJECT_KEY))");
  jdbc.execute("CREATE TABLE SMT_PRINT_ATTEMPT (ATTEMPT_ID VARCHAR(128) PRIMARY KEY,JOB_ID VARCHAR(128),COMMAND_ID VARCHAR(128),FACE VARCHAR(128),STATE_JSON CLOB,ATTEMPT_NO BIGINT,UNIQUE(COMMAND_ID),UNIQUE(JOB_ID,ATTEMPT_NO))");
  jdbc.execute("CREATE TABLE SMT_PRINT_EVENT (EVENT_ID VARCHAR(128) PRIMARY KEY,JOB_ID VARCHAR(128),ATTEMPT_ID VARCHAR(128),COMMAND_ID VARCHAR(128),EVENT_TYPE VARCHAR(128),BODY_HASH VARCHAR(128),RESPONSE_JSON CLOB,DETAILS_JSON CLOB,CREATED_AT TIMESTAMP)");
  jdbc.execute("CREATE TABLE SMT_PRINT_JOB_ARTIFACT (ARTIFACT_ID VARCHAR(128) PRIMARY KEY,OWNER_ID VARCHAR(128),PARK_ID VARCHAR(128),FACE VARCHAR(128),CONTENT_HASH VARCHAR(128),CONTENT_BYTES BLOB)");
  jdbc.execute("CREATE TABLE SMT_PRINT_JOB_PREVIEW (PREVIEW_ID VARCHAR(128) PRIMARY KEY,PARK_ID VARCHAR(128),CREATED_BY VARCHAR(128),DETAILS_JSON CLOB)");
}}
