package com.tce.smart.platform.service.print;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tce.smart.platform.core.mapper.*;
import org.junit.*;
import org.mybatis.spring.*;
import org.springframework.core.io.*;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.Assert.*;
import static com.tce.smart.platform.service.print.PrintAccessPolicyTest.*;
/** 隔离H2的真实事务用于验证不可逆设备动作的数据库边界。 */
public class PrintJobServiceTest {
 PrintTemplateServiceTest f; PrintJobMapper mapper; PrintJobService jobs; PrintPrinterService printers; PrintClientService clients; PrintJobTransactions tx; PrintExecutionProperties execution; PrintClientIdentity device; PrintJobPreparation preparation; PrintAccessPolicy access; String printer;
 @Before public void setup()throws Exception{
  f=new PrintTemplateServiceTest();f.temporary.create();f.setup();PrintJobTestSchema.create(f.jdbc);
  SqlSessionFactoryBean factory=new SqlSessionFactoryBean();factory.setDataSource(f.source);factory.setMapperLocations(new Resource[]{new ClassPathResource("mapper/PrintTemplateMapper.xml"),new ClassPathResource("mapper/PrintJobMapper.xml")});SqlSessionTemplate sql=new SqlSessionTemplate(factory.getObject());mapper=sql.getMapper(PrintJobMapper.class);
  PrintFeatureProperties feature=properties();for(String c:Arrays.asList("execute","device","recover","preview"))feature.getPermissions().put(c,"test:print:"+c);access=new PrintAccessPolicy(feature,null);manager();
  tx=new PrintJobTransactions(sql.getMapper(PrintTemplateMapper.class),new DataSourceTransactionManager(f.source));execution=new PrintExecutionProperties();execution.setEnabled(true);
  printers=new PrintPrinterService(mapper,access,tx);printer=(String)printers.save(null,profile(),"printer").getData().get("printerProfileId");
  preparation=org.mockito.Mockito.mock(PrintJobPreparation.class);org.mockito.Mockito.when(preparation.freeze(org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyBoolean())).thenAnswer(inv->{ObjectNode request=inv.getArgument(0);if("bad".equals(request.path("subjectId").asText()))throw new PrintApiException(422,"CARD_REQUIRED","缺卡");ObjectNode s=PrintJson.object().put("subjectId",request.path("subjectId").asText()).put("subjectType","STAFF").put("employeeGradeCode","g1");s.set("renderRequest",PrintJson.object().put("jobId",(String)inv.getArgument(1)));s.set("resolution",PrintJson.object());return s;});
  jobs=new PrintJobService(mapper,access,tx,printers,preparation,execution);device=new PrintClientIdentity("test-device",new HashSet<>(Arrays.asList("1")),new HashSet<>(Arrays.asList(printer)));clients=new PrintClientService(mapper,tx,execution);}
 @After public void close(){if(f!=null){f.close();f.temporary.delete();}}
 void manager(){login(1,"test:print:read","test:print:write","test:print:publish","test:print:resource","test:print:execute","test:print:device","test:print:recover","test:print:preview");}
 ObjectNode profile(){ObjectNode p=PrintJson.object().put("parkId","1").put("name","合成打印机").put("deviceIdentity","test-device").put("manufacturer","HiTi").put("model","CS220").put("deviceType","CARD_PRINTER").put("connectionType","USB_LOCAL_CLIENT").put("defaultPrintMode","MANUAL_DUPLEX").put("capabilityStatus","UNVERIFIED").put("flipCapability","MANUAL_ONLY");p.putArray("allowedPrintModes").add("MANUAL_DUPLEX");p.putObject("mediaSpec").put("widthMm",85.6).put("heightMm",53.98);p.putObject("calibration");p.putArray("capabilityEvidence");return p;}
 ObjectNode request(String id){ObjectNode p=PrintJson.object().put("parkId","1").put("subjectType","STAFF").put("subjectId",id).put("printItemType","STAFF_CARD").put("printerProfileId",printer).put("printMode","MANUAL_DUPLEX");p.putObject("selection").put("kind","BOUND");return p;}
 synchronized ObjectNode confirmedRequest(ObjectNode request){ObjectNode profile=PrintPrinterService.snapshot(mapper.findPrinter(request.path("printerProfileId").asText()));ObjectNode frozen=jobs.preparation.freeze(request,UUID.randomUUID().toString(),profile,true);ObjectNode evidence=PrintJobConfirmation.evidence(frozen,profile,request.path("printMode").asText(profile.path("defaultPrintMode").asText()));String previewId=UUID.nameUUIDFromBytes((PrintJson.canonical(request)+PrintJson.canonical(evidence)).getBytes(java.nio.charset.StandardCharsets.UTF_8)).toString();if(mapper.findJobPreview(previewId)==null){com.tce.smart.platform.core.entity.print.PrintJobPreview preview=new com.tce.smart.platform.core.entity.print.PrintJobPreview();preview.setPreviewId(previewId);preview.setParkId("1");preview.setCreatedBy(access.actor());ObjectNode details=PrintJson.object().put("previewId",previewId).put("status","READY");details.set("confirmation",evidence);preview.setDetailsJson(PrintJson.canonical(details));mapper.insertJobPreview(preview);}return request.deepCopy().put("previewId",previewId);}
 String create(String id){return (String)jobs.create(confirmedRequest(request(id)),"job-"+id).getData().get("jobId");}
 void ready(String id){f.jdbc.update("UPDATE SMT_PRINT_JOB SET STATUS='READY',ARTIFACTS_JSON=? WHERE JOB_ID=?","{\"artifacts\":[{\"face\":\"FRONT\",\"sha256\":\"sha256:"+String.join("",Collections.nCopies(64,"a"))+"\",\"pageCount\":1,\"widthMm\":85.6,\"heightMm\":53.98},{\"face\":\"BACK\",\"sha256\":\"sha256:"+String.join("",Collections.nCopies(64,"b"))+"\",\"pageCount\":1,\"widthMm\":85.6,\"heightMm\":53.98}]}",id);}
 ObjectNode claim(String resume){ObjectNode p=PrintJson.object().put("deviceIdentity","test-device").put("printerProfileId",printer).put("clientInstanceId",UUID.randomUUID().toString()).put("clientVersion","0.1.0").put("capabilitySnapshotHash",(String)printers.detail(printer).get("printerSnapshotHash"));p.putArray("supportedPrintModes").add("MANUAL_DUPLEX");if(resume!=null)p.put("resumeJobId",resume);return p;}
 JsonNode claimJob(String id){return PrintJson.tree(clients.claim(device,claim(id),UUID.randomUUID().toString()).getData());}
 ObjectNode event(JsonNode command,String type){ObjectNode e=PrintJson.object().put("eventId",UUID.randomUUID().toString()).put("attemptId",command.at("/action/attemptId").asText()).put("commandId",command.at("/action/commandId").asText()).put("eventType",type).put("clientSequence",1).put("occurredAt",java.time.Instant.now().toString()).put("artifactHash",command.at("/action/artifact/sha256").asText());e.putObject("payload");return e;}
 ObjectNode check(JsonNode command,String decision,String resolution){ObjectNode p=PrintJson.object().put("attemptId",command.at("/action/attemptId").asText()).put("face",command.at("/action/face").asText()).put("decision",decision).put("resolution",resolution).put("reason","合成核对");p.putObject("physicalCheck").put("state","NO_CARD_IN_DEVICE").put("operatorNote","现场人工核对");return p;}
 @Test public void batchFailureCreatesZeroJobsAndNoOperation(){ObjectNode b=confirmedRequest(request("a"));b.putArray("subjects").addObject().put("subjectType","STAFF").put("subjectId","a").put("previewId",b.path("previewId").asText());((com.fasterxml.jackson.databind.node.ArrayNode)b.get("subjects")).addObject().put("subjectType","STAFF").put("subjectId","bad").put("previewId",b.path("previewId").asText());expectCode("BATCH_VALIDATION_FAILED",()->jobs.batch(b,"batch"));assertEquals(0,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void sameKeyConcurrentCreatesOneFrozenJob()throws Exception{ExecutorService pool=Executors.newFixedThreadPool(2);try{Callable<String> c=()->{manager();return create("a");};Future<String>a=pool.submit(c),b=pool.submit(c);assertEquals(a.get(20,TimeUnit.SECONDS),b.get(20,TimeUnit.SECONDS));assertEquals(1,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());assertFalse(PrintJson.canonical(jobs.detail(a.get())).contains("renderRequest"));}finally{pool.shutdownNow();}}
 @Test public void differentKeysForSameSubjectCannotCreateTwoActiveJobs()throws Exception{ExecutorService pool=Executors.newFixedThreadPool(2);try{Callable<String> c=()->{manager();try{jobs.create(confirmedRequest(request("a")),"different-"+UUID.randomUUID());return "CREATED";}catch(PrintApiException e){return e.getCode();}};Future<String>a=pool.submit(c),b=pool.submit(c);List<String> outcome=Arrays.asList(a.get(20,TimeUnit.SECONDS),b.get(20,TimeUnit.SECONDS));assertTrue(outcome.contains("CREATED"));assertTrue(outcome.contains("PRINT_SUBJECT_ACTIVE"));assertEquals(1,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}finally{pool.shutdownNow();}}
 @Test public void cancelledSubjectCanCreateANewJob(){String id=create("a");jobs.cancel(id,PrintJson.object().put("reason","重新制卡"),"cancel-active");String next=(String)jobs.create(confirmedRequest(request("a")),"recreate-after-cancel").getData().get("jobId");assertNotEquals(id,next);assertEquals(2,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void recoveryKeepsAttemptAndOccupancyAfterExecutionDisabled(){String id=create("a");ready(id);JsonNode command=claimJob(id);execution.setEnabled(false);JsonNode resumed=claimJob(id);assertEquals(command.at("/action/commandId"),resumed.at("/action/commandId"));assertEquals(1,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_ATTEMPT",Integer.class).intValue());assertEquals(id,printers.detail(printer).get("activeJobId"));}
 @Test public void acceptedNeverCompletesAndManualFlipCreatesOneBack(){String id=create("a");ready(id);JsonNode c=claimJob(id);clients.event(device,id,event(c,"DEVICE_ACCEPTED"),"accepted");assertEquals("AWAITING_FRONT_CHECK",jobs.detail(id).get("status"));jobs.outputCheck(id,check(c,"CONFIRMED_OUT","NONE"),"front-check");ObjectNode flip=PrintJson.object().put("attemptId",c.at("/action/attemptId").asText()).put("orientationConfirmed",true);jobs.flip(id,flip,"flip");assertTrue(jobs.flip(id,flip,"flip").isReplayed());assertEquals(2,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_ATTEMPT",Integer.class).intValue());assertEquals("BACK",claimJob(id).at("/action/face").asText());}
 @Test public void unknownRequiresRetirementAndExplicitSameCardRecheck(){String id=create("a");ready(id);JsonNode c=claimJob(id);clients.event(device,id,event(c,"OUTPUT_UNKNOWN"),"unknown");ObjectNode check=check(c,"CONFIRMED_NOT_OUT","CONTINUE");expectCode("OUTPUT_CHECK_REQUIRED",()->jobs.outputCheck(id,check,"bad-continue"));ObjectNode retired=event(c,"COMMAND_RETIRED");((ObjectNode)retired.get("payload")).put("queueCleared",true).put("localCommandRetired",true).put("sameCardFaceVerified",true);clients.event(device,id,retired,"retired");expectCode("OUTPUT_CHECK_REQUIRED",()->jobs.outputCheck(id,check,"missing-human"));((ObjectNode)check.get("physicalCheck")).put("sameCardFaceVerified",true);jobs.outputCheck(id,check,"continue");JsonNode next=claimJob(id);assertNotEquals(c.at("/action/commandId"),next.at("/action/commandId"));clients.event(device,id,event(c,"DEVICE_COMPLETED"),"late");assertEquals("RESULT_UNKNOWN",jobs.detail(id).get("status"));assertEquals(next.at("/action/attemptId").asText(),jobs.detail(id).get("currentAttemptId"));}
 @Test public void eventIdentityReplaysOriginalEvenAfterOtherEvents(){String id=create("a");ready(id);JsonNode c=claimJob(id);ObjectNode accepted=event(c,"DEVICE_ACCEPTED");Map<String,Object> original=clients.event(device,id,accepted,"e1").getData();clients.event(device,id,event(c,"OUTPUT_UNKNOWN"),"e2");assertEquals(original,clients.event(device,id,accepted,"e3").getData());accepted.put("clientSequence",2);expectCode("IDEMPOTENCY_KEY_REUSED",()->clients.event(device,id,accepted,"e4"));}
 @Test public void crossParkAndUnconfiguredCapabilityFailClosed(){String id=create("a");login(2,"test:print:execute");expectCode("PRINT_SCOPE_DENIED",()->jobs.detail(id));manager();PrintClientIdentity foreign=new PrintClientIdentity("test-device",Collections.singleton("2"),Collections.singleton(printer));expectCode("PRINT_SCOPE_DENIED",()->clients.claim(foreign,claim(null),"foreign"));ObjectNode p=profile();p.putArray("allowedPrintModes").add("AUTO_DUPLEX");p.put("defaultPrintMode","AUTO_DUPLEX");expectCode("PRINTER_CAPABILITY_UNVERIFIED",()->printers.save(null,p,"auto"));}

 @Test public void printerRejectsUnknownEnumsAndEmptyAutoEvidence(){ObjectNode p=profile().put("deviceType","ARBITRARY");expectCode("INVALID_REQUEST",()->printers.save(null,p,"bad-device"));ObjectNode auto=profile().put("capabilityStatus","VERIFIED").put("flipCapability","AUTO_VERIFIED").put("defaultPrintMode","AUTO_DUPLEX");auto.putArray("allowedPrintModes").add("AUTO_DUPLEX");auto.putArray("capabilityEvidence").addObject();expectCode("PRINTER_CAPABILITY_UNVERIFIED",()->printers.save(null,auto,"empty-proof"));}
 @Test public void profileMutationCannotChangeFrozenModeOrRecoveryIdentity(){String id=create("a");String frozen=f.jdbc.queryForObject("SELECT SNAPSHOT_JSON FROM SMT_PRINT_JOB WHERE JOB_ID=?",String.class,id);ready(id);JsonNode c=claimJob(id);ObjectNode update=PrintJson.object().put("configRevision",0).put("deviceIdentity","replacement");printers.save(printer,update,"change-device");assertEquals(frozen,f.jdbc.queryForObject("SELECT SNAPSHOT_JSON FROM SMT_PRINT_JOB WHERE JOB_ID=?",String.class,id));ObjectNode resume=claim(id).put("capabilitySnapshotHash",c.path("printerSnapshotHash").asText());assertEquals(c.at("/action/commandId").asText(),PrintJson.tree(clients.claim(device,resume,"old-frozen-device").getData()).at("/action/commandId").asText());}
 @Test public void concurrentClaimsCannotStealPhysicalOccupancy()throws Exception{String a=create("a"),b=create("b");ready(a);ready(b);ExecutorService pool=Executors.newFixedThreadPool(2);try{List<Future<String>> futures=new ArrayList<>();for(String id:Arrays.asList(a,b)){ObjectNode body=claim(id);futures.add(pool.submit(()->{try{return (String)clients.claim(device,body,id).getData().get("jobId");}catch(PrintApiException ex){return ex.getCode();}}));}List<String> result=Arrays.asList(futures.get(0).get(20,TimeUnit.SECONDS),futures.get(1).get(20,TimeUnit.SECONDS));assertTrue(result.contains("PRINTER_OCCUPIED"));assertEquals(1,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_ATTEMPT",Integer.class).intValue());}finally{pool.shutdownNow();}}
 @Test public void renderFailurePersistsButNeverBecomesClaimable(){String id=create("a");PrintRendererClient renderer=org.mockito.Mockito.mock(PrintRendererClient.class);org.mockito.Mockito.when(renderer.renderFrozen(org.mockito.ArgumentMatchers.any())).thenThrow(new PrintApiException(503,"PRINT_RENDERER_UNAVAILABLE","合成失败"));new PrintJobRenderer(mapper,tx,renderer,execution).render(id);assertEquals("RENDER_FAILED",jobs.detail(id).get("status"));expectCode("JOB_STATE_CONFLICT",()->claimJob(id));assertEquals(0,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB_ARTIFACT",Integer.class).intValue());assertNull(printers.detail(printer).get("activeJobId"));}
 @Test public void expiredRenderLeaseFailsAtomicallyWithoutCallingRenderer(){String id=create("a");f.jdbc.update("UPDATE SMT_PRINT_JOB SET STATUS='RENDERING',LEASE_EXPIRES_AT=?,UPDATED_AT=? WHERE JOB_ID=?",new java.sql.Timestamp(System.currentTimeMillis()-1000),new java.sql.Timestamp(System.currentTimeMillis()-1000),id);PrintRendererClient renderer=org.mockito.Mockito.mock(PrintRendererClient.class);execution.setRenderWorkerEnabled(true);new PrintJobRenderer(mapper,tx,renderer,execution).poll();assertEquals("RENDER_FAILED",jobs.detail(id).get("status"));assertEquals("RENDER_LEASE_EXPIRED",mapper.findJob(id).getErrorCode());assertNull(mapper.findJob(id).getActiveSubjectKey());assertNull(mapper.findJob(id).getLeaseExpiresAt());org.mockito.Mockito.verify(renderer,org.mockito.Mockito.never()).renderFrozen(org.mockito.ArgumentMatchers.any());}
 @Test public void cancelKeepsOccupancyUntilMatchingHumanAndDeviceClearance(){String id=create("a");ready(id);JsonNode c=claimJob(id);jobs.cancel(id,PrintJson.object().put("reason","合成取消"),"cancel");ObjectNode cleared=PrintJson.object().put("deviceIdentity","test-device").put("physicalState","NO_CARD_IN_DEVICE").put("operatorCheckId",UUID.randomUUID().toString());expectCode("DEVICE_CLEARANCE_REQUIRED",()->clients.deviceCleared(device,id,cleared,"fake-clear"));Map<String,Object> result=jobs.outputCheck(id,check(c,"CONFIRMED_NOT_OUT","CANCEL"),"cancel-check").getData();assertEquals(id,printers.detail(printer).get("activeJobId"));cleared.put("operatorCheckId",(String)result.get("operatorCheckId"));clients.deviceCleared(device,id,cleared,"clear");assertNull(printers.detail(printer).get("activeJobId"));}
 @Test public void deviceFilterRejectsAdministratorAndEmptyCredentials()throws Exception{PrintClientProperties p=new PrintClientProperties();expectCode("PRINT_DEVICE_AUTHENTICATION_REQUIRED",()->PrintClientSecurity.authenticate(p,"Bearer synthetic-device-secret"));PrintClientProperties.Credential c=new PrintClientProperties.Credential();c.setDeviceIdentity("test-device");c.setTokenSha256(PrintJson.hashBytes("synthetic-device-secret".getBytes(java.nio.charset.StandardCharsets.UTF_8)));c.setParkIds(Collections.singleton("1"));c.setPrinterProfileIds(Collections.singleton(printer));p.getCredentials().add(c);assertEquals("test-device",PrintClientSecurity.authenticate(p,"Bearer synthetic-device-secret").deviceIdentity);org.springframework.test.web.servlet.MockMvc mvc=org.springframework.test.web.servlet.setup.MockMvcBuilders.standaloneSetup(new com.tce.smart.platform.controller.print.PrintClientController(clients)).setControllerAdvice(new com.tce.smart.platform.controller.print.PrintApiAdvice()).addFilters(new PrintClientSecurity.DeviceFilter(p)).build();mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/print-client/v1/claims/"+UUID.randomUUID()+"/current")).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isUnauthorized()).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.header().exists("X-Request-Id")).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.header().string("Content-Type","application/json;charset=UTF-8"));}
 @Test public void listFiltersAndQueuedCancelReasonRemainPersisted(){String id=create("a");create("b");com.tce.smart.platform.api.dto.req.print.PrintJobQuery q=new com.tce.smart.platform.api.dto.req.print.PrintJobQuery();q.setParkId("1");q.setSubjectId("a");Map<String,Object> result=jobs.list(q);assertEquals(1L,((Number)result.get("total")).longValue());assertEquals(1,((List<?>)result.get("records")).size());jobs.cancel(id,PrintJson.object().put("reason","合成取消原因"),"queued-cancel");assertEquals("合成取消原因",PrintJson.read(f.jdbc.queryForObject("SELECT STATE_JSON FROM SMT_PRINT_JOB WHERE JOB_ID=?",String.class,id)).path("cancelReason").asText());assertFalse(PrintJson.canonical(jobs.detail(id)).contains("合成取消原因"));}
 @Test public void autoClaimsOnlyCombinedAndUnknownRetirementCannotAuthorizeContinue(){ObjectNode p=profile().put("configRevision",0).put("capabilityStatus","VERIFIED").put("flipCapability","AUTO_VERIFIED").put("defaultPrintMode","AUTO_DUPLEX");p.putArray("allowedPrintModes").add("AUTO_DUPLEX");p.putArray("capabilityEvidence").addObject().put("type","FLIP_MODULE").put("verified",true).put("evidenceId",UUID.randomUUID().toString()).put("driverVersion","synthetic-driver").put("verifiedBy","synthetic-operator").put("verifiedAt",java.time.Instant.now().toString());printers.save(printer,p,"auto-profile");String id=(String)jobs.create(confirmedRequest(request("a").put("printMode","AUTO_DUPLEX")),"auto-job").getData().get("jobId");ready(id);ObjectNode artifacts=(ObjectNode)PrintJson.read(f.jdbc.queryForObject("SELECT ARTIFACTS_JSON FROM SMT_PRINT_JOB WHERE JOB_ID=?",String.class,id));ObjectNode combined=artifacts.putObject("combinedArtifact").put("sha256","sha256:"+String.join("",Collections.nCopies(64,"c"))).put("pageCount",2).put("widthMm",85.6).put("heightMm",53.98);f.jdbc.update("UPDATE SMT_PRINT_JOB SET ARTIFACTS_JSON=? WHERE JOB_ID=?",PrintJson.canonical(artifacts),id);ObjectNode claim=claim(id);claim.putArray("supportedPrintModes").add("AUTO_DUPLEX");JsonNode command=PrintJson.tree(clients.claim(device,claim,"auto-claim").getData());assertEquals("PRINT_BOTH",command.at("/action/type").asText());assertEquals(2,command.at("/action/artifact/pageCount").asInt());clients.event(device,id,event(command,"OUTPUT_UNKNOWN"),"auto-unknown");ObjectNode retirement=event(command,"COMMAND_RETIRED");((ObjectNode)retirement.get("payload")).put("localCommandRetired",true).put("queueCleared",true).put("sameCardFaceVerified",true);clients.event(device,id,retirement,"auto-retired");ObjectNode check=check(command,"CONFIRMED_NOT_OUT","CONTINUE");((ObjectNode)check.get("physicalCheck")).put("sameCardFaceVerified",true);expectCode("OUTPUT_CHECK_REQUIRED",()->jobs.outputCheck(id,check,"auto-continue"));assertEquals(1,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_ATTEMPT",Integer.class).intValue());}

 @Test public void continuationClearanceCannotReleaseNewSubmittedAttempt(){
  String id=create("a");ready(id);JsonNode original=claimJob(id);ObjectNode rejected=event(original,"DRIVER_REJECTED");((ObjectNode)rejected.get("payload")).put("submissionAccepted",false);clients.event(device,id,rejected,"old-rejected");
  Map<String,Object> continued=jobs.outputCheck(id,check(original,"CONFIRMED_NOT_OUT","CONTINUE"),"continue-check").getData();String oldCheck=(String)continued.get("operatorCheckId");JsonNode next=claimJob(id);
  clients.event(device,id,event(next,"COMMAND_SENT"),"new-sent");clients.event(device,id,event(next,"DEVICE_ACCEPTED"),"new-accepted");jobs.cancel(id,PrintJson.object().put("reason","取消已提交的新尝试"),"cancel-new");
  ObjectNode clear=PrintJson.object().put("deviceIdentity","test-device").put("physicalState","NO_CARD_IN_DEVICE").put("operatorCheckId",oldCheck);expectCode("DEVICE_CLEARANCE_REQUIRED",()->clients.deviceCleared(device,id,clear,"stale-clear"));assertEquals(id,printers.detail(printer).get("activeJobId"));
  assertEquals(oldCheck,PrintJson.read(f.jdbc.queryForObject("SELECT STATE_JSON FROM SMT_PRINT_ATTEMPT WHERE ATTEMPT_ID=?",String.class,original.at("/action/attemptId").asText())).path("operatorCheckId").asText());assertNull(mapper.findJob(id).getOperatorCheckId());
  Map<String,Object> fresh=jobs.outputCheck(id,check(next,"CONFIRMED_NOT_OUT","CANCEL"),"fresh-new-check").getData();assertNotEquals(oldCheck,fresh.get("operatorCheckId"));clear.put("operatorCheckId",(String)fresh.get("operatorCheckId"));clients.deviceCleared(device,id,clear,"fresh-clear");assertNull(printers.detail(printer).get("activeJobId"));
 }
 @Test public void flipStartsWithNoInheritedFrontClearance(){String id=create("a");ready(id);JsonNode front=claimJob(id);clients.event(device,id,event(front,"DEVICE_ACCEPTED"),"front-accepted-clearance");jobs.outputCheck(id,check(front,"CONFIRMED_OUT","NONE"),"front-clearance");jobs.flip(id,PrintJson.object().put("attemptId",front.at("/action/attemptId").asText()).put("orientationConfirmed",true),"flip-clearance");assertNull(mapper.findJob(id).getOperatorCheckId());assertFalse(PrintJobService.state(mapper.findJobAttempt(mapper.findJob(id).getCurrentAttemptId())).hasNonNull("operatorCheckId"));}

 JsonNode startBack(String id){ready(id);JsonNode front=claimJob(id);clients.event(device,id,event(front,"DEVICE_ACCEPTED"),"accepted-"+id);jobs.outputCheck(id,check(front,"CONFIRMED_OUT","NONE"),"front-"+id);jobs.flip(id,PrintJson.object().put("attemptId",front.at("/action/attemptId").asText()).put("orientationConfirmed",true),"flip-"+id);return claimJob(id);}
 @Test public void completedUnknownPhysicalStateCanRecordFreshClearanceWithoutRewritingResult(){
  String id=create("a");JsonNode back=startBack(id);clients.event(device,id,event(back,"DEVICE_ACCEPTED"),"back-accepted");ObjectNode output=check(back,"CONFIRMED_OUT","NONE");((ObjectNode)output.get("physicalCheck")).put("state","STATE_UNKNOWN");String prior=(String)jobs.outputCheck(id,output,"completed-unknown").getData().get("operatorCheckId");assertEquals("COMPLETED",jobs.detail(id).get("status"));
  ObjectNode body=check(back,"DEVICE_CLEARANCE","NONE");Map<String,Object> fresh=jobs.outputCheck(id,body,"completed-clearance").getData();assertEquals("COMPLETED",fresh.get("status"));assertNotEquals(prior,fresh.get("operatorCheckId"));assertEquals(PrintJson.canonical(fresh),PrintJson.canonical(jobs.outputCheck(id,body,"completed-clearance").getData()));assertTrue(PrintJobService.state(mapper.findJobAttempt(back.at("/action/attemptId").asText())).path("confirmedOut").asBoolean());
  ObjectNode clear=PrintJson.object().put("deviceIdentity","test-device").put("physicalState","NO_CARD_IN_DEVICE").put("operatorCheckId",prior);expectCode("DEVICE_CLEARANCE_REQUIRED",()->clients.deviceCleared(device,id,clear,"old-complete-clear"));clear.put("operatorCheckId",(String)fresh.get("operatorCheckId"));clients.deviceCleared(device,id,clear,"completed-clear");assertNull(printers.detail(printer).get("activeJobId"));assertEquals("COMPLETED",jobs.detail(id).get("status"));
 }
 @Test public void failedAndCancelledClearancePreserveTerminalBusinessResult(){for(String terminal:Arrays.asList("FAILED","CANCELLED")){String id=create(terminal);ready(id);JsonNode command=claimJob(id);if("FAILED".equals(terminal))f.jdbc.update("UPDATE SMT_PRINT_JOB SET STATUS='FAILED' WHERE JOB_ID=?",id);else jobs.cancel(id,PrintJson.object().put("reason","原始取消业务理由"),"cancel-terminal");String before=mapper.findJob(id).getStateJson();Map<String,Object> fresh=jobs.outputCheck(id,check(command,"DEVICE_CLEARANCE","NONE"),"terminal-clear-"+terminal).getData();assertEquals(terminal,fresh.get("status"));assertEquals(before,mapper.findJob(id).getStateJson());clients.deviceCleared(device,id,PrintJson.object().put("deviceIdentity","test-device").put("physicalState","NO_CARD_IN_DEVICE").put("operatorCheckId",(String)fresh.get("operatorCheckId")),"release-"+terminal);assertNull(printers.detail(printer).get("activeJobId"));}}

 @Test public void confirmedFrontLateEventsOnlyAuditAndKeepBackInProgress(){String id=create("a");ready(id);JsonNode front=claimJob(id);clients.event(device,id,event(front,"DEVICE_ACCEPTED"),"on-time-front");jobs.outputCheck(id,check(front,"CONFIRMED_OUT","NONE"),"front-physical");jobs.flip(id,PrintJson.object().put("attemptId",front.at("/action/attemptId").asText()).put("orientationConfirmed",true),"begin-back");JsonNode back=claimJob(id);for(String type:Arrays.asList("COMMAND_SENT","DEVICE_ACCEPTED","DEVICE_COMPLETED")){ObjectNode late=event(front,type);late.put("clientSequence",1);Map<String,Object> result=clients.event(device,id,late,"late-front-"+type).getData();assertEquals(true,result.get("late"));assertEquals("BACK_IN_PROGRESS",jobs.detail(id).get("status"));assertEquals(back.at("/action/attemptId").asText(),jobs.detail(id).get("currentAttemptId"));assertFalse(PrintJobService.state(mapper.findJobAttempt(back.at("/action/attemptId").asText())).path("lateConflict").asBoolean());}assertEquals(4,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_EVENT WHERE JOB_ID=?",Integer.class,id).intValue());}

 org.springframework.test.web.servlet.MockMvc jobHttp(){return org.springframework.test.web.servlet.setup.MockMvcBuilders.standaloneSetup(new com.tce.smart.platform.controller.print.PrintJobController(jobs,null)).setControllerAdvice(new com.tce.smart.platform.controller.print.PrintApiAdvice()).addFilters(new com.tce.smart.platform.controller.print.PrintRequestFilter()).build();}
 JsonNode postJobMutation(org.springframework.test.web.servlet.MockMvc mvc,String path,ObjectNode body,String key)throws Exception{return PrintJson.read(mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(path).servletPath(path).contentType("application/json").header("Idempotency-Key",key).content(PrintJson.canonical(body))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andReturn().getResponse().getContentAsString()).path("data");}
 void assertCompleteMutationCommand(String id,JsonNode response,String face){assertFalse("响应必须含新attemptId",response.path("attemptId").asText().isEmpty());assertFalse("响应必须含新commandId",response.path("commandId").asText().isEmpty());assertEquals(face,response.path("face").asText());assertEquals("test-device",response.path("deviceIdentity").asText());assertEquals(printer,response.path("printerProfileId").asText());assertEquals("MANUAL_DUPLEX",response.path("printMode").asText());assertTrue(response.path("templateSnapshotHash").asText().matches("sha256:[a-f0-9]{64}"));assertTrue(response.path("printerSnapshotHash").asText().matches("sha256:[a-f0-9]{64}"));assertEquals(1,response.at("/artifact/pageCount").asInt());assertEquals(85.6,response.at("/artifact/pageWidthMm").asDouble(),0.001);assertEquals(53.98,response.at("/artifact/pageHeightMm").asDouble(),0.001);assertEquals("/api/print-client/v1/jobs/"+id+"/artifacts/"+face+"/download",response.at("/artifact/downloadPath").asText());assertEquals(response.path("commandId"),response.at("/action/commandId"));}
 @Test public void flipHttpResponseContainsCompleteStableBackCommand()throws Exception{String id=create("a");ready(id);JsonNode front=claimJob(id);clients.event(device,id,event(front,"DEVICE_ACCEPTED"),"http-front-accepted");jobs.outputCheck(id,check(front,"CONFIRMED_OUT","NONE"),"http-front-out");ObjectNode body=PrintJson.object().put("attemptId",front.at("/action/attemptId").asText()).put("orientationConfirmed",true);org.springframework.test.web.servlet.MockMvc mvc=jobHttp();String path="/print/v1/print-jobs/"+id+"/flip-confirmation";JsonNode response=postJobMutation(mvc,path,body,"http-back");assertCompleteMutationCommand(id,response,"BACK");assertEquals(response,postJobMutation(mvc,path,body,"http-back"));assertEquals(response.path("commandId"),claimJob(id).at("/action/commandId"));assertEquals(2,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_ATTEMPT WHERE JOB_ID=?",Integer.class,id).intValue());}
 @Test public void continueHttpResponseContainsCompleteStableReplacementCommand()throws Exception{String id=create("a");ready(id);JsonNode original=claimJob(id);ObjectNode rejected=event(original,"DRIVER_REJECTED");((ObjectNode)rejected.get("payload")).put("submissionAccepted",false);clients.event(device,id,rejected,"http-rejected");ObjectNode body=check(original,"CONFIRMED_NOT_OUT","CONTINUE");org.springframework.test.web.servlet.MockMvc mvc=jobHttp();String path="/print/v1/print-jobs/"+id+"/output-check";JsonNode response=postJobMutation(mvc,path,body,"http-replacement");assertCompleteMutationCommand(id,response,"FRONT");assertNotEquals(original.at("/action/commandId"),response.path("commandId"));assertEquals(response,postJobMutation(mvc,path,body,"http-replacement"));assertEquals(response.path("commandId"),claimJob(id).at("/action/commandId"));assertEquals(2,f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_ATTEMPT WHERE JOB_ID=?",Integer.class,id).intValue());}
}
