package com.tce.smart.platform.service.print;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import org.junit.*;
import java.io.ByteArrayOutputStream;
import java.util.*;
import static org.junit.Assert.*;
import static com.tce.smart.platform.service.print.PrintAccessPolicyTest.*;

/** 使用真实H2/MyBatis预览记录与事务验证确认关联；渲染替身只生成合成PDF。 */
public class PrintJobConfirmationTest {
 PrintJobServiceTest fixture;PrintJobPreviewService previews;ObjectNode facts;double geometryWidth=85.6;String staticResourceId;
 @Before public void setup()throws Exception{
  fixture=new PrintJobServiceTest();fixture.setup();facts=PrintJson.object().put("employeeGradeCode","g1").put("classificationCode","STAFF_DEFAULT");facts.putObject("fields").put("staffName","合成甲").put("cardNo","synthetic-card");facts.putObject("resolution").put("bindingRuleId",UUID.randomUUID().toString()).put("bindingRevision",1).put("pairRevision",1).put("frontTemplateVersionId",UUID.randomUUID().toString()).put("backTemplateVersionId",UUID.randomUUID().toString());((ObjectNode)facts.get("resolution")).putObject("selection").put("kind","BOUND");facts.putArray("resources").addObject().put("bindingKey","personPhoto").put("mediaType","image/png").put("sha256",PrintJson.hashBytes(new byte[]{1,2,3})).put("bytesBase64","AQID");
  org.mockito.Mockito.reset(fixture.preparation);
  org.mockito.Mockito.when(fixture.preparation.freeze(org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyBoolean())).thenAnswer(inv->{ObjectNode request=inv.getArgument(0);String id=inv.getArgument(1);boolean preview=inv.getArgument(3);ObjectNode frozen=facts.deepCopy().put("parkId","1").put("subjectType",request.path("subjectType").asText()).put("subjectId",request.path("subjectId").asText()).put("printItemType","STAFF_CARD").put("personType","EMPLOYEE");ObjectNode resolution=(ObjectNode)frozen.get("resolution");resolution.put("manualSelectionConfirmed",!preview).put("confirmedBy",preview?"":"7").put("confirmedAt",java.time.Instant.now().toString());ObjectNode render=frozen.putObject("renderRequest").put("purpose",preview?"PREVIEW":"PRINT").put("requestId",UUID.randomUUID().toString()).put(preview?"previewId":"jobId",id).put("printItemType","STAFF_CARD").put("printMode",request.path("printMode").asText("MANUAL_DUPLEX")).put("expectedFaceCount",2);ArrayNode faces=render.putArray("faceSources");for(String face:Arrays.asList("FRONT","BACK")){ObjectNode f=faces.addObject().put("face",face).put("templateVersionId",resolution.path("FRONT".equals(face)?"frontTemplateVersionId":"backTemplateVersionId").asText());f.putObject("template").putObject("pageSpecJson").put("widthMm",geometryWidth).put("heightMm",53.98);f.putObject("resolvedInput").set("fields",frozen.path("fields").deepCopy());JsonNode photo=frozen.path("resources").get(0);f.putArray("resourceManifest").addObject().put("objectId",UUID.randomUUID().toString()).put("bindingKey","personPhoto").put("contentHash",photo.path("sha256").asText()).put("contentBase64",photo.path("bytesBase64").asText());if(staticResourceId!=null)((ArrayNode)f.get("resourceManifest")).addObject().put("objectId",staticResourceId).put("bindingKey","logo").put("contentHash","sha256:static").put("contentBase64","c3RhdGlj");}return frozen;});
  PrintRendererClient renderer=org.mockito.Mockito.mock(PrintRendererClient.class);org.mockito.Mockito.when(renderer.renderFrozen(org.mockito.ArgumentMatchers.any())).thenAnswer(inv->rendered(inv.getArgument(0)));previews=new PrintJobPreviewService(fixture.mapper,fixture.access,fixture.tx,fixture.preparation,renderer,new PrintJobRenderer(fixture.mapper,fixture.tx,renderer,fixture.execution));
 }
 @After public void close(){if(fixture!=null)fixture.close();}
 ObjectNode request(String subject){return fixture.request(subject);}
 ObjectNode confirmed(String subject){ObjectNode r=request(subject);r.put("previewId",(String)previews.preview(r).get("previewId"));return r;}
 static ObjectNode rendered(JsonNode input)throws Exception{ObjectNode result=PrintJson.object().put("status","READY");ArrayNode artifacts=result.putArray("artifacts");for(String face:Arrays.asList("FRONT","BACK"))artifacts.add(pdf(face,1));result.set("combinedArtifact",pdf("BOTH",2));return result;}
 static ObjectNode pdf(String face,int pages)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();try(org.apache.pdfbox.pdmodel.PDDocument doc=new org.apache.pdfbox.pdmodel.PDDocument()){for(int i=0;i<pages;i++)doc.addPage(new org.apache.pdfbox.pdmodel.PDPage(new org.apache.pdfbox.pdmodel.common.PDRectangle((float)(85.6*72/25.4),(float)(53.98*72/25.4))));doc.save(out);}byte[] bytes=out.toByteArray();return PrintJson.object().put("artifactId",UUID.randomUUID().toString()).put("face",face).put("pageCount",pages).put("widthMm",85.6).put("heightMm",53.98).put("bytes",bytes.length).put("sha256",PrintJson.hashBytes(bytes)).put("mediaType","application/pdf").put("contentBase64",Base64.getEncoder().encodeToString(bytes));}
 @Test public void missingPreviewNeverCreatesJob(){expectCode("PRINT_PREVIEW_REQUIRED",()->fixture.jobs.create(request("a"),"missing-preview"));assertEquals(0,fixture.f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void unchangedSemanticSnapshotSurvivesRandomIdsAndConfirmationMetadata(){ObjectNode request=confirmed("a");String previewId=request.path("previewId").asText();assertFalse(PrintJson.canonical(previews.detail(previewId)).contains("confirmation"));Map<String,Object> first=fixture.jobs.create(request,"same-preview").getData();assertEquals("QUEUED",first.get("status"));assertTrue(fixture.jobs.create(request,"same-preview").isReplayed());assertEquals(PrintJson.canonical(first),PrintJson.canonical(fixture.jobs.create(request,"same-preview").getData()));assertNotEquals(first.get("jobId"),fixture.jobs.create(request,"another-job").getData().get("jobId"));}
 @Test public void bindingAndActualTemplateChangesRequireAnotherPreview(){ObjectNode request=confirmed("a");((ObjectNode)facts.get("resolution")).put("bindingRevision",2);expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(request,"changed-binding"));((ObjectNode)facts.get("resolution")).put("bindingRevision",1).put("frontTemplateVersionId",UUID.randomUUID().toString());expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(request,"changed-template"));assertEquals(0,fixture.f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void photographFieldsGradeAndPrinterRevisionCannotChangeBehindPreview(){ObjectNode request=confirmed("a");ObjectNode original=facts.deepCopy();((ObjectNode)facts.path("resources").get(0)).put("bytesBase64","BAUG").put("sha256",PrintJson.hashBytes(new byte[]{4,5,6}));expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(request,"photo-changed"));facts=original.deepCopy();((ObjectNode)facts.get("fields")).put("staffName","合成乙");expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(request,"fields-changed"));facts=original.deepCopy().put("employeeGradeCode","g2");expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(request,"grade-changed"));facts=original.deepCopy();fixture.printers.save(fixture.printer,PrintJson.object().put("configRevision",0).put("name","修改档案"),"printer-changed");expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(request,"device-changed"));}
 @Test public void previewScopeAndReadyStateAreRequired(){ObjectNode request=confirmed("a");String preview=request.path("previewId").asText();fixture.f.jdbc.update("UPDATE SMT_PRINT_JOB_PREVIEW SET CREATED_BY='other' WHERE PREVIEW_ID=?",preview);expectCode("PRINT_SCOPE_DENIED",()->fixture.jobs.create(request,"other-owner"));fixture.f.jdbc.update("UPDATE SMT_PRINT_JOB_PREVIEW SET CREATED_BY='7',PARK_ID='2' WHERE PREVIEW_ID=?",preview);expectCode("PRINT_SCOPE_DENIED",()->fixture.jobs.create(request,"other-park"));fixture.f.jdbc.update("UPDATE SMT_PRINT_JOB_PREVIEW SET PARK_ID='1',DETAILS_JSON=? WHERE PREVIEW_ID=?","{\"status\":\"RENDER_FAILED\"}",preview);expectCode("PRINT_PREVIEW_REQUIRED",()->fixture.jobs.create(request,"failed-preview"));}
 @Test public void batchRequiresEachPersonsOwnCurrentPreviewAndRollsBackAll(){ObjectNode a=confirmed("a"),b=confirmed("b");ObjectNode batch=request("a");ArrayNode subjects=batch.putArray("subjects");subjects.addObject().put("subjectType","STAFF").put("subjectId","a").put("previewId",a.path("previewId").asText());subjects.addObject().put("subjectType","STAFF").put("subjectId","b").put("previewId",b.path("previewId").asText());fixture.f.jdbc.update("UPDATE SMT_PRINT_JOB_PREVIEW SET DETAILS_JSON=? WHERE PREVIEW_ID=?","{\"status\":\"READY\",\"confirmation\":{\"version\":1,\"fingerprint\":\"sha256:expired\"}}",b.path("previewId").asText());try{fixture.jobs.batch(batch,"stale-batch");fail("单人预览过期必须拒绝整批");}catch(PrintApiException e){assertEquals("BATCH_VALIDATION_FAILED",e.getCode());assertTrue(PrintJson.canonical(e.getDetails()).contains("PRINT_PREVIEW_STALE"));}assertEquals(0,fixture.f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void frozenRecoverySummaryOnlyExposesApprovedFields(){ObjectNode patch=PrintJson.object().put("configRevision",0).put("displayName","冻结设备").put("driverVersion","private-driver");patch.putObject("calibration").put("frontFeedInstruction","正面朝上").put("backFeedInstruction","按校准标记翻面").put("frontRotation",0).put("backRotation",180).put("privateDriverOption","secret");fixture.printers.save(fixture.printer,patch,"calibrated");((ObjectNode)facts.get("fields")).put("staffNo","SYN-001");String job=(String)fixture.jobs.create(confirmed("a"),"summary").getData().get("jobId");((ObjectNode)facts.get("fields")).put("staffName","合成乙").put("staffNo","SYN-002");fixture.printers.save(fixture.printer,PrintJson.object().put("configRevision",1).put("displayName","后来设备"),"changed-summary");JsonNode view=PrintJson.tree(fixture.jobs.detail(job));assertEquals("合成甲",view.at("/subjectSummary/displayName").asText());assertEquals("SYN-001",view.at("/subjectSummary/staffNo").asText());assertEquals("冻结设备",view.at("/printerSummary/displayName").asText());assertEquals("CS220",view.at("/printerSummary/model").asText());assertEquals("正面朝上",view.at("/printerSummary/calibration/frontFeedInstruction").asText());assertEquals(180,view.at("/printerSummary/calibration/backRotation").asInt());String json=PrintJson.canonical(view);assertFalse(json.contains("private-driver"));assertFalse(json.contains("privateDriverOption"));assertFalse(json.contains("synthetic-card"));}
 @Test public void allCurrentBatchCreatesAllAndReplaysWithoutRecheckingChangedFacts(){ObjectNode a=confirmed("a"),b=confirmed("b"),batch=request("a");batch.putArray("subjects").add(a).add(b);Map<String,Object> first=fixture.jobs.batch(batch,"current-batch").getData();assertEquals(2,((List<?>)first.get("jobs")).size());facts.put("employeeGradeCode","g2");assertTrue(fixture.jobs.batch(batch,"current-batch").isReplayed());assertEquals(PrintJson.canonical(first),PrintJson.canonical(fixture.jobs.batch(batch,"current-batch").getData()));assertEquals(2,fixture.f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void topLevelPreviewCannotReplaceMissingPerPersonPreview(){ObjectNode a=confirmed("a"),batch=a.deepCopy();batch.putArray("subjects").addObject().put("subjectType","STAFF").put("subjectId","a");try{fixture.jobs.batch(batch,"missing-item-preview");fail("每人必须提供自己的预览");}catch(PrintApiException e){assertEquals("BATCH_VALIDATION_FAILED",e.getCode());assertTrue(PrintJson.canonical(e.getDetails()).contains("PRINT_PREVIEW_REQUIRED"));}assertEquals(0,fixture.f.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_JOB",Integer.class).intValue());}
 @Test public void anotherSubjectAndChangedSelectionCannotReusePreview(){ObjectNode a=confirmed("a");expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(a.deepCopy().put("subjectId","b"),"another-subject"));((ObjectNode)facts.path("resolution").path("selection")).put("kind","EXPLICIT");expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(a,"another-selection"));}
 @Test public void invalidMissingAndLegacyReadyIdsRequirePreview(){for(String id:Arrays.asList("not-a-uuid",UUID.randomUUID().toString()))expectCode("PRINT_PREVIEW_REQUIRED",()->fixture.jobs.create(request("a").put("previewId",id),"missing-"+id));ObjectNode r=confirmed("a");fixture.f.jdbc.update("UPDATE SMT_PRINT_JOB_PREVIEW SET DETAILS_JSON='{"+"\"status\":\"READY\""+"}' WHERE PREVIEW_ID=?",r.path("previewId").asText());expectCode("PRINT_PREVIEW_REQUIRED",()->fixture.jobs.create(r,"legacy-ready"));}
 @Test public void createHttpReturnsRequiredStaleAndOriginalIdempotentResponse()throws Exception{org.springframework.test.web.servlet.MockMvc mvc=fixture.jobHttp();String path="/print/v1/print-jobs";assertHttpError(mvc,path,request("a"),"http-required",422,"PRINT_PREVIEW_REQUIRED");ObjectNode r=confirmed("a");JsonNode created=postCreation(mvc,path,r,"http-current");facts.put("employeeGradeCode","g2");assertEquals(created,postCreation(mvc,path,r,"http-current"));assertHttpError(mvc,path,r,"http-stale",409,"PRINT_PREVIEW_STALE");ObjectNode another=confirmed("a");assertHttpError(mvc,path,another,"http-current",409,"IDEMPOTENCY_KEY_REUSED");}
 JsonNode postCreation(org.springframework.test.web.servlet.MockMvc mvc,String path,ObjectNode request,String key)throws Exception{return PrintJson.read(mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(path).servletPath(path).contentType("application/json").header("Idempotency-Key",key).content(PrintJson.canonical(request))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isAccepted()).andReturn().getResponse().getContentAsString()).path("data");}
 void assertHttpError(org.springframework.test.web.servlet.MockMvc mvc,String path,ObjectNode request,String key,int status,String code)throws Exception{String result=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(path).servletPath(path).contentType("application/json").header("Idempotency-Key",key).content(PrintJson.canonical(request))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().is(status)).andReturn().getResponse().getContentAsString();assertEquals(code,PrintJson.read(result).at("/error/code").asText());}

 @Test public void geometryStaticResourceIdentityAndPhotoBytesRemainConfirmed(){staticResourceId=UUID.randomUUID().toString();ObjectNode r=confirmed("a");geometryWidth=86;expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(r,"changed-geometry"));geometryWidth=85.6;String original=staticResourceId;staticResourceId=UUID.randomUUID().toString();expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(r,"changed-static-resource"));staticResourceId=original;((ObjectNode)facts.path("resources").get(0)).put("bytesBase64","BAUG");expectCode("PRINT_PREVIEW_STALE",()->fixture.jobs.create(r,"changed-bytes-same-hash"));}
 @Test public void recoverySummaryFallsBackWithoutInventingCalibration(){((ObjectNode)facts.get("fields")).remove("staffName");String id=(String)fixture.jobs.create(confirmed("a"),"fallback-summary").getData().get("jobId");JsonNode view=PrintJson.tree(fixture.jobs.detail(id));assertEquals("a",view.at("/subjectSummary/displayName").asText());assertEquals(0,view.at("/printerSummary/calibration").size());assertTrue(view.at("/subjectSummary/staffNo").isMissingNode());}

}
