package com.tce.smart.platform.service.print;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tce.smart.platform.api.dto.req.print.*;
import com.tce.smart.platform.core.mapper.*;
import org.junit.*;
import org.mybatis.spring.*;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.Assert.*;
import static com.tce.smart.platform.service.print.PrintAccessPolicyTest.*;
/** 使用隔离的 H2 和真实 Mapper 验证绑定、冻结版本及事务竞争。 */
public class PrintTemplateResolverTest {
 private PrintTemplateServiceTest fixture; private PrintTemplateResolver resolver; private PrintResolutionProperties config; private PrintBindingRequest rule; private String front,back,pair;
 @Before public void setup() throws Exception {
  fixture=new PrintTemplateServiceTest();fixture.temporary.create();fixture.setup();
  fixture.jdbc.execute("CREATE TABLE SMT_PARK_BU (ID INTEGER,COMP_ID VARCHAR(64),PARK_ID INTEGER)");fixture.jdbc.update("INSERT INTO SMT_PARK_BU VALUES (1,'c1',1)");fixture.jdbc.execute("CREATE TABLE SMT_ORGANIZE_RELATION (ID BIGINT,PARK_ID INTEGER,COMP_TYPE INTEGER)");fixture.jdbc.execute("CREATE TABLE SMT_SECURITYAREA_SUPPLIER (ID BIGINT,PARK_ID INTEGER,DEL_FLAG INTEGER)");fixture.jdbc.execute("CREATE TABLE SMT_PARK (ID VARCHAR(64) PRIMARY KEY)");fixture.jdbc.update("INSERT INTO SMT_PARK VALUES ('1')");
  fixture.jdbc.execute("CREATE TABLE SMT_PRINT_BIND_RULE (BINDING_RULE_ID VARCHAR(36) PRIMARY KEY,PARK_ID VARCHAR(64),PRINT_ITEM_TYPE VARCHAR(64),PERSON_TYPE VARCHAR(64),CLASSIFICATION_CODE VARCHAR(64),SCOPE_TYPE VARCHAR(32),SCOPE_ID VARCHAR(64),TEMPLATE_ID VARCHAR(36),PAIR_ID VARCHAR(36),EMPLOYEE_GRADE_CODES_CLOB CLOB,PRIORITY INTEGER,VALID_FROM TIMESTAMP,VALID_TO TIMESTAMP,STATUS VARCHAR(16),REVISION BIGINT,CREATED_BY VARCHAR(64),CREATED_AT TIMESTAMP,UPDATED_BY VARCHAR(64),UPDATED_AT TIMESTAMP)");
  PrintFeatureProperties feature=properties();feature.getPermissions().put("execute","test:print:execute");PrintAccessPolicy access=new PrintAccessPolicy(feature,null);
  config=new PrintResolutionProperties();PrintResolutionProperties.GradeDictionary dictionary=new PrintResolutionProperties.GradeDictionary();dictionary.setConfirmed(true);dictionary.getCodes().put("g1","测试职层一");dictionary.getCodes().put("g2","测试职层二");config.getEmployeeGrades().put("1",dictionary);
  SqlSessionFactoryBean factory=new SqlSessionFactoryBean();factory.setDataSource(fixture.source);factory.setMapperLocations(new org.springframework.core.io.Resource[]{new ClassPathResource("mapper/PrintTemplateMapper.xml"),new ClassPathResource("mapper/PrintBindingMapper.xml")});SqlSessionTemplate sql=new SqlSessionTemplate(factory.getObject());
  resolver=new PrintTemplateResolver(sql.getMapper(PrintBindingMapper.class),sql.getMapper(PrintTemplateMapper.class),access,new PrintTemplateValidator(access,feature),config,new DataSourceTransactionManager(fixture.source));
  front=publish("FRONT");back=publish("BACK");PrintPairRequest p=new PrintPairRequest();p.setName("合成组合");p.setPrintItemType("STAFF_CARD");p.setPersonType("EMPLOYEE");p.setClassificationCode("STAFF_DEFAULT");p.setFrontTemplateVersionId(front);p.setBackTemplateVersionId(back);pair=(String)fixture.service.createPair("1",p,"pair").getData().get("pairId");
  rule=new PrintBindingRequest();rule.setParkId("1");rule.setPriority(100);rule.setPrintItemType("STAFF_CARD");rule.setPersonType("EMPLOYEE");rule.setClassificationCode("STAFF_DEFAULT");rule.setScopeType("EXPLICIT_DEFAULT");rule.setEmployeeGradeCodes(Arrays.asList("g1","g2"));rule.setPairId(pair);rule.setValidFrom("2020-01-01T00:00:00Z");manager();
 }
 @After public void close(){if(fixture!=null){fixture.close();fixture.temporary.delete();}}
 private void manager(){login(1,"test:print:read","test:print:write","test:print:publish","test:print:resource","test:print:execute");}
 private String publish(String face)throws Exception{String id=fixture.create(face);Map<String,Object> t=fixture.service.detail(id);PrintPublishRequest p=new PrintPublishRequest();p.setDraftRevision(0L);p.setDraftVersionId((String)t.get("currentDraftVersionId"));return (String)fixture.service.publish(id,p,UUID.randomUUID().toString()).getData().get("templateVersionId");}
 private ObjectNode subject(){ObjectNode s=PrintJson.object().put("parkId","1").put("printItemType","STAFF_CARD").put("personType","EMPLOYEE").put("classificationCode","STAFF_DEFAULT").put("subjectType","STAFF").put("subjectId","s1").put("companyId","c1").put("employeeGradeCode","g1").put("employeeGradeName","测试职层一").put("employeeGradeSource","DHR");s.putObject("fields");s.putArray("resources");return s;}
 private ObjectNode explicit(){return PrintJson.object().put("kind","EXPLICIT").put("manualSelectionConfirmed",true).put("frontTemplateVersionId",front).put("backTemplateVersionId",back);}
 @Test public void specificBeatsDefaultAndIdempotencyReplaysOriginal(){PrintMutationResult created=resolver.create("1",rule,"create");String id=(String)created.getData().get("bindingRuleId");assertEquals(id,resolver.resolve("1",subject()).path("bindingRuleId").asText());rule.setScopeType("COMPANY");rule.setScopeId("c1");rule.setPriority(1);resolver.create("1",rule,"specific");assertEquals("SPECIFIC_COMPANY",resolver.resolve("1",subject()).path("matchLevel").asText());rule.setScopeType("EXPLICIT_DEFAULT");rule.setScopeId(null);rule.setPriority(100);assertTrue(resolver.create("1",rule,"create").isReplayed());rule.setEmployeeGradeCodes(Collections.singletonList("g2"));expectCode("IDEMPOTENCY_KEY_REUSED",()->resolver.create("1",rule,"create"));assertEquals(2,fixture.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_BIND_RULE",Integer.class).intValue());assertTrue(fixture.jdbc.queryForObject("SELECT DETAILS_JSON FROM SMT_PRINT_AUDIT WHERE OBJECT_ID=?",String.class,id).contains("requestId"));}
 @Test public void invalidGradesRemainHardFailures(){ObjectNode s=subject();s.remove("employeeGradeCode");expectCode("EMPLOYEE_GRADE_REQUIRED",()->resolver.select("1",s,explicit()));s.put("employeeGradeCode","null");expectCode("EMPLOYEE_GRADE_UNMAPPED",()->resolver.select("1",s,explicit()));s.put("employeeGradeCode","g1").put("employeeGradeName","");expectCode("EMPLOYEE_GRADE_UNMAPPED",()->resolver.select("1",s,explicit()));config.getEmployeeGrades().get("1").setConfirmed(false);expectCode("EMPLOYEE_GRADE_UNMAPPED",()->resolver.employeeGrades("1"));}
 @Test public void disjointGradesAndHalfOpenExpiry(){rule.setEmployeeGradeCodes(Collections.singletonList("g2"));resolver.create("1",rule,"g2");expectCode("EMPLOYEE_GRADE_TEMPLATE_NOT_FOUND",()->resolver.resolve("1",subject()));rule.setEmployeeGradeCodes(Collections.singletonList("g1"));rule.setValidTo("2020-01-02T00:00:00Z");resolver.create("1",rule,"expired");expectCode("EMPLOYEE_GRADE_TEMPLATE_NOT_FOUND",()->resolver.resolve("1",subject()));rule.setValidFrom("2020-01-02T00:00:00Z");rule.setValidTo(null);resolver.create("1",rule,"current");assertEquals(pair,resolver.resolve("1",subject()).at("/selection/pairId").asText());expectCode("BINDING_AMBIGUOUS",()->resolver.create("1",rule,"overlap"));}
 @Test public void manualUnboundVersionsRequireConfirmationAndStayImmutable()throws Exception{ObjectNode selected=resolver.select("1",subject(),explicit());assertEquals(front,selected.path("frontTemplateVersionId").asText());assertFalse(selected.hasNonNull("bindingRuleId"));assertEquals("NOT_FOUND",selected.at("/automaticResolution/status").asText());assertEquals("7",selected.path("confirmedBy").asText());assertTrue(selected.hasNonNull("confirmedAt"));ObjectNode e=explicit();e.remove("manualSelectionConfirmed");expectCode("MANUAL_SELECTION_CONFIRMATION_REQUIRED",()->resolver.select("1",subject(),e));ObjectNode p=PrintJson.object().put("kind","PAIR").put("pairId",pair).put("pairRevision",99).put("manualSelectionConfirmed",true);expectCode("PAIR_REVISION_CONFLICT",()->resolver.select("1",subject(),p));String another=publish("FRONT");resolver.create("1",rule,"default");ObjectNode changed=explicit().put("frontTemplateVersionId",another);assertTrue(resolver.select("1",subject(),changed).path("differsFromAutomatic").asBoolean());fixture.jdbc.update("UPDATE SMT_PRINT_TEMPLATE SET CURRENT_PUBLISHED_VERSION_ID=? WHERE CURRENT_PUBLISHED_VERSION_ID=?",another,front);assertEquals(front,resolver.select("1",subject(),explicit()).path("frontTemplateVersionId").asText());}
 @Test public void historicalAmbiguityMayWarnButScopeAndPermissionsNeverDo(){resolver.create("1",rule,"default");fixture.jdbc.update("INSERT INTO SMT_PRINT_BIND_RULE SELECT ?,PARK_ID,PRINT_ITEM_TYPE,PERSON_TYPE,CLASSIFICATION_CODE,SCOPE_TYPE,SCOPE_ID,TEMPLATE_ID,PAIR_ID,EMPLOYEE_GRADE_CODES_CLOB,PRIORITY,VALID_FROM,VALID_TO,STATUS,REVISION,CREATED_BY,CREATED_AT,UPDATED_BY,UPDATED_AT FROM SMT_PRINT_BIND_RULE",UUID.randomUUID().toString());expectCode("BINDING_AMBIGUOUS",()->resolver.resolve("1",subject()));assertEquals("AMBIGUOUS",resolver.select("1",subject(),explicit()).at("/automaticResolution/status").asText());expectCode("PRINT_SCOPE_DENIED",()->resolver.select("1",subject().put("parkId","2"),explicit()));fixture.jdbc.update("UPDATE SMT_PRINT_TEMPLATE_VER SET PARK_ID='2' WHERE TEMPLATE_VERSION_ID=?",front);expectCode("PRINT_SCOPE_DENIED",()->resolver.select("1",subject(),explicit()));login(1,"test:print:read");expectCode("PRINT_PERMISSION_DENIED",()->resolver.select("1",subject(),explicit()));}
 @Test public void concurrentOverlapsHaveOneWinner()throws Exception{ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);List<Future<String>> results=new ArrayList<>();try{for(int i=0;i<2;i++){final String key="race"+i;results.add(pool.submit(()->{manager();start.await();try{resolver.create("1",rule,key);return "CREATED";}catch(PrintApiException e){return e.getCode();}finally{org.springframework.security.core.context.SecurityContextHolder.clearContext();}}));}start.countDown();List<String> codes=Arrays.asList(results.get(0).get(20,TimeUnit.SECONDS),results.get(1).get(20,TimeUnit.SECONDS));assertTrue(codes.contains("CREATED"));assertTrue(codes.contains("BINDING_AMBIGUOUS"));assertEquals(1,fixture.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_BIND_RULE",Integer.class).intValue());}finally{pool.shutdownNow();}}
 @Test public void patchRejectsTwoTargetsInsteadOfSilentlyDroppingOne(){String id=(String)resolver.create("1",rule,"default").getData().get("bindingRuleId");rule.setRevision(0L);rule.setTemplateId(fixture.jdbc.queryForObject("SELECT TEMPLATE_ID FROM SMT_PRINT_TEMPLATE_VER WHERE TEMPLATE_VERSION_ID=?",String.class,front));expectCode("INVALID_REQUEST",()->resolver.save(id,rule,"invalid-patch"));}
 @Test public void updateDisableRevisionAndReplayKeepOriginalAudit(){String id=(String)resolver.create("1",rule,"default").getData().get("bindingRuleId");rule.setRevision(0L);rule.setEmployeeGradeCodes(Collections.singletonList("g2"));assertEquals(1L,((Number)resolver.save(id,rule,"patch").getData().get("revision")).longValue());expectCode("EMPLOYEE_GRADE_TEMPLATE_NOT_FOUND",()->resolver.resolve("1",subject()));expectCode("BINDING_REVISION_CONFLICT",()->resolver.save(id,rule,"stale"));resolver.disable(id,1L,"disable");assertEquals("DISABLED",resolver.detail(id).get("status"));assertTrue(resolver.save(id,rule,"patch").isReplayed());assertEquals(3,fixture.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_AUDIT WHERE OBJECT_ID=?",Integer.class,id).intValue());}
 @Test public void explicitRejectsClassificationAndFaceMismatch(){expectCode("TEMPLATE_VALIDATION_FAILED",()->resolver.select("1",subject().put("classificationCode","UNRELATED"),explicit()));expectCode("TEMPLATE_VALIDATION_FAILED",()->resolver.select("1",subject(),explicit().put("backTemplateVersionId",front)));}
 @Test public void visitorSecurityUsesOneControlledQrAndRequiresCredential()throws Exception{
  PrintTemplateRequest v=fixture.draft("FRONT");v.setPrintItemType("VISITOR_SLIP");v.setPersonType("VISITOR");v.setClassificationCode("VISITOR_SECURITY");
  ObjectNode component=((com.fasterxml.jackson.databind.node.ArrayNode)v.getLayoutJson().path("schemas").get(0)).addObject().put("name","凭证码").put("type","qrcode").put("width",10).put("height",10);component.putObject("position").put("x",1).put("y",1);
  ((com.fasterxml.jackson.databind.node.ArrayNode)v.getFieldSchemaJson().path("fields")).addObject().put("key","visitorCredentialPayload").put("schemaName","凭证码").put("required",true);
  String template=(String)fixture.service.create("1",v).get("templateId");PrintPublishRequest publication=new PrintPublishRequest();publication.setDraftRevision(0L);publication.setDraftVersionId((String)fixture.service.detail(template).get("currentDraftVersionId"));String version=(String)fixture.service.publish(template,publication,"visitor-publish").getData().get("templateVersionId");
  ObjectNode person=subject().put("printItemType","VISITOR_SLIP").put("personType","VISITOR").put("classificationCode","VISITOR_SECURITY");ObjectNode selection=PrintJson.object().put("kind","EXPLICIT").put("frontTemplateVersionId",version).put("manualSelectionConfirmed",true);
  expectCode("SECURITY_QR_TEMPLATE_REQUIRED",()->resolver.select("1",person,selection));((ObjectNode)person.path("fields")).put("visitorCredentialPayload","synthetic-credential");ObjectNode result=resolver.select("1",person,selection);assertTrue(result.path("securityQrRequired").asBoolean());assertFalse(result.has("backTemplateVersionId"));expectCode("INVALID_REQUEST",()->resolver.select("1",person,selection.deepCopy().put("backTemplateVersionId",back)));
 }
 @Test public void httpAuditAndSourceClassificationCannotBeOverridden()throws Exception{
  PrintFeatureProperties feature=properties();feature.getPermissions().put("execute","test:print:execute");PrintAccessPolicy policy=new PrintAccessPolicy(feature,null);
  com.tce.smart.platform.controller.print.PrintBindingController controller=new com.tce.smart.platform.controller.print.PrintBindingController(resolver,(park,type,id)->subject(),policy);
  org.springframework.test.web.servlet.MockMvc mvc=org.springframework.test.web.servlet.setup.MockMvcBuilders.standaloneSetup(controller).setControllerAdvice(new com.tce.smart.platform.controller.print.PrintApiAdvice()).addFilters(new com.tce.smart.platform.controller.print.PrintRequestFilter()).build();
  org.springframework.mock.web.MockHttpServletResponse response=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/print/v1/bindings").servletPath("/print/v1/bindings").contentType("application/json").header("Idempotency-Key","http").content(PrintJson.canonical(rule))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isCreated()).andReturn().getResponse();
  String id=PrintJson.read(response.getContentAsString()).at("/data/bindingRuleId").asText();assertEquals(response.getHeader("X-Request-Id"),PrintJson.read(fixture.jdbc.queryForObject("SELECT DETAILS_JSON FROM SMT_PRINT_AUDIT WHERE OBJECT_ID=?",String.class,id)).path("requestId").asText());
  mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/print/v1/bindings/resolve").servletPath("/print/v1/bindings/resolve").param("subjectId","s1").param("subjectType","STAFF").param("printItemType","STAFF_CARD").param("personType","EMPLOYEE").param("classificationCode","WRONG")).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isUnprocessableEntity());
 }

 @Test public void organizationAndSupplierScopesMustHaveUniqueLiveParkOwnership(){
  rule.setScopeType("COMPANY");rule.setScopeId("other");fixture.jdbc.update("INSERT INTO SMT_PARK_BU VALUES (2,'other',2)");expectCode("PRINT_SCOPE_DENIED",()->resolver.create("1",rule,"foreign-company"));
  rule.setScopeId("c1");fixture.jdbc.update("INSERT INTO SMT_PARK_BU VALUES (3,'c1',2)");expectCode("PRINT_SCOPE_DENIED",()->resolver.create("1",rule,"ambiguous-company"));
  rule.setScopeId("42");fixture.jdbc.update("INSERT INTO SMT_ORGANIZE_RELATION VALUES (42,1,1)");expectCode("BINDING_SCOPE_NOT_FOUND",()->resolver.create("1",rule,"external-company"));
  rule.setScopeType("SUPPLIER");rule.setScopeId("51");fixture.jdbc.update("INSERT INTO SMT_SECURITYAREA_SUPPLIER VALUES (51,2,0)");expectCode("PRINT_SCOPE_DENIED",()->resolver.create("1",rule,"foreign-supplier"));
  fixture.jdbc.update("UPDATE SMT_SECURITYAREA_SUPPLIER SET PARK_ID=1,DEL_FLAG=1 WHERE ID=51");expectCode("BINDING_SCOPE_NOT_FOUND",()->resolver.create("1",rule,"deleted-supplier"));
  fixture.jdbc.update("UPDATE SMT_SECURITYAREA_SUPPLIER SET DEL_FLAG=0 WHERE ID=51");resolver.create("1",rule,"supplier");ObjectNode s=subject().put("supplierId","51");s.remove("companyId");assertEquals("SPECIFIC_SUPPLIER",resolver.resolve("1",s).path("matchLevel").asText());
 }

 @Test public void omittedPatchExpiryKeepsExistingWindowButExplicitNullClearsIt(){
  rule.setValidTo("2050-01-01T00:00:00Z");String id=(String)resolver.create("1",rule,"expiring").getData().get("bindingRuleId");PrintBindingRequest partial=new PrintBindingRequest();partial.setRevision(0L);assertEquals("2050-01-01T00:00:00Z",resolver.save(id,partial,"partial").getData().get("validTo"));
  partial.setValidTo(null);expectCode("IDEMPOTENCY_KEY_REUSED",()->resolver.save(id,partial,"partial"));
  partial.setRevision(1L);partial.setValidTo(null);assertNull(resolver.save(id,partial,"clear-expiry").getData().get("validTo"));
 }

 @Test public void visitorBindingCannotFollowAnotherTemplatesPublishedPointer()throws Exception{
  PrintTemplateRequest v=fixture.draft("FRONT");v.setPrintItemType("VISITOR_SLIP");v.setPersonType("VISITOR");v.setClassificationCode("VISITOR_NORMAL");String original=(String)fixture.service.create("1",v).get("templateId");PrintPublishRequest p=new PrintPublishRequest();p.setDraftRevision(0L);p.setDraftVersionId((String)fixture.service.detail(original).get("currentDraftVersionId"));String version=(String)fixture.service.publish(original,p,"visitor-normal").getData().get("templateVersionId");String other=(String)fixture.service.create("1",v).get("templateId");fixture.jdbc.update("UPDATE SMT_PRINT_TEMPLATE SET CURRENT_PUBLISHED_VERSION_ID=? WHERE TEMPLATE_ID=?",version,other);
  PrintBindingRequest binding=new PrintBindingRequest();binding.setParkId("1");binding.setPrintItemType("VISITOR_SLIP");binding.setPersonType("VISITOR");binding.setClassificationCode("VISITOR_NORMAL");binding.setScopeType("EXPLICIT_DEFAULT");binding.setTemplateId(other);binding.setValidFrom("2020-01-01T00:00:00Z");expectCode("TEMPLATE_VALIDATION_FAILED",()->resolver.create("1",binding,"corrupt-pointer"));
 }

 @Test public void nonEmployeeUiPayloadWithNullGradesPersistsThroughHttpCreateAndEdit()throws Exception{
  PrintTemplateRequest template=fixture.draft("FRONT");template.setPrintItemType("VISITOR_SLIP");template.setPersonType("VISITOR");template.setClassificationCode("VISITOR_NORMAL");
  String templateId=(String)fixture.service.create("1",template).get("templateId");PrintPublishRequest publication=new PrintPublishRequest();publication.setDraftRevision(0L);publication.setDraftVersionId((String)fixture.service.detail(templateId).get("currentDraftVersionId"));fixture.service.publish(templateId,publication,"ui-visitor-publish");
  PrintFeatureProperties feature=properties();feature.getPermissions().put("execute","test:print:execute");PrintAccessPolicy policy=new PrintAccessPolicy(feature,null);
  com.tce.smart.platform.controller.print.PrintBindingController controller=new com.tce.smart.platform.controller.print.PrintBindingController(resolver,(park,type,id)->subject(),policy);
  org.springframework.test.web.servlet.MockMvc mvc=org.springframework.test.web.servlet.setup.MockMvcBuilders.standaloneSetup(controller).setControllerAdvice(new com.tce.smart.platform.controller.print.PrintApiAdvice()).addFilters(new com.tce.smart.platform.controller.print.PrintRequestFilter()).build();
  // 与页面请求相同：非员工职级为null；新增、编辑均经过真实Controller、Resolver和SQL。
  ObjectNode body=PrintJson.object().put("parkId","1").put("printItemType","VISITOR_SLIP").put("personType","VISITOR").put("classificationCode","VISITOR_NORMAL").put("scopeType","EXPLICIT_DEFAULT").putNull("scopeId").putNull("employeeGradeCodes").put("priority",100).put("validFrom","2026-01-01T00:00:00Z").putNull("validTo").put("templateId",templateId);
  org.springframework.mock.web.MockHttpServletResponse created=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/print/v1/bindings").servletPath("/print/v1/bindings").contentType("application/json").header("Idempotency-Key","ui-visitor-create").content(PrintJson.canonical(body))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isCreated()).andReturn().getResponse();
  String id=PrintJson.read(created.getContentAsString()).at("/data/bindingRuleId").asText();body.put("revision",0).put("priority",99);
  mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch("/print/v1/bindings/"+id).servletPath("/print/v1/bindings/"+id).contentType("application/json").header("Idempotency-Key","ui-visitor-edit").content(PrintJson.canonical(body))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk());
  assertEquals(1,fixture.jdbc.queryForObject("SELECT COUNT(*) FROM SMT_PRINT_BIND_RULE",Integer.class).intValue());assertNull(fixture.jdbc.queryForObject("SELECT EMPLOYEE_GRADE_CODES_CLOB FROM SMT_PRINT_BIND_RULE WHERE BINDING_RULE_ID=?",String.class,id));assertEquals(99,fixture.jdbc.queryForObject("SELECT PRIORITY FROM SMT_PRINT_BIND_RULE WHERE BINDING_RULE_ID=?",Integer.class,id).intValue());
 }

}
