FROM anapsix/alpine-java:8_server-jre_unlimited

MAINTAINER smart@bjtce.com

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /smart-dispatcher

WORKDIR /smart-dispatcher

EXPOSE 8082

ADD ./smart-dispatcher/smart-dispatcher-biz/target/smart-dispatcher-biz.jar ./

ARG APP_ENV

ENV APP_ENV $APP_ENV

CMD java -Dspring.profiles.active=$APP_ENV -Djava.security.egd=file:/dev/./urandom -jar smart-dispatcher-biz.jar
