package com.tce.smart.schedule.service.platform.impl;
import com.tce.smart.common.core.model.Result;import com.tce.smart.dispatcher.api.dto.req.DispatcherDTO;import com.tce.smart.dispatcher.api.enums.EventEnum;import com.tce.smart.dispatcher.api.feign.RemoteDispatcherService;
import com.tce.smart.platform.core.entity.*;import com.tce.smart.platform.core.mapper.*;import com.tce.smart.platform.core.service.*;import com.tce.smart.platform.core.service.impl.*;import com.tce.smart.platform.core.dto.authversion.AuthVersion.*;import com.tce.smart.platform.core.dto.authtransport.AuthTransport.*;import com.tce.smart.schedule.config.AuthOperationSchedulerProperties;
import org.junit.*;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import static org.mockito.Mockito.*;
/** 真实PERSON协调与Facade配合受控持久层和协议，不假定平台替客户端去重。 */
public class AuthOperationPersonOwnerTest {
 private final Map<Long,SmtAuthTransportPhase> rows=new LinkedHashMap<>();private final Map<String,SmtAuthPersonOwner> owners=new LinkedHashMap<>();private final Map<Long,SmtAuthOperationTarget> targets=new HashMap<>();private final Map<Long,SmtAuthOperationAttempt> attempts=new HashMap<>();private final Map<Long,List<SmtAuthSelectionSource>> sources=new HashMap<>();private final Map<String,String> identities=new HashMap<>();
 private AuthOperationTransportMapper phases;private AuthOperationPersonOwnerMapper ownerMapper;private AuthOperationTransportService service;private AuthOperationTransportFacade facade;
 private final AtomicInteger creates=new AtomicInteger(),faces=new AtomicInteger(),gets=new AtomicInteger(),configs=new AtomicInteger();private boolean losePerson;private Runnable beforeEmptyPeople;
 @Before public void setup(){
  phases=mock(AuthOperationTransportMapper.class);ownerMapper=mock(AuthOperationPersonOwnerMapper.class);SmtAuthOperationTargetMapper tm=mock(SmtAuthOperationTargetMapper.class);SmtAuthOperationAttemptMapper am=mock(SmtAuthOperationAttemptMapper.class);AuthOperationVersionService versions=mock(AuthOperationVersionService.class);EmployeeAuthOperationService employee=mock(EmployeeAuthOperationService.class);
  service=new AuthOperationTransportService(phases,null,null,versions,tm,am,null,null,null,employee,null,null,null);org.springframework.test.util.ReflectionTestUtils.setField(service,"personOwners",ownerMapper);
  when(phases.byId(anyLong())).thenAnswer(i->rows.get(i.getArgument(0)));when(phases.phase(anyLong(),anyString())).thenAnswer(i->rows.values().stream().filter(p->Objects.equals(p.getAttemptId(),i.getArgument(0))&&p.getPhase().equals(i.getArgument(1))).findFirst().orElse(null));
  when(phases.insert(any())).thenAnswer(i->{SmtAuthTransportPhase p=i.getArgument(0);rows.put(p.getId(),p);return 1;});when(phases.routeTableInstalled()).thenReturn(1);when(phases.routeMatches(any())).thenReturn(1);
  when(phases.transition(anyLong(),anyString(),anyString(),any(),any())).thenAnswer(i->{SmtAuthTransportPhase p=rows.get(i.getArgument(0));if(!p.getState().equals(i.getArgument(1))||(p.getExternalId()!=null&&!p.getExternalId().equals(i.getArgument(3))))return 0;p.setState(i.getArgument(2));if(p.getExternalId()==null)p.setExternalId(i.getArgument(3));p.setErrorCode(i.getArgument(4));return 1;});
  when(phases.start(anyLong(),anyString(),any())).thenAnswer(i->{SmtAuthTransportPhase p=rows.get(i.getArgument(0));if(!"PREPARED".equals(p.getState()))return 0;p.setState("INTENT");p.setRequestKey(i.getArgument(1));p.setPersonId(i.getArgument(2));return 1;});
  when(phases.personBinding(any(),anyString(),anyString(),anyString(),any(),any())).thenAnswer(i->{SmtAuthTransportPhase p=i.getArgument(0);if(!"PREPARED".equals(p.getState()))return 0;p.setPersonOperationKey(i.getArgument(1));p.setPersonIdentityHash(i.getArgument(2));p.setOrgIndexCode(i.getArgument(3));p.setPersonId(i.getArgument(4));p.setPersonProofPhaseId(i.getArgument(5));return 1;});
  when(phases.claimPerson(any(),anyString())).thenAnswer(i->{SmtAuthTransportPhase p=i.getArgument(0);identities.putIfAbsent(p.getInstanceId()+":"+i.getArgument(1),p.getSubjectId());return 1;});when(phases.ownsPerson(any(),anyString())).thenAnswer(i->{SmtAuthTransportPhase p=i.getArgument(0);return p.getSubjectId().equals(identities.get(p.getInstanceId()+":"+i.getArgument(1)))?1:0;});when(phases.conflictingPerson(any(),anyString())).thenAnswer(i->{SmtAuthTransportPhase p=i.getArgument(0);String subject=identities.get(p.getInstanceId()+":"+i.getArgument(1));return subject!=null&&!subject.equals(p.getSubjectId())?1:0;});
  when(tm.selectById(anyLong())).thenAnswer(i->targets.get(i.getArgument(0)));when(am.selectByIdAndTarget(anyLong(),anyLong())).thenAnswer(i->attempts.get(i.getArgument(0)));when(employee.sourcesForTarget(anyLong())).thenAnswer(i->sources.get(i.getArgument(0)));
  when(versions.currentDesired(anyString())).thenAnswer(i->{SmtAuthTransportPhase p=rows.values().stream().filter(x->i.getArgument(0).equals(x.getResourceId())).findFirst().get();return ResourceDecision.builder().resourceId(p.getResourceId()).generation(1).blockingAttemptId(p.getAttemptId()).build();});
  when(ownerMapper.lock(anyString())).thenAnswer(i->owners.get(i.getArgument(0)));when(ownerMapper.lockByPhase(anyLong())).thenAnswer(i->owners.values().stream().filter(o->Objects.equals(o.getOwnerPhaseId(),i.getArgument(0))).findFirst().orElse(null));when(ownerMapper.insert(any())).thenAnswer(i->{SmtAuthPersonOwner o=i.getArgument(0);if(owners.containsKey(o.getId()))throw new org.springframework.dao.DuplicateKeyException("竞争");owners.put(o.getId(),o);return 1;});
  when(ownerMapper.setPhase(anyString(),anyLong())).thenAnswer(i->{owners.get(i.getArgument(0)).setOwnerPhaseId(i.getArgument(1));return 1;});
  when(ownerMapper.start(anyString(),anyLong(),anyString(),anyString())).thenAnswer(i->{SmtAuthPersonOwner o=owners.get(i.getArgument(0));if(!"PREPARED".equals(o.getState())||!o.getOwnerPhaseId().equals(i.getArgument(1))||!o.getOwnerToken().equals(i.getArgument(2)))return 0;o.setState("INTENT");o.setRequestKey(i.getArgument(3));return 1;});
  when(ownerMapper.accepted(anyString(),anyLong(),anyString(),anyString(),anyString())).thenAnswer(i->{SmtAuthPersonOwner o=owners.get(i.getArgument(0));if(!Arrays.asList("INTENT","UNKNOWN").contains(o.getState())||!o.getOwnerPhaseId().equals(i.getArgument(1))||!o.getOwnerToken().equals(i.getArgument(2))||!o.getRequestKey().equals(i.getArgument(3)))return 0;o.setState("ACCEPTED");o.setPersonId(i.getArgument(4));return 1;});
  when(ownerMapper.mark(anyString(),anyString(),anyString(),anyString())).thenAnswer(i->{SmtAuthPersonOwner o=owners.get(i.getArgument(0));if(!o.getState().equals(i.getArgument(1)))return 0;o.setState(i.getArgument(2));o.setReason(i.getArgument(3));return 1;});
  when(ownerMapper.history(any())).thenAnswer(i->{SmtAuthTransportPhase c=i.getArgument(0);List<SmtAuthTransportPhase> result=new ArrayList<>();for(SmtAuthTransportPhase p:rows.values())if(p.getInstanceId().equals(c.getInstanceId())&&p.getSubjectId().equals(c.getSubjectId())&&("ISC_PERSON".equals(p.getPhase())||p.getPersonId()!=null)){result.add(p);if(result.size()==2)break;}return result;});
  RemoteDispatcherService remote=mock(RemoteDispatcherService.class);SmtImageService images=mock(SmtImageService.class);when(images.getImageBase64ByCode("image")).thenReturn("actual-attempt-image");AuthOperationSchedulerProperties props=new AuthOperationSchedulerProperties();AuthOperationSchedulerProperties.Instance instance=new AuthOperationSchedulerProperties.Instance();instance.setId("isc");instance.setAccessType("ISC");instance.setParks(Arrays.asList(1,2));props.setInstances(Collections.singletonList(instance));facade=new AuthOperationTransportFacade(service,remote,images,props);org.springframework.test.util.ReflectionTestUtils.setField(facade,"xcPark",1);org.springframework.test.util.ReflectionTestUtils.setField(facade,"xcOrg","org");org.springframework.test.util.ReflectionTestUtils.setField(facade,"hfOrg","org");
  when(remote.dispatch(any(),anyString())).thenAnswer(i->{DispatcherDTO d=i.getArgument(0);if(EventEnum.ISC_PERSON_GET.getCode().equals(d.getEventType())){gets.incrementAndGet();if(beforeEmptyPeople!=null)beforeEmptyPeople.run();return Result.success("{\"list\":[]}");}if(EventEnum.ISC_PERSON_ADD.getCode().equals(d.getEventType())){creates.incrementAndGet();return losePerson?Result.success("{}"):Result.success("{\"personId\":\"person-real\"}");}if(EventEnum.ISC_FACE_ADD.getCode().equals(d.getEventType())){faces.incrementAndGet();return Result.success("{}");}configs.incrementAndGet();return Result.success("{\"taskId\":\"config-real\"}");});
 }
 @Test public void twentyDevicesCreateOnePersonAndUploadNineteenIndependentFaces(){for(int n=0;n<20;n++){SmtAuthTransportPhase p=config(100+n,"op");Assert.assertEquals(1,run(p).getProcessed());}Assert.assertEquals(1,creates.get());Assert.assertEquals(19,faces.get());Assert.assertEquals(1,gets.get());Assert.assertEquals(20,configs.get());Assert.assertEquals(1,owners.size());Assert.assertEquals(1,rows.values().stream().filter(p->"ISC_PERSON".equals(p.getPhase())).count());}
 @Test public void unknownOwnerBlocksOtherDevicesAndNewOperationThenLateAcceptanceResumes(){losePerson=true;SmtAuthTransportPhase a=config(100,"op");run(a);SmtAuthPersonOwner o=owners.values().iterator().next();Assert.assertEquals("UNKNOWN",o.getState());SmtAuthTransportPhase b=config(101,"op"),newOperation=config(102,"next-op");Assert.assertEquals("WAITING_PERSON",run(b).getOutcome());Assert.assertEquals("WAITING_PERSON",run(newOperation).getOutcome());Assert.assertEquals(1,creates.get());Assert.assertEquals(1,gets.get());Assert.assertEquals("PREPARED",b.getState());Assert.assertEquals("PREPARED",a.getState());service.accepted(1,"isc",Collections.singletonList(o.getOwnerPhaseId()),"person-real");Assert.assertEquals(1,run(a).getProcessed());Assert.assertEquals(1,run(b).getProcessed());Assert.assertEquals(1,faces.get());Assert.assertEquals("VERIFYING",run(newOperation).getOutcome());Assert.assertEquals(1,creates.get());}
 @Test public void changedOrgBlocksOnlyThatConsumerAndOtherParkCanReuseSameOrg(){run(config(100,"op"));SmtAuthTransportPhase bad=config(101,"op");Assert.assertEquals("VERIFYING",service.preparePersonIdentity(1,"isc",bad.getId(),"another-org").getOutcome());SmtAuthTransportPhase same=config(102,"op");same.setParkId(2);targets.get(same.getTargetId()).setParkId(2);Assert.assertEquals(1,run(same).getProcessed());Assert.assertEquals(1,creates.get());}
 @Test public void oldUnknownAndTwoOldAcceptedPersonsCannotBeTreatedAsEmptyHistory(){SmtAuthTransportPhase old=config(80,"old");old.setPhase("ISC_PERSON");old.setState("UNKNOWN");SmtAuthTransportPhase c=config(100,"op");Assert.assertEquals("WAITING_PERSON",service.preparePersonIdentity(1,"isc",100L,"org").getOutcome());Assert.assertEquals(0,creates.get());}
 @Test public void sameSubjectInAnotherInstanceHasItsOwnOwner(){service.preparePersonIdentity(1,"isc",config(100,"op").getId(),"org");SmtAuthTransportPhase c=config(101,"op");c.setInstanceId("other-isc");Assert.assertEquals("OWNER_NEEDS_LOOKUP",service.preparePersonIdentity(1,"other-isc",101L,"org").getOutcome());Assert.assertEquals(2,owners.size());}
 @Test public void twoOldAcceptedPersonsStayVisibleAndNeverSelectTheNewest(){for(int n=0;n<2;n++){SmtAuthTransportPhase old=config(80+n,"old");old.setPhase("ISC_PERSON");old.setState("ACCEPTED");old.setExternalId("different-"+n);}SmtAuthTransportPhase c=config(100,"op");Assert.assertEquals("VERIFYING",service.preparePersonIdentity(1,"isc",c.getId(),"org").getOutcome());Assert.assertEquals("LEGACY_PERSON_HISTORY_UNVERIFIED",owners.values().iterator().next().getReason());Assert.assertEquals(0,gets.get());}
 @Test public void staleOwnerTokenCannotSendOrAccept(){SmtAuthTransportPhase c=config(100,"op");PersonIdentity d=service.preparePersonIdentity(1,"isc",c.getId(),"org");SmtAuthTransportPhase asset=rows.get(d.getProofPhaseId());asset.setLeaseToken("stale");try{service.begin(1,"isc",Collections.singletonList(asset.getId()),null);Assert.fail();}catch(IllegalArgumentException expected){}Assert.assertEquals("PREPARED",owners.values().iterator().next().getState());try{service.accepted(1,"isc",Collections.singletonList(asset.getId()),"wrong-person");Assert.fail();}catch(IllegalArgumentException expected){}Assert.assertEquals("PREPARED",asset.getState());}
 @Test public void invalidPreparedOwnerLeavesDurableVerification(){SmtAuthTransportPhase c=config(100,"op");PersonIdentity d=service.preparePersonIdentity(1,"isc",c.getId(),"org");targets.get(c.getTargetId()).setLeaseToken("next-attempt");SmtAuthTransportPhase consumer=config(101,"op");Assert.assertEquals("VERIFYING",service.preparePersonIdentity(1,"isc",consumer.getId(),"org").getOutcome());Assert.assertEquals("PERSON_OWNER_INVALID",owners.values().iterator().next().getReason());Assert.assertEquals(0,creates.get());}
 @Test public void waitingPersonDoesNotConsumeBudgetOrBreakHealthyConfigBatch(){SmtAuthTransportPhase owner=config(90,"op");service.preparePersonIdentity(1,"isc",owner.getId(),"org");SmtAuthTransportPhase waiting=config(100,"op"),a=config(101,"op"),b=config(102,"op");for(SmtAuthTransportPhase p:Arrays.asList(waiting,a,b))p.setDeviceId("one-device");a.setSubjectId("healthy-a");b.setSubjectId("healthy-b");a.setPersonId("trusted-a");b.setPersonId("trusted-b");identities.put("isc:trusted-a","healthy-a");identities.put("isc:trusted-b","healthy-b");Run run=facade.submitPreparedExact(1,"isc",Arrays.asList(waiting.getId(),a.getId(),b.getId()),3);Assert.assertEquals(2,run.getProcessed());Assert.assertEquals(3,run.getHttpUsed());Assert.assertEquals(1,configs.get());Assert.assertEquals(2,faces.get());Assert.assertEquals(0,gets.get());Assert.assertEquals(0,creates.get());Assert.assertEquals("PREPARED",waiting.getState());}
 @Test public void verifiedParentMakesPreparedOwnerExplicitlyUnrecoverable(){SmtAuthTransportPhase owner=config(90,"op");service.preparePersonIdentity(1,"isc",owner.getId(),"org");owner.setState("VERIFYING");SmtAuthTransportPhase follower=config(100,"op");Assert.assertEquals("VERIFYING",service.preparePersonIdentity(1,"isc",follower.getId(),"org").getOutcome());Assert.assertEquals("PERSON_OWNER_INVALID",owners.values().iterator().next().getReason());}
 @Test public void concurrentConfigurationVerificationDoesNotAbortHealthyBatch(){SmtAuthTransportPhase bad=config(100,"op"),a=config(101,"op"),b=config(102,"op");for(SmtAuthTransportPhase p:Arrays.asList(bad,a,b))p.setDeviceId("one-device");a.setSubjectId("healthy-a");b.setSubjectId("healthy-b");a.setPersonId("trusted-a");b.setPersonId("trusted-b");identities.put("isc:trusted-a","healthy-a");identities.put("isc:trusted-b","healthy-b");beforeEmptyPeople=()->service.block(1,"isc",bad.getId(),"ISC_IDENTITY_UNPROVEN");Run result=facade.submitPreparedExact(1,"isc",Arrays.asList(bad.getId(),a.getId(),b.getId()),4);Assert.assertEquals(2,result.getProcessed());Assert.assertEquals(1,configs.get());Assert.assertEquals(2,faces.get());Assert.assertEquals(0,creates.get());Assert.assertEquals(1,gets.get());Assert.assertEquals("VERIFYING",bad.getState());Assert.assertEquals("VERIFYING",owners.values().iterator().next().getState());}
 @Test public void configurationVerificationCommitsAfterPrepareAssetTransactionRollsBack(){
  MemoryTransactions tx=new MemoryTransactions();org.springframework.aop.framework.ProxyFactory proxy=new org.springframework.aop.framework.ProxyFactory(service);proxy.setProxyTargetClass(true);proxy.addAdvice(new org.springframework.transaction.interceptor.TransactionInterceptor(tx,new org.springframework.transaction.annotation.AnnotationTransactionAttributeSource()));service=(AuthOperationTransportService)proxy.getProxy();org.springframework.test.util.ReflectionTestUtils.setField(facade,"transport",service);
  SmtAuthTransportPhase bad=config(100,"op"),healthy=config(101,"op");bad.setDeviceId("one-device");healthy.setDeviceId("one-device");healthy.setSubjectId("healthy");healthy.setPersonId("trusted");identities.put("isc:trusted","healthy");
  beforeEmptyPeople=()->{Long asset=owners.values().iterator().next().getOwnerPhaseId();service.rejectPrepared(1,"isc",asset,"ISC_IDENTITY_CONFLICT");Assert.assertEquals("PREPARED",bad.getState());};
  Run result=facade.submitPreparedExact(1,"isc",Arrays.asList(bad.getId(),healthy.getId()),3);Assert.assertEquals(1,tx.rollbacks);Assert.assertEquals("PREPARED",tx.rolledBackStates.get(bad.getId()));Assert.assertEquals("VERIFYING",bad.getState());Assert.assertEquals("ISC_IDENTITY_CONFLICT",bad.getErrorCode());Assert.assertEquals(1,result.getProcessed());Assert.assertEquals(1,configs.get());Assert.assertEquals(0,creates.get());
 }
 /** 受控持久层事务快照：保留Spring真实拦截/rollback/后续REQUIRES_NEW边界，不代替Oracle锁证据。 */
 private class MemoryTransactions extends org.springframework.transaction.support.AbstractPlatformTransactionManager {
  int rollbacks;Map<Long,String> rolledBackStates=new HashMap<>();
  protected Object doGetTransaction(){return new StoreSnapshot();}
  protected void doBegin(Object raw,org.springframework.transaction.TransactionDefinition definition){StoreSnapshot snapshot=(StoreSnapshot)raw;for(SmtAuthTransportPhase p:rows.values()){SmtAuthTransportPhase copy=new SmtAuthTransportPhase();org.springframework.beans.BeanUtils.copyProperties(p,copy);snapshot.phases.put(p.getId(),copy);}for(SmtAuthPersonOwner o:owners.values()){SmtAuthPersonOwner copy=new SmtAuthPersonOwner();org.springframework.beans.BeanUtils.copyProperties(o,copy);snapshot.owners.put(o.getId(),copy);}snapshot.identities.putAll(identities);}
  protected void doCommit(org.springframework.transaction.support.DefaultTransactionStatus status){}
  protected void doRollback(org.springframework.transaction.support.DefaultTransactionStatus status){StoreSnapshot snapshot=(StoreSnapshot)status.getTransaction();rollbacks++;rows.keySet().retainAll(snapshot.phases.keySet());for(SmtAuthTransportPhase p:snapshot.phases.values()){org.springframework.beans.BeanUtils.copyProperties(p,rows.get(p.getId()));rolledBackStates.put(p.getId(),p.getState());}owners.keySet().retainAll(snapshot.owners.keySet());for(SmtAuthPersonOwner o:snapshot.owners.values())org.springframework.beans.BeanUtils.copyProperties(o,owners.get(o.getId()));identities.clear();identities.putAll(snapshot.identities);}
 }
 private static class StoreSnapshot {Map<Long,SmtAuthTransportPhase> phases=new HashMap<>();Map<String,SmtAuthPersonOwner> owners=new HashMap<>();Map<String,String> identities=new HashMap<>();}
 private Run run(SmtAuthTransportPhase p){return facade.submitPreparedExact(p.getParkId(),p.getInstanceId(),Collections.singletonList(p.getId()),3);}
 private SmtAuthTransportPhase config(long id,String operation){SmtAuthTransportPhase p=new SmtAuthTransportPhase();p.setId(id);p.setTargetId(id);p.setAttemptId(id+1000);p.setParkId(1);p.setInstanceId("isc");p.setDeviceId("device-"+id);p.setPhase("ISC_CONFIG");p.setAccessType("ISC");p.setState("PREPARED");p.setAction("ADD");p.setSubjectType("STAFF");p.setSubjectId("staff");p.setBadge("badge");p.setImageId("image");p.setPersonSnapshot("{\"personName\":\"冻结员工\",\"gender\":1}");p.setResourceId("resource-"+id);p.setResourceGeneration(1L);p.setLeaseToken("token-"+id);p.setTaskId("task-"+id);rows.put(id,p);SmtAuthOperationTarget t=new SmtAuthOperationTarget();t.setId(id);t.setParkId(1);t.setLeaseToken(p.getLeaseToken());t.setOperationVersion(1L);t.setState("EXECUTING");targets.put(id,t);SmtAuthOperationAttempt a=new SmtAuthOperationAttempt();a.setId(p.getAttemptId());a.setTaskId(p.getTaskId());a.setTargetId(id);a.setLeaseToken(p.getLeaseToken());a.setStatus("SUBMITTING");attempts.put(a.getId(),a);SmtAuthSelectionSource source=new SmtAuthSelectionSource();source.setSubjectId("staff");source.setOperationKey(operation);sources.put(id,Collections.singletonList(source));return p;}
}
