package com.tce.smart.platform.core.service.impl;
import com.tce.smart.platform.core.dto.authselection.AuthSelection.*;
import com.tce.smart.platform.core.entity.*;
import com.tce.smart.platform.core.mapper.AuthOperationDirectClaimMapper;
import org.junit.*;
import java.util.*;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.transaction.annotation.AnnotationTransactionAttributeSource;
import org.springframework.transaction.interceptor.TransactionInterceptor;
import org.springframework.transaction.support.*;
/** 独立组件的冻结读取、归属冲突及实际 Spring 事务边界反例。 */
public class AuthDirectClaimFoundationTest {
 static Map<Long,SmtAuthTransportPhase> stored=new HashMap<>();
 @Before public void resetProofs(){stored.clear();}
 @Test public void multilinePlateNeverCreatesAnyPermanentClaim(){
  for(String plate:Arrays.asList("粤B1\n2\n345","粤B1\r\n2\r\n345","粤B12\t345","粤b12345")){
   Memory m=new Memory();Tx tx=new Tx(m);AuthOperationDirectClaimService service=proxy(new AuthOperationDirectClaimService(m),tx);SmtAuthTransportPhase p=vehicle(1,"71",plate);String reason=null;
   try{new TransactionTemplate(tx).execute(x->{service.claim(Collections.singletonList(p));return null;});}catch(IllegalArgumentException expected){reason=expected.getMessage();}
   Assert.assertEquals("非法车牌不得创建任一永久键",0,m.rows.size());Assert.assertEquals("DIRECT_PLATE_FORMAT_UNVERIFIED",reason);
  }
 }
 @Test public void realEmployeeFreezeShapeReadsExplicitStaffZeroWithoutMutation(){
  SmtAuthTransportPhase p=staffPhase();SmtAuthSelectionSource s=staffSource();SmtAuthSelectionResource r=staffResource();
  SmtAuthTransportPhase frozen=AuthTransportCredentials.freeze(p,Collections.singletonList(binding(1)),Collections.singletonList(s),Collections.singletonList(r));
  PersonCredential c=(PersonCredential)AuthTransportCredentials.fromPhase(frozen);Assert.assertEquals("71",c.getTaskCardNo());Assert.assertEquals(Integer.valueOf(1),c.getTaskServiceType());Assert.assertEquals("1",c.getCardType());Assert.assertEquals("frozen-badge",c.getBadge());Assert.assertEquals("frozen-image",c.getImageId());Assert.assertEquals(s.getPersonSnapshot(),frozen.getPersonSnapshot());Assert.assertNull(frozen.getCredentialVersion());Assert.assertNull(frozen.getCredentialSnapshot());Assert.assertEquals(Integer.valueOf(0),s.getSnapshotVersion());Assert.assertEquals(Integer.valueOf(0),r.getCredentialVersion());Assert.assertNull(p.getBadge());Assert.assertNull(p.getImageId());
 }
 @Test public void completelyAbsentLegacyStaffFieldsKeepTheirOriginalReadPath(){
  SmtAuthSelectionSource s=staffSource();s.setSourceKind(null);s.setSubjectType(null);s.setSnapshotVersion(null);s.setBusinessSnapshot(null);SmtAuthSelectionResource r=staffResource();r.setSubjectType(null);r.setCredentialVersion(null);
  Assert.assertEquals("frozen-badge",AuthTransportCredentials.freeze(staffPhase(),Collections.singletonList(binding(1)),Collections.singletonList(s),Collections.singletonList(r)).getBadge());
 }
 @Test public void explicitStaffZeroOnlyAcceptsItsCompleteWhitelistedPair(){
  for(String variant:Arrays.asList("source-version-null","source-version-2","source-kind-null","source-kind-visitor","source-family-visitor","source-parent","resource-version-null","resource-version-2","resource-family-null","resource-family-visitor","resource-snapshot","resource-typed","legacy-source-explicit-resource","explicit-source-legacy-resource")){
   SmtAuthSelectionSource s=staffSource();SmtAuthSelectionResource r=staffResource();
   if(variant.equals("source-version-null"))s.setSnapshotVersion(null);if(variant.equals("source-version-2"))s.setSnapshotVersion(2);if(variant.equals("source-kind-null"))s.setSourceKind(null);if(variant.equals("source-kind-visitor"))s.setSourceKind("VISITOR");if(variant.equals("source-family-visitor"))s.setSubjectType("VISITOR");if(variant.equals("source-parent"))s.setParentKind("VISITOR");
   if(variant.equals("resource-version-null"))r.setCredentialVersion(null);if(variant.equals("resource-version-2"))r.setCredentialVersion(2);if(variant.equals("resource-family-null"))r.setSubjectType(null);if(variant.equals("resource-family-visitor"))r.setSubjectType("VISITOR");if(variant.equals("resource-snapshot"))r.setCredentialSnapshot("{}");if(variant.equals("resource-typed")){r.setCredentialVersion(1);PersonCredential c=person("71");c.setTaskServiceType(1);c.setCardType("1");r.setCredentialSnapshot(AuthSelectionSnapshots.credential(c));}
   if(variant.equals("legacy-source-explicit-resource")){s.setSourceKind(null);s.setSubjectType(null);s.setSnapshotVersion(null);s.setBusinessSnapshot(null);}if(variant.equals("explicit-source-legacy-resource")){r.setSubjectType(null);r.setCredentialVersion(null);}
   try{AuthTransportCredentials.freeze(staffPhase(),Collections.singletonList(binding(1)),Collections.singletonList(s),Collections.singletonList(r));Assert.fail("不完整白名单不得降级: "+variant);}catch(IllegalArgumentException expected){}
  }
 }
 // 固定复现 EmployeeAuthOperationService.freeze 的员工字段：来源和资源显式为0，历史格式独立。
 static SmtAuthTransportPhase staffPhase(){SmtAuthTransportPhase p=phase(1);p.setSubjectType("STAFF");p.setServiceType("1");p.setCredentialVersion(null);p.setCredentialSnapshot(null);return p;}
 static SmtAuthSelectionSource staffSource(){SmtAuthSelectionSource s=source(1);s.setSourceKind("STAFF_AUTH");s.setSubjectType("STAFF");s.setSnapshotVersion(0);s.setBadge("frozen-badge");s.setImageId("frozen-image");s.setPersonSnapshot("{\"personName\":\"冻结员工\",\"gender\":1}");s.setBusinessSnapshot("{\"format\":\"EMPLOYEE_HISTORY_EVIDENCE_V1\",\"rows\":[]}");return s;}
 static SmtAuthSelectionResource staffResource(){SmtAuthSelectionResource r=resource(1);r.setSubjectType("STAFF");r.setCredentialVersion(0);r.setCredentialSnapshot(null);r.setServiceType("1");r.setParticipation("INCLUDE");return r;}
 @Test public void phaseMapperBindsTypedSnapshotAsClob() throws Exception {org.apache.ibatis.session.Configuration cfg=new org.apache.ibatis.session.Configuration();for(String file:Arrays.asList("AuthOperationTransportMapper.xml","AuthOperationDirectClaimMapper.xml")){try(java.io.InputStream in=getClass().getResourceAsStream("/mapper/"+file)){Assert.assertNotNull(in);new org.apache.ibatis.builder.xml.XMLMapperBuilder(in,cfg,file,cfg.getSqlFragments()).parse();}}org.apache.ibatis.mapping.BoundSql sql=cfg.getMappedStatement("com.tce.smart.platform.core.mapper.AuthOperationTransportMapper.insert").getBoundSql(phase(1));Assert.assertTrue(sql.getParameterMappings().stream().anyMatch(x->"credentialSnapshot".equals(x.getProperty())&&x.getJdbcType()==org.apache.ibatis.type.JdbcType.CLOB));Assert.assertTrue(cfg.hasStatement("com.tce.smart.platform.core.mapper.AuthOperationDirectClaimMapper.lock"));}
 @Test public void emptyWindowsUseExistingPhaseZeroConvention(){SmtAuthTransportPhase p=phase(1);p.setStartTime(0L);p.setOverTime(0L);Assert.assertNotNull(AuthTransportCredentials.freeze(p,Collections.singletonList(binding(1)),Collections.singletonList(source(1)),Collections.singletonList(resource(1))));}
 @Test public void vehicleFamilyCannotInventAServiceType(){SmtAuthTransportPhase p=vehicle(1,"71","粤B12345");VehicleCredential v=(VehicleCredential)AuthSelectionSnapshots.credential(1,p.getCredentialSnapshot());v.setTaskServiceType(99);p.setServiceType("99");p.setCredentialSnapshot(AuthSelectionSnapshots.credential(v));reject(()->AuthTransportCredentials.fromPhase(p));}
 @Test public void frozenResourceWindowMustMatchPhaseWindow(){SmtAuthTransportPhase p=phase(1);p.setStartTime(100L);SmtAuthSelectionResource r=resource(1);r.setValidFrom(java.time.LocalDateTime.ofEpochSecond(200,0,java.time.ZoneOffset.UTC));reject(()->AuthTransportCredentials.freeze(p,Collections.singletonList(binding(1)),Collections.singletonList(source(1)),Collections.singletonList(r)));}
 @Test public void suppliedPhaseCannotForgeStoredIdentityOrUseMissingProof(){Memory m=new Memory();Tx tx=new Tx(m);AuthOperationDirectClaimService service=proxy(new AuthOperationDirectClaimService(m),tx);SmtAuthTransportPhase p=phase(1),other=new SmtAuthTransportPhase();org.springframework.beans.BeanUtils.copyProperties(p,other);other.setSubjectId("forged");stored.put(1L,other);reject(()->new TransactionTemplate(tx).execute(x->{service.claim(Collections.singletonList(p));return null;}));stored.clear();reject(()->new TransactionTemplate(tx).execute(x->{service.claim(Collections.singletonList(p));return null;}));Assert.assertTrue(m.rows.isEmpty());}

 @Test public void oldStaffProjectionReadsWithoutChangingItsIdentity(){SmtAuthTransportPhase p=phase(1);p.setCredentialVersion(null);p.setCredentialSnapshot(null);p.setSubjectType("STAFF");p.setServiceType("7");PersonCredential c=(PersonCredential)AuthTransportCredentials.fromPhase(p);Assert.assertNotNull(c);Assert.assertEquals("71",c.getTaskCardNo());Assert.assertEquals(Integer.valueOf(7),c.getTaskServiceType());Assert.assertEquals("1",c.getCardType());}
 @Test public void explicitVersionNeverFallsBackToStaff(){SmtAuthTransportPhase p=phase(1);p.setCredentialVersion(2);reject(()->AuthTransportCredentials.fromPhase(p));p.setCredentialVersion(null);reject(()->AuthTransportCredentials.fromPhase(p));p.setCredentialSnapshot(null);p.setSubjectType("VISITOR");reject(()->AuthTransportCredentials.fromPhase(p));}
 @Test public void typedVehicleKeepsRealLongCardAndRequiresFrozenCardType(){SmtAuthTransportPhase p=vehicle(1,"8123456789012345678","粤B12345");VehicleCredential c=(VehicleCredential)AuthTransportCredentials.fromPhase(p);Assert.assertNotNull(c);Assert.assertEquals("8123456789012345678",c.getTaskCardNo());Assert.assertEquals("0",c.getCardType());p.setCredentialSnapshot(p.getCredentialSnapshot().replace("\"cardType\":\"0\"","\"cardType\":null"));reject(()->AuthTransportCredentials.fromPhase(p));}
 @Test public void mismatchedWireFieldsAndUtf8WidthsAreNotSilentlyTruncated(){SmtAuthTransportPhase p=phase(1);p.setCardNo("72");final SmtAuthTransportPhase first=p;reject(()->AuthTransportCredentials.fromPhase(first));p=phase(1);p.setServiceType("6");final SmtAuthTransportPhase q=p;reject(()->AuthTransportCredentials.fromPhase(q));PersonCredential c=person("71");c.setImageId(String.join("",Collections.nCopies(50,"图")));p=phase(1);p.setCredentialSnapshot(AuthSelectionSnapshots.credential(c));final SmtAuthTransportPhase z=p;reject(()->AuthTransportCredentials.fromPhase(z));}
 @Test public void everySharedSourceMustMatchExactBindingAndCredential(){SmtAuthTransportPhase p=phase(1);List<SmtAuthSourceResource> bs=Arrays.asList(binding(1),binding(2));List<SmtAuthSelectionSource> ss=Arrays.asList(source(1),source(2));List<SmtAuthSelectionResource> rs=Arrays.asList(resource(1),resource(2));SmtAuthTransportPhase frozen=AuthTransportCredentials.freeze(p,bs,ss,rs);Assert.assertNotNull(frozen);Assert.assertEquals(Integer.valueOf(1),frozen.getCredentialVersion());ss.get(1).setFingerprint("different");reject(()->AuthTransportCredentials.freeze(p,bs,ss,rs));ss.get(1).setFingerprint("fp2");PersonCredential other=person("72");rs.get(1).setCredentialSnapshot(AuthSelectionSnapshots.credential(other));reject(()->AuthTransportCredentials.freeze(p,bs,ss,rs));}
 @Test public void missingOrExtraSourceAndWrongResourceCannotBeIgnored(){SmtAuthTransportPhase p=phase(1);List<SmtAuthSourceResource> bs=Arrays.asList(binding(1),binding(2));reject(()->AuthTransportCredentials.freeze(p,bs,Collections.singletonList(source(1)),Collections.singletonList(resource(1))));SmtAuthSelectionResource wrong=resource(1);wrong.setDeviceId("another-device");reject(()->AuthTransportCredentials.freeze(p,Collections.singletonList(binding(1)),Collections.singletonList(source(1)),Collections.singletonList(wrong)));}
 @Test public void claimNeedsCallerTransactionAndRollsBackItsFirstKey(){Memory m=new Memory();Tx tx=new Tx(m);AuthOperationDirectClaimService s=proxy(new AuthOperationDirectClaimService(m),tx);try{s.claim(Collections.singletonList(phase(1)));Assert.fail("缺事务必须拒绝");}catch(org.springframework.transaction.IllegalTransactionStateException expected){}TransactionTemplate t=new TransactionTemplate(tx);t.execute(x->{s.claim(Collections.singletonList(vehicle(1,"71","粤B12345")));return null;});Assert.assertEquals(2,m.rows.size());try{t.execute(x->{s.claim(Collections.singletonList(vehicle(2,"72","粤B12345")));return null;});Assert.fail("二键冲突必须整体回滚");}catch(IllegalArgumentException expected){}Assert.assertEquals(2,m.rows.size());}
 @Test public void sameOwnerIsIdempotentButFamilyResourceWireAndRouteCannotTakeOver(){Memory m=new Memory();Tx tx=new Tx(m);AuthOperationDirectClaimService s=proxy(new AuthOperationDirectClaimService(m),tx);TransactionTemplate t=new TransactionTemplate(tx);SmtAuthTransportPhase p=phase(1);t.execute(x->{s.claim(Collections.singletonList(p));s.claim(Collections.singletonList(p));return null;});Assert.assertEquals(1,m.rows.size());for(String field:Arrays.asList("family","resource","park","instance")){SmtAuthTransportPhase other=phase(2);if(field.equals("family"))other.setSubjectType("VISITOR_FELLOW");if(field.equals("resource"))other.setResourceId("r2");if(field.equals("park"))other.setParkId(2);if(field.equals("instance"))other.setInstanceId("new-route");reject(()->t.execute(x->{s.claim(Collections.singletonList(other));return null;}));}Assert.assertEquals(1,m.rows.size());}
 @Test public void allKeysAcrossTheBatchAreLockedInOneStableOrder(){Memory m=new Memory();Tx tx=new Tx(m);AuthOperationDirectClaimService s=proxy(new AuthOperationDirectClaimService(m),tx);TransactionTemplate t=new TransactionTemplate(tx);t.execute(x->{s.claim(Arrays.asList(vehicle(1,"91","粤B99999"),vehicle(2,"71","粤B12345")));return null;});Assert.assertEquals(4,m.rows.size());List<String> expected=new ArrayList<>(m.order);Collections.sort(expected);Assert.assertEquals(expected,m.order);}
 @Test public void independentDevicesAndDifferentCardsOfOneSubjectDoNotShareNaturalKey(){Memory m=new Memory();Tx tx=new Tx(m);AuthOperationDirectClaimService s=proxy(new AuthOperationDirectClaimService(m),tx);SmtAuthTransportPhase a=phase(1),b=phase(2),c=phase(3);b.setDeviceId("other");c.setCardNo("72");c.setCredentialSnapshot(AuthSelectionSnapshots.credential(person("72")));new TransactionTemplate(tx).execute(x->{s.claim(Arrays.asList(a,b,c));return null;});Assert.assertEquals(3,m.rows.size());}
 public static SmtAuthTransportPhase phase(long id){SmtAuthTransportPhase p=new SmtAuthTransportPhase();p.setId(id);p.setTargetId(id);p.setAttemptId(id);p.setParkId(1);p.setInstanceId("direct");p.setAccessType("DIRECT");p.setPhase("DIRECT_SEND");p.setState("PREPARED");p.setDeviceId("device");p.setSubjectType("VISITOR");p.setSubjectId("71");p.setResourceId("r");p.setResourceGeneration(1L);p.setResourceType("PERSON");p.setCredentialChannel("FACE");p.setServiceType("3");p.setAction("ADD");p.setCardNo("71");p.setTaskId("101");p.setCredentialVersion(1);p.setCredentialSnapshot(AuthSelectionSnapshots.credential(person("71")));stored.put(id,p);return p;}
 public static PersonCredential person(String card){PersonCredential c=new PersonCredential();c.setTaskCardNo(card);c.setTaskDeviceType(1);c.setTaskServiceType(3);c.setCardType("7");c.setName("来访者");c.setImageId("image");return c;}
 public static SmtAuthTransportPhase vehicle(long id,String card,String plate){SmtAuthTransportPhase p=phase(id);p.setSubjectType("VISITOR_VEHICLE");p.setResourceType("VEHICLE");p.setCredentialChannel("PLATE");p.setServiceType("4");p.setCardNo(card);VehicleCredential c=new VehicleCredential();c.setTaskCardNo(card);c.setTaskDeviceType(2);c.setTaskServiceType(4);c.setCardType("0");c.setPlate(plate);p.setCredentialSnapshot(AuthSelectionSnapshots.credential(c));return p;}
 static SmtAuthSourceResource binding(long n){SmtAuthSourceResource b=new SmtAuthSourceResource();b.setSourceCoordId("s"+n);b.setSourceGeneration(1L);b.setSourceRowId("row"+n);b.setSourceFingerprint("fp"+n);b.setResourceCoordId("r");b.setResourceGeneration(1L);b.setTargetId(1L);return b;}
 static SmtAuthSelectionSource source(long n){SmtAuthSelectionSource s=new SmtAuthSelectionSource();s.setBatchId(1L);s.setOrdinal(n);s.setSourceCoordId("s"+n);s.setSourceGeneration(1L);s.setSourceRowId("row"+n);s.setFingerprint("fp"+n);s.setParkId(1);s.setSubjectType("VISITOR");s.setSubjectId("71");s.setSourceKind("VISITOR");s.setSnapshotVersion(1);return s;}
 static SmtAuthSelectionResource resource(long n){SmtAuthSelectionResource r=new SmtAuthSelectionResource();r.setBatchId(1L);r.setOrdinal(n);r.setSourceOrdinal(n);r.setParkId(1);r.setSubjectType("VISITOR");r.setSubjectId("71");r.setAccessType("DIRECT");r.setDeviceId("device");r.setResourceCoordId("r");r.setResourceType("PERSON");r.setServiceType("3");r.setCredentialChannel("FACE");r.setCredentialVersion(1);r.setCredentialSnapshot(AuthSelectionSnapshots.credential(person("71")));return r;}
 static void reject(Runnable f){try{f.run();Assert.fail("缺少精确证据必须拒绝");}catch(IllegalArgumentException expected){}}
 static class Memory implements AuthOperationDirectClaimMapper {Map<String,SmtAuthDirectClaim> rows=new HashMap<>();List<String> order=new ArrayList<>();public SmtAuthTransportPhase phase(Long id){return stored.get(id);}public SmtAuthDirectClaim lock(String id){order.add(id);return rows.get(id);}public int insert(SmtAuthDirectClaim row){if(rows.containsKey(row.getId()))throw new org.springframework.dao.DuplicateKeyException("竞争");rows.put(row.getId(),row);return 1;}}
 static class Tx extends AbstractPlatformTransactionManager {final Memory m;boolean active;Map<String,SmtAuthDirectClaim> before;Tx(Memory m){this.m=m;}protected Object doGetTransaction(){return this;}protected boolean isExistingTransaction(Object o){return active;}protected void doBegin(Object o,org.springframework.transaction.TransactionDefinition d){active=true;before=new HashMap<>(m.rows);}protected void doCommit(DefaultTransactionStatus s){active=false;}protected void doRollback(DefaultTransactionStatus s){m.rows=before;active=false;}protected void doSetRollbackOnly(DefaultTransactionStatus s){} }
 static AuthOperationDirectClaimService proxy(AuthOperationDirectClaimService raw,Tx tx){ProxyFactory p=new ProxyFactory(raw);p.setProxyTargetClass(true);p.addAdvice(new TransactionInterceptor(tx,new AnnotationTransactionAttributeSource()));return (AuthOperationDirectClaimService)p.getProxy();}
}
