package com.tce.smart.platform.core.service.impl;
import com.tce.smart.platform.core.dto.authselection.*;
import com.tce.smart.platform.core.dto.authselection.AuthSelection.*;
import com.tce.smart.platform.core.dto.authselection.VisitorAuthSnapshot.*;
import com.tce.smart.platform.core.entity.*;
import com.tce.smart.platform.core.mapper.VisitorAuthOperationMapper;
import org.junit.*;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import java.util.*;
import com.tce.smart.platform.core.dto.authversion.AuthVersion.Window;
import java.time.*;
/** 离线行为测试只替换数据库读取；真实行锁与SQL留给独立Oracle候选。 */
public class VisitorAuthSourceHandlerTest {
 private VisitorAuthOperationMapper mapper; private VisitorAuthSourceHandler handler; private SmtVisitor live; private VisitorAuthSnapshot business; private SmtAuthSelectionSource row;
 @Before public void setup(){
  mapper=mock(VisitorAuthOperationMapper.class);handler=new VisitorAuthSourceHandler(mapper);
  live=new SmtVisitor();live.setId(910000000000000001L);live.setParkId(42);live.setCreateTime(java.sql.Timestamp.valueOf("2009-02-13 23:31:30.123"));live.setStartTime(java.sql.Timestamp.valueOf("2025-01-01 00:00:00.123"));live.setEndTime(java.sql.Timestamp.valueOf("2099-01-01 00:00:00.456"));live.setCause(1);live.setCertType(0);live.setCertNo("cert-main");live.setVisitorName("合成访客");live.setVisitorPhotoId("photo-main");live.setIsVehicle(1);live.setVehiclePlate("合成车牌");live.setStatus(0);live.setDelFlag(0);
  business=new VisitorAuthSnapshot();ParentFacts p=new ParentFacts();p.setId(live.getId());p.setParkId(42);p.setCreateTime("2009-02-13T23:31:30.123");p.setStartTime("2025-01-01T00:00:00.123");p.setEndTime("2099-01-01T00:00:00.456");p.setCause(1);p.setCertType(0);p.setCertNo("cert-main");p.setVisitorName("合成访客");p.setVisitorPhotoId("photo-main");p.setIsVehicle(1);p.setVehiclePlate("合成车牌");business.setParent(p);
  Evidence e=new Evidence();e.setTrigger(Trigger.APPROVAL);e.setApprovalBasis(ApprovalBasis.DATABASE_PARENT_STATUS_ZERO);e.setRawStatus(0);e.setRawDelFlag(0);e.setLeadHours(2);business.setEvidence(e);
  row=new SmtAuthSelectionSource();row.setBatchId(77L);row.setOrdinal(1L);row.setParkId(42);row.setSourceKind("VISITOR");row.setSubjectType("VISITOR");row.setSnapshotVersion(1);row.setSubjectId("910000000000000001");row.setSourceRowId(row.getSubjectId());row.setStableKey("18:910000000000000001");row.setParentKind("VISITOR");row.setParentRowId(row.getSubjectId());row.setDesiredAction("ADD");row.setFingerprint("frozen-fingerprint");row.setState("PENDING");persist();
  when(mapper.lockParent(42,live.getId())).thenReturn(live);
 }
 private void persist(){row.setBusinessSnapshot(AuthSelectionSnapshots.business(business,Collections.emptyList()));SmtAuthSelectionSource stored=new SmtAuthSelectionSource();org.springframework.beans.BeanUtils.copyProperties(row,stored);when(mapper.frozenSource(77L,1L)).thenReturn(stored);}
 private SourceSelection<VisitorAuthSnapshot> selection(){return SourceSelection.<VisitorAuthSnapshot>builder().parkId(42).sourceKind(SourceKind.VISITOR).subjectType(SubjectType.VISITOR).subjectId(row.getSubjectId()).sourceRowId(row.getSourceRowId()).stableKey(row.getStableKey()).parentKind("VISITOR").parentRowId(row.getParentRowId()).snapshotVersion(1).action("ADD").business(business).window(Window.builder().from(LocalDateTime.of(2024,12,31,22,0,0,123000000)).to(LocalDateTime.of(2099,1,1,0,0,0,456000000)).build()).build();}
 @Test public void parentFactsCannotAuthorizeAWiderSelectionWindow(){SourceSelection<VisitorAuthSnapshot> s=SourceSelection.<VisitorAuthSnapshot>builder().parkId(42).sourceKind(SourceKind.VISITOR).subjectType(SubjectType.VISITOR).subjectId(row.getSubjectId()).sourceRowId(row.getSourceRowId()).stableKey(row.getStableKey()).parentKind("VISITOR").parentRowId(row.getParentRowId()).snapshotVersion(1).action("ADD").business(business).window(Window.builder().from(LocalDateTime.of(2000,1,1,0,0)).to(LocalDateTime.of(2099,1,1,0,0,0,456000000)).build()).build();try{handler.lockAndValidate(s);fail("不能借正确父事实扩大权限期");}catch(IllegalArgumentException expected){}}
 @Test public void actualApprovedParentCanBeAccepted(){handler.lockAndValidate(selection());}
 @Test public void trustedPhysicalResultSurvivesNormalArrivalAndDeparture(){live.setStatus(3);assertTrue(handler.applyExact(row,business));live.setStatus(5);live.setDelFlag(1);assertTrue(handler.applyExact(row,business));assertEquals(Integer.valueOf(5),live.getStatus());assertEquals(Integer.valueOf(1),live.getDelFlag());}
 @Test public void oracleMicrosecondChangeCannotSettle(){java.sql.Timestamp precise=new java.sql.Timestamp(4070908800456L);precise.setNanos(456001000);live.setEndTime(precise);assertFalse(handler.applyExact(row,business));}
 @Test public void changedWindowByOneMillisecondCannotSettle(){live.setEndTime(java.sql.Timestamp.valueOf("2099-01-01 00:00:00.457"));assertFalse(handler.applyExact(row,business));}
 @Test public void sameWindowReapplicationCannotSettle(){live.setStatus(2);assertFalse(handler.applyExact(row,business));}
 @Test public void noInventedSuccessorLetsRejectedOrExpiredAddSettle(){for(int status:new int[]{1,4,6}){live.setStatus(status);assertFalse(handler.applyExact(row,business));}}
 @Test public void fabricatedApprovalCannotBeAcceptedFromPendingParent(){live.setStatus(2);try{handler.lockAndValidate(selection());fail("必须核真实父批准");}catch(IllegalArgumentException expected){}}
 @Test public void fabricatedBusinessDoesNotReplacePersistedSnapshot(){business.getParent().setCertNo("forged");live.setCertNo("forged");assertFalse(handler.applyExact(row,business));}
 @Test public void missingPersistedSourceCannotSettle(){when(mapper.frozenSource(77L,1L)).thenReturn(null);assertFalse(handler.applyExact(row,business));}
 @Test public void vehicleHandlerCannotSettlePersonSource(){assertFalse(new VisitorVehicleAuthSourceHandler(mapper).applyExact(row,business));}
 @Test public void changedIdentityAndParentCannotSettle(){live.setCertNo("changed");assertFalse(handler.applyExact(row,business));live.setCertNo("cert-main");live.setParkId(43);assertFalse(handler.applyExact(row,business));}
 @Test public void nullFieldsCompareWithoutInventingDefaults(){assertTrue(handler.applyExact(row,business));live.setProcessId("another-process");assertFalse(handler.applyExact(row,business));}
 @Test public void mainFaceExitIsNotARemovalTrigger(){business.getEvidence().setTrigger(Trigger.FELLOW_EXIT);business.getEvidence().setApprovalBasis(ApprovalBasis.NOT_APPLICABLE);business.getEvidence().setEventId(8L);row.setDesiredAction("DELETE");persist();assertFalse(handler.applyExact(row,business));}

 private void fellow(){FellowFacts f=new FellowFacts();f.setId(910000000000000002L);f.setVisitorId(live.getId());f.setCertType(0);f.setCertNo("cert-fellow");f.setFellowName("合成随行");f.setFellowPhotoId("photo-fellow");business.setFellow(f);SmtFellowVisitor child=new SmtFellowVisitor();org.springframework.beans.BeanUtils.copyProperties(f,child);when(mapper.lockFellow(live.getId(),f.getId())).thenReturn(child);row.setSourceKind("VISITOR_FELLOW");row.setSubjectType("VISITOR_FELLOW");row.setSubjectId(f.getId().toString());row.setSourceRowId(row.getSubjectId());row.setStableKey("18:91000000000000000118:910000000000000002");persist();}
 private void vehicle(){row.setSourceKind("VISITOR_VEHICLE");row.setSubjectType("VISITOR_VEHICLE");persist();}
 private void deletion(Trigger trigger){row.setDesiredAction("DELETE");business.getEvidence().setTrigger(trigger);business.getEvidence().setApprovalBasis(ApprovalBasis.NOT_APPLICABLE);business.getEvidence().setEventId(trigger==Trigger.EXPIRY?null:8L);persist();}
 @Test public void fellowUsesOwnIdentityAndRequiresLiveParentRelationship(){fellow();VisitorFellowAuthSourceHandler h=new VisitorFellowAuthSourceHandler(mapper);assertTrue(h.applyExact(row,business));when(mapper.lockFellow(live.getId(),910000000000000002L)).thenReturn(null);assertFalse(h.applyExact(row,business));}
 @Test public void vehicleIsIndependentAndCannotReuseChangedPlate(){vehicle();VisitorVehicleAuthSourceHandler h=new VisitorVehicleAuthSourceHandler(mapper);assertTrue(h.applyExact(row,business));live.setVehiclePlate("新车牌");assertFalse(h.applyExact(row,business));}
 @Test public void familyRegistryDispatchesAllThreeKindsWithoutEmployeeFallback(){AuthSourceConvergenceRegistry r=new AuthSourceConvergenceRegistry(Arrays.asList(handler,new VisitorFellowAuthSourceHandler(mapper),new VisitorVehicleAuthSourceHandler(mapper)));assertTrue(r.apply(row));vehicle();assertTrue(r.apply(row));fellow();assertTrue(r.apply(row));row.setSubjectType("STAFF");assertFalse(r.apply(row));}
 @Test public void expiryDeleteKeepsParentAndFellowHistory(){live.setEndTime(java.sql.Timestamp.valueOf("2025-01-02 00:00:00.456"));business.getParent().setEndTime("2025-01-02T00:00:00.456");deletion(Trigger.EXPIRY);assertTrue(handler.applyExact(row,business));assertEquals(Long.valueOf(910000000000000001L),live.getId());assertEquals(Integer.valueOf(0),live.getStatus());fellow();deletion(Trigger.EXPIRY);assertTrue(new VisitorFellowAuthSourceHandler(mapper).applyExact(row,business));}
 @Test public void futureExpiryDoesNotAuthorizeDeletion(){deletion(Trigger.EXPIRY);assertFalse(handler.applyExact(row,business));}
 @Test public void vehicleExitRequiresActualEvidenceAndOnlyParentVehicleScope(){deletion(Trigger.VEHICLE_EXIT);assertFalse(handler.applyExact(row,business));when(mapper.vehicleExitEvidence(42,live.getId(),8L,java.sql.Timestamp.valueOf("2024-12-31 22:00:00.123"),java.sql.Timestamp.valueOf("2099-01-01 00:00:00.456"))).thenReturn(1);assertTrue(handler.applyExact(row,business));vehicle();assertTrue(new VisitorVehicleAuthSourceHandler(mapper).applyExact(row,business));fellow();assertFalse(new VisitorFellowAuthSourceHandler(mapper).applyExact(row,business));}
 @Test public void fellowExitCannotDeleteMainOrVehicle(){fellow();deletion(Trigger.FELLOW_EXIT);when(mapper.fellowExitEvidence(42,910000000000000002L,8L,java.sql.Timestamp.valueOf("2024-12-31 22:00:00.123"),java.sql.Timestamp.valueOf("2099-01-01 00:00:00.456"))).thenReturn(1);assertTrue(new VisitorFellowAuthSourceHandler(mapper).applyExact(row,business));assertFalse(handler.applyExact(row,business));}
 @Test public void wholeMinuteEndTimeSupportsVehicleAndFellowExit(){live.setEndTime(java.sql.Timestamp.valueOf("2099-01-01 00:00:00"));business.getParent().setEndTime("2099-01-01T00:00");deletion(Trigger.VEHICLE_EXIT);java.sql.Timestamp end=java.sql.Timestamp.valueOf("2099-01-01 00:00:00");when(mapper.vehicleExitEvidence(42,live.getId(),8L,java.sql.Timestamp.valueOf("2024-12-31 22:00:00.123"),end)).thenReturn(1);assertTrue(handler.applyExact(row,business));vehicle();assertTrue(new VisitorVehicleAuthSourceHandler(mapper).applyExact(row,business));fellow();deletion(Trigger.FELLOW_EXIT);when(mapper.fellowExitEvidence(42,910000000000000002L,8L,java.sql.Timestamp.valueOf("2024-12-31 22:00:00.123"),end)).thenReturn(1);assertTrue(new VisitorFellowAuthSourceHandler(mapper).applyExact(row,business));}
 @Test public void residentExitDoesNotCreateNewRevocationPolicy(){live.setCause(5);business.getParent().setCause(5);deletion(Trigger.VEHICLE_EXIT);when(mapper.vehicleExitEvidence(anyInt(),anyLong(),anyLong(),any(),any())).thenReturn(1);assertFalse(handler.applyExact(row,business));}
 @Test public void storedOffsetSurvivesLaterConfigurationChange(){org.springframework.test.util.ReflectionTestUtils.setField(handler,"leadHours",3);assertTrue(handler.applyExact(row,business));try{handler.lockAndValidate(selection());fail("新受理必须用当前配置");}catch(IllegalArgumentException expected){}}
 @Test public void correctMicrosecondSnapshotCanSettle(){java.sql.Timestamp t=java.sql.Timestamp.valueOf("2099-01-01 00:00:00.456123");live.setEndTime(t);business.getParent().setEndTime("2099-01-01T00:00:00.456123");persist();assertTrue(handler.applyExact(row,business));}
 @Test public void reviewOnlySourceCannotBecomeConverged(){row.setVerificationReason("MISSING_RESOURCE_EVIDENCE");persist();assertFalse(handler.applyExact(row,business));}

 @Test public void productionHandlerRequiresAnOuterTransaction(){org.springframework.aop.framework.ProxyFactory f=new org.springframework.aop.framework.ProxyFactory(handler);f.setProxyTargetClass(true);f.addAdvice(new org.springframework.transaction.interceptor.TransactionInterceptor(new org.springframework.jdbc.datasource.DataSourceTransactionManager(new org.springframework.jdbc.datasource.DriverManagerDataSource()),new org.springframework.transaction.annotation.AnnotationTransactionAttributeSource()));AuthSourceHandler<VisitorAuthSnapshot> proxied=(AuthSourceHandler<VisitorAuthSnapshot>)f.getProxy();try{proxied.lockAndValidate(selection());fail("正式handler不能脱离外层事务持锁");}catch(org.springframework.transaction.IllegalTransactionStateException expected){}}
 @Test public void realMapperTimestampHandlerPreservesOracleMicroseconds() throws Exception {org.apache.ibatis.session.Configuration c=new org.apache.ibatis.session.Configuration();c.setMapUnderscoreToCamelCase(true);try(java.io.InputStream in=getClass().getResourceAsStream("/mapper/VisitorAuthOperationMapper.xml")){assertNotNull(in);new org.apache.ibatis.builder.xml.XMLMapperBuilder(in,c,"mapper/VisitorAuthOperationMapper.xml",c.getSqlFragments()).parse();}org.apache.ibatis.mapping.ResultMapping time=c.getResultMap("com.tce.smart.platform.core.mapper.VisitorAuthOperationMapper.parent").getResultMappings().stream().filter(m->"endTime".equals(m.getProperty())).findFirst().get();java.sql.ResultSet rs=mock(java.sql.ResultSet.class);java.sql.Timestamp precise=java.sql.Timestamp.valueOf("2099-01-01 00:00:00.456123");when(rs.getTimestamp("END_TIME")).thenReturn(precise);Object read=time.getTypeHandler().getResult(rs,"END_TIME");assertTrue(read instanceof java.sql.Timestamp);assertEquals(456123000,((java.sql.Timestamp)read).getNanos());}
}
