/** 在编译后的真实页面验证两项业务流程，仅使用显式演示数据与本地服务。 */
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir } from 'node:fs/promises'
const require = createRequire(process.env.PLAYWRIGHT_MODULE_PATH ? process.env.PLAYWRIGHT_MODULE_PATH + '/package.json' : import.meta.url)
const { chromium } = require('playwright')
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, locale:'zh-CN' })
page.setDefaultTimeout(8000)
const errors = []
page.on('pageerror', error => errors.push(error.message))
const screenshotDir = new URL('../test-results/', import.meta.url)
await mkdir(screenshotDir, {recursive:true})
/** uni将占位文字渲染为独立节点，通过其控件容器定位真实输入元素。 */
function field(label) { return page.locator('uni-input:visible, uni-textarea:visible').filter({hasText:label}).locator('input, textarea') }
/** 点击可见业务按钮本身，兼容uni-button对内部文本的指针事件屏蔽。 */
async function button(label) {
  await page.locator('uni-button:visible').filter({has:page.getByText(label,{exact:true})}).click()
}
/** 从固定底栏切换工作区，不注入路由或应用状态。 */
async function tab(label) { await page.locator('.uni-tabbar__item').filter({hasText:label}).click() }
/** 显式选择测试角色，并等待工作台完成路由切换。 */
async function demo(label) {
  await button('体验演示')
  await button(label)
  await page.getByText('常用应用',{exact:true}).waitFor()
}
/** 正常退出再选择另一个角色，模拟申请人与办理人员使用不同账号。 */
async function changeRole(label) {
  await tab('我的')
  await button('退出登录')
  await page.getByText('工号登录',{exact:true}).waitFor()
  await demo(label)
}
/** 操作实际岗位滚轮，选择后核对表单中的名称。 */
async function pick(index, destination) {
  const picker = page.locator('uni-picker:visible').nth(index)
  await picker.click()
  const confirm = page.locator('.uni-picker-action-confirm').last()
  await confirm.waitFor()
  const column = page.locator('uni-picker-view-column').last()
  const box = await column.boundingBox()
  const desiredIndex = destination === '西门' ? 1 : 0
  const currentIndex = await page.locator('.uni-picker-view-content').last().evaluate(element => element.style.transform.startsWith('translateY(-34') ? 1 : 0)
  if (desiredIndex !== currentIndex) {
    await column.click({position:{x:box.width/2,y:box.height/2+(desiredIndex > currentIndex ? 34 : -34)}})
    await page.waitForFunction(index=>document.querySelectorAll('.uni-picker-view-content')[document.querySelectorAll('.uni-picker-view-content').length-1].style.transform.startsWith('translateY(' + (index === 1 ? '-34' : '0')), desiredIndex)
  }
  await confirm.click()
  await picker.getByText('演示园区'+destination,{exact:true}).waitFor()
}
/** 从审批/执行记录页打开本次测试创建的单据。 */
async function openRecord(module, title) {
  await button(module)
  await field('搜索单据、申请人或封条').fill(title)
  await button('查看详情')
  await page.getByText('申请详情',{exact:true}).waitFor()
}
/** 岗位仅在设置中保存，再从工作台进入现场业务。 */
async function post(name) {
  await tab('我的')
  await button('设置')
  await pick(0, name.includes('西门') ? '西门' : '东门')
  await button('保存设置')
  await page.locator('.page:visible').getByText('设置已保存',{exact:true}).waitFor()
  await page.goBack()
  await tab('工作台')
}
try {
  await page.goto(process.env.CLIENT_PREVIEW_URL || 'http://127.0.0.1:5179', { waitUntil: 'networkidle' })
  await page.getByText('工号登录', { exact: true }).waitFor()
  await page.screenshot({path:new URL('login-mobile.png',screenshotDir).pathname,fullPage:true})
  await field('请输入工号').fill('0001')
  await field('请输入密码').fill('local-test')
  await button('登录')
  await page.getByText(/服务尚未配置/).waitFor()
  await page.waitForFunction(()=>document.querySelector('input[type=password]').value === '',{},{timeout:2000})
  assert.equal(await field('请输入密码').inputValue(),'')
  await demo('正式员工')
  assert.equal(await page.locator('.post-button').count(),0,'工作台不提供现场岗位选择')
  assert.equal(await page.locator('.uni-tabbar__icon img').count(),4,'四个页签应有图标')
  await page.screenshot({path:new URL('workbench-mobile.png',screenshotDir).pathname,fullPage:true})
  assert.ok(await page.getByText('演示环境', { exact: false }).count() > 0)
  assert.equal(await page.getByText('物品放行审批',{exact:true}).count(),0)
  await button('全部应用')
  await field('搜索应用名称或用途').fill('物品')
  assert.equal(await page.locator('uni-button.tile-open').count(),2)
  await field('搜索应用名称或用途').fill('不存在的应用')
  await page.getByText('没有找到可用应用',{exact:true}).waitFor()
  await page.goBack()
  await page.getByText('常用应用',{exact:true}).waitFor()

  // 设备设置须在统一入口保存，并在重新启动页面后继续生效。
  await tab('我的')
  assert.equal(await page.getByText('现场岗位',{exact:true}).count(),0)
  await button('设置')
  await page.locator('.scan-setting').filter({has:page.getByText('硬件扫码头',{exact:true})}).locator('uni-button').click()
  await button('保存设置')
  await page.locator('.page:visible').getByText('设置已保存',{exact:true}).waitFor()
  await page.reload({waitUntil:'networkidle'})
  await page.getByText('工号登录',{exact:true}).waitFor()
  await demo('正式员工')
  const releaseTitle = '验收物品放行'
  await button('物品放行申请')
  assert.equal(await page.locator('.scan-mode-button').count(),0,'业务页不提供扫码方式切换')
  await field('按设备扫码键，或输入后确认').waitFor()
  await field('简要描述本次申请').fill(releaseTitle)
  // 未保存的设置不能影响原表单，明确保存后返回则立即生效且保留业务草稿。
  await button('前往设置')
  await page.locator('.scan-setting').filter({has:page.getByText('摄像头',{exact:true})}).locator('uni-button').click()
  await page.goBack()
  await field('按设备扫码键，或输入后确认').waitFor()
  assert.equal(await field('简要描述本次申请').inputValue(), releaseTitle)
  await button('前往设置')
  await page.locator('.scan-setting').filter({has:page.getByText('摄像头',{exact:true})}).locator('uni-button').click()
  await button('保存设置')
  await page.locator('.page:visible').getByText('设置已保存',{exact:true}).waitFor()
  await page.goBack()
  await page.getByText('打开摄像头扫码',{exact:true}).waitFor()
  assert.equal(await field('简要描述本次申请').inputValue(), releaseTitle)
  await button('前往设置')
  await page.locator('.scan-setting').filter({has:page.getByText('硬件扫码头',{exact:true})}).locator('uni-button').click()
  await button('保存设置')
  await page.locator('.page:visible').getByText('设置已保存',{exact:true}).waitFor()
  await page.goBack()
  await field('按设备扫码键，或输入后确认').waitFor()
  await field('请填写用途和办理原因').fill('本地演示验收')
  await pick(0,'东门')
  await pick(1,'西门')
  await field('填写物料名称、数量及单位').fill('演示样品 2 箱')
  const scan = field('按设备扫码键，或输入后确认')
  await scan.fill('x'.repeat(4097))
  await scan.press('Enter')
  await page.getByText('扫码内容不能超过4096字符',{exact:true}).waitFor()
  assert.equal(await scan.inputValue(), '', '异常码应清空，下一次硬件扫码不能追加到错误内容上')
  await scan.pressSequentially('00001234',{delay:0})
  await scan.press('Enter')
  await page.getByText('00001234',{exact:true}).waitFor()
  await button('提交申请')
  await page.getByText('申请详情',{exact:true}).waitFor()
  await page.getByText('待审批',{exact:true}).waitFor()
  await page.getByText('出发：演示园区东门 · 到达：演示园区西门',{exact:true}).waitFor()
  console.log('物品申请、岗位滚轮与扫码保留前导零通过')

  // 从详情正常返回工作台后切换角色，维持同一演示进程记录。
  await page.goBack()
  await changeRole('外包／派遣人员')
  assert.equal(await page.getByText('保密区通行申请',{exact:true}).count(),0)
  await changeRole('审批主管')
  await openRecord('物品放行审批',releaseTitle)
  await page.getByText('出发：演示园区东门 · 到达：演示园区西门',{exact:true}).waitFor()
  const approveBox = await page.locator('uni-button:visible').filter({has:page.getByText('同意申请',{exact:true})}).boundingBox()
  const rejectBox = await page.locator('uni-button:visible').filter({has:page.getByText('驳回申请',{exact:true})}).boundingBox()
  assert.ok(Math.abs(approveBox.y-rejectBox.y)<2,'审批动作应在同一行')
  assert.ok(approveBox.x-(rejectBox.x+rejectBox.width)>=10,'审批动作需要清晰间距')
  assert.ok(approveBox.height>=44 && rejectBox.height>=44,'审批触控区域至少44px')
  await button('驳回申请')
  await page.getByText('驳回时请填写原因',{exact:true}).waitFor()
  await page.screenshot({path:new URL('approval-mobile.png',screenshotDir).pathname,fullPage:true})
  await button('同意申请')
  await page.getByText('待执行',{exact:true}).waitFor()
  await page.goBack(); await page.goBack()
  await openRecord('物品放行审批','演示物品放行申请')
  await button('同意申请')
  await page.getByText('待执行',{exact:true}).waitFor()
  await page.goBack(); await page.goBack()
  await changeRole('现场安检')
  await button('物品现场执行')
  await page.getByText('请选择岗位',{exact:true}).waitFor()
  assert.equal(await field('搜索单据、申请人或封条').isDisabled(),true,'未选岗不能搜索执行单据')
  assert.equal(await page.locator('uni-button:visible').filter({hasText:'扫码定位单据'}).count(),0,'现场扫码直接使用搜索框，不再有独立入口')
  assert.equal(await page.getByText('查看详情',{exact:true}).count(),0,'未选岗不显示可执行单据')
  assert.equal(await page.getByText('切换岗位',{exact:true}).count(),0)
  await page.goBack()
  await page.evaluate(()=>{ location.hash='/pages/scan/scan?kind=item-pass' })
  await page.locator('.page:visible').getByText('扫码定位单据',{exact:true}).waitFor()
  assert.equal(await field('按设备扫码键，或输入后确认').isDisabled(),true,'未选岗直链扫码同样禁止')
  await page.goBack()
  await page.getByText('常用应用',{exact:true}).waitFor()
  await page.evaluate(()=>{ location.hash='/pages/detail/detail?id=demo-release-pending&view=execute' })
  await page.getByText('请先确认安检岗位',{exact:true}).waitFor()
  assert.equal(await page.getByText('申请详情',{exact:true}).count(),0,'未选岗执行直链不得展示单据')
  await page.goBack()
  await page.getByText('常用应用',{exact:true}).waitFor()
  await post('演示园区东门')
  await button('物品现场执行')
  const search = field('搜索单据、申请人或封条')
  await page.waitForFunction(() => document.activeElement === document.querySelector('.record-search input'))
  assert.equal(await page.locator('.search-camera:visible').count(),0,'扫码头模式不显示摄像头按钮')
  // 不点击、不回车便输入部分编号，列表必须已经筛选。
  await page.keyboard.type('000012',{delay:0})
  await page.waitForFunction(() => document.querySelectorAll('.record-card').length === 1)
  await page.locator('.record-card').getByText(releaseTitle,{exact:true}).waitFor()
  await page.keyboard.type('34',{delay:0})
  await page.keyboard.press('Enter')
  await page.waitForFunction(() => { const field=document.querySelector('.record-search input'); return document.activeElement === field && field.selectionStart === 0 && field.selectionEnd === field.value.length })
  assert.equal(await search.inputValue(),'00001234')
  await page.keyboard.type('DEMO-SEAL-001',{delay:0})
  await page.keyboard.press('Enter')
  await page.locator('.record-card').getByText('演示物品放行申请',{exact:true}).waitFor()
  assert.equal(await search.inputValue(),'DEMO-SEAL-001','连续扫码应替换上个码，不能拼接')
  assert.ok(page.url().includes('/pages/records/records'),'回车不会跳转详情')
  await page.locator('.search-clear').click()
  await page.waitForFunction(() => document.querySelectorAll('.record-card').length === 2)
  await page.screenshot({path:new URL('execution-search-hardware.png',screenshotDir).pathname,fullPage:true})
  await page.goBack()
  await openRecord('物品现场执行',releaseTitle)
  assert.equal(await page.getByText('切换岗位',{exact:true}).count(),0)
  await button('押运人')
  const depart = page.locator('uni-button:visible').filter({hasText:'确认出发'})
  assert.equal(await depart.getAttribute('disabled'),'true')
  await button('模拟押运人刷卡（仅演示）')
  await button('确认出发')
  await page.getByText('运输中',{exact:true}).waitFor()
  await page.goBack(); await page.goBack()
  await post('演示园区西门')
  await openRecord('物品现场执行',releaseTitle)
  await button('模拟押运人刷卡（仅演示）')
  await button('确认到达并归档')
  await page.getByText('已完成',{exact:true}).waitFor()
  console.log('物品审批、岗位前置、模拟押运人刷卡及出发到达通过')
  await page.goBack(); await page.goBack()
  await post('演示园区东门')
  await openRecord('物品现场执行','演示物品放行申请')
  assert.equal(await page.locator('uni-button:visible').filter({hasText:'确认出发'}).getAttribute('disabled'),'true','未选押运方式不能执行')
  await button('定位锁')
  assert.equal(await page.locator('uni-button:visible').filter({hasText:'确认出发'}).getAttribute('disabled'),'true','锁号必填')
  await field('请输入定位锁编号').fill('000009')
  await button('确认出发')
  await page.getByText('运输中',{exact:true}).waitFor()
  await page.getByText('定位锁 · 000009',{exact:true}).waitFor()
  await page.screenshot({path:new URL('lock-transport-mobile.png',screenshotDir).pathname,fullPage:true})
  await page.goBack(); await page.goBack()
  await post('演示园区西门')
  await openRecord('物品现场执行','演示物品放行申请')
  assert.equal(await page.locator('.transport-option:visible').count(),0,'到达沿用出发登记方式')
  await field('请输入定位锁编号').fill('000010')
  await button('确认到达并归档')
  await page.locator('.error:visible').filter({hasText:/定位锁/}).waitFor()
  await field('请输入定位锁编号').fill('000009')
  await button('确认到达并归档')
  await page.getByText('已完成',{exact:true}).waitFor()
  console.log('定位锁必填、前导零保存与到达同号核验通过')
  await page.goBack(); await page.goBack()
  await post('演示园区东门')
  await button('厂牌扫码核验')
  await page.getByText('供应商厂牌核验',{exact:true}).waitFor()
  assert.equal(await page.getByText('切换岗位',{exact:true}).count(),0)
  await field('按设备扫码键，或输入后确认').fill('NOT-A-BADGE')
  await field('按设备扫码键，或输入后确认').press('Enter')
  await page.getByText('厂牌无效，无法核验',{exact:true}).waitFor()
  assert.equal(await page.getByText('登记进入',{exact:true}).count(),0)
  await field('按设备扫码键，或输入后确认').fill('DEMO-BADGE-001')
  await field('按设备扫码键，或输入后确认').press('Enter')
  await page.getByText('核验通过',{exact:true}).waitFor()
  for (const label of ['授权期限','授权区域','被访人','被访人联系方式','人员联系方式','公司信息','暂无照片']) await page.locator('.page:visible').getByText(label,{exact:true}).first().waitFor()
  await page.screenshot({path:new URL('supplier-verified-mobile.png',screenshotDir).pathname,fullPage:true})
  await button('登记进入')
  await page.getByText(/已登记进入/).waitFor()
  assert.equal(await page.getByText('核验通过',{exact:true}).count(),0,'登记后必须重新核验')
  await field('按设备扫码键，或输入后确认').fill('DEMO-BADGE-001')
  await field('按设备扫码键，或输入后确认').press('Enter')
  await page.getByText('核验通过',{exact:true}).waitFor()
  await button('登记离开')
  await page.getByText(/已登记离开/).waitFor()
  assert.equal(await page.getByText('核验通过',{exact:true}).count(),0)
  // 连续字符与紧随其后的回车模拟扫码头，不等待框架的输入节流计时。
  await field('按设备扫码键，或输入后确认').pressSequentially('DEMO-BADGE-001',{delay:0})
  await field('按设备扫码键，或输入后确认').press('Enter')
  await page.getByText('核验通过',{exact:true}).waitFor()
  await button('登记进入')
  await page.getByText(/已登记进入/).waitFor()
  await button('查看通行记录')
  await page.locator('.page:visible').getByText('供应商通行记录',{exact:true}).waitFor()
  await page.locator('.passage-card').first().waitFor()
  assert.equal(await page.locator('.passage-card').count(),3)
  await button('进入')
  await page.getByText('2 条符合条件的记录',{exact:true}).waitFor()
  assert.equal(await page.locator('.passage-card').count(),2)
  await button('离开')
  await page.getByText('1 条符合条件的记录',{exact:true}).waitFor()
  assert.equal(await page.locator('.passage-card').count(),1)
  await button('全部')
  await page.getByText('3 条符合条件的记录',{exact:true}).waitFor()
  await page.screenshot({path:new URL('supplier-records-mobile.png',screenshotDir).pathname,fullPage:true})
  console.log('供应商厂牌拒绝、核验、显式进出登记与独立事件记录通过')
  await page.goBack(); await page.goBack()
  await tab('我的')
  assert.equal(await page.getByText('现场岗位',{exact:true}).count(),0)
  await button('设置')
  await page.locator('.scan-setting').filter({has:page.getByText('摄像头',{exact:true})}).locator('uni-button').click()
  await button('保存设置')
  await page.locator('.page:visible').getByText('设置已保存',{exact:true}).waitFor()
  await page.goBack()
  await page.getByText('摄像头',{exact:true}).waitFor()
  await tab('工作台')
  await button('物品现场执行')
  await page.locator('.search-camera:visible').waitFor()
  for (const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:1000})
    const inputBox = await field('搜索单据、申请人或封条').boundingBox()
    const cameraBox = await page.locator('.search-camera:visible').boundingBox()
    assert.ok(cameraBox.x >= inputBox.x + inputBox.width,'相机按钮应在搜索框右侧')
    assert.ok(Math.abs(cameraBox.y + cameraBox.height / 2 - inputBox.y - inputBox.height / 2) < 3,'相机按钮与搜索框同排')
    assert.ok(cameraBox.x + cameraBox.width <= width && cameraBox.width >= 44 && cameraBox.height >= 44)
  }
  await page.locator('.search-camera').click()
  await page.getByText('当前平台暂不支持相机扫码，请前往设置选择扫码头',{exact:true}).waitFor()
  await field('搜索单据、申请人或封条').fill('仍可手工搜索')
  await page.getByText('暂无符合条件的记录',{exact:true}).waitFor()
  await page.screenshot({path:new URL('execution-search-camera.png',screenshotDir).pathname,fullPage:true})
  await page.goBack()
  await tab('我的')
  await button('退出登录')
  await demo('外包／派遣人员')
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:new URL('workbench-desktop.png',screenshotDir).pathname,fullPage:true})
  await page.evaluate(()=>{ location.hash='/pages/records/records?kind=item-pass&view=approve' })
  await page.waitForURL('**/#/pages/workbench/workbench')
  await page.locator('.page:visible').getByText('常用应用',{exact:true}).waitFor()
  assert.equal(await page.getByText('物品放行审批',{exact:true}).count(),0)
  await page.evaluate(()=>{ location.hash='/pages/posts/posts' })
  await page.waitForURL('**/#/pages/workbench/workbench')
  await page.getByText('常用应用',{exact:true}).waitFor()
  assert.equal(await page.locator('.post-card:visible').count(),0,'申请人不能通过直链绑定安检岗位')
  await page.evaluate(()=>{ location.hash='/pages/application/application?kind=supplier' })
  await page.getByText('此入口已调整',{exact:true}).waitFor()
  assert.equal(await page.getByText('提交申请',{exact:true}).count(),0)
  await button('返回工作台')
  await page.waitForURL('**/#/pages/workbench/workbench')
  await page.locator('.page:visible').getByText('常用应用',{exact:true}).waitFor()
  for (const route of ['application','records','scan']) {
    await page.evaluate(route=>{ location.hash='/pages/'+route+'/'+route+'?kind=garbage' },route)
    await page.getByText('无效业务入口',{exact:true}).waitFor()
    await button('返回工作台')
    await page.waitForURL('**/#/pages/workbench/workbench')
    await page.locator('.page:visible').getByText('常用应用',{exact:true}).waitFor()
  }
  await tab('我的')
  await button('退出登录')
  await page.goto((process.env.CLIENT_PREVIEW_URL || 'http://127.0.0.1:5179') + '/#/pages/application/application?kind=item-pass')
  await page.getByText('工号登录',{exact:true}).waitFor()
  assert.deepEqual(errors,[])
  console.log('三类身份、应用搜索、扫码设置和宽屏验收通过')
} catch (error) {
  await page.screenshot({path:new URL('failure.png',screenshotDir).pathname,fullPage:true})
  throw error
} finally { await browser.close() }
