-- 回退 PR #143 的保密权限批次字段和索引。
-- 先发布不再读写这些字段的代码；任一前置检查发现旧数据时整段脚本中止，不执行删列。
-- BATCH_ID 不属于本次回退范围，禁止删除。
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(1) INTO V_COUNT
    FROM SMT_ISC_DEVICE_TASK
    WHERE SOURCE_TYPE IS NOT NULL
       OR SOURCE_ID IS NOT NULL
       OR SOURCE_DETAIL_ID IS NOT NULL
       OR INTENT_KEY IS NOT NULL;
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, '存在保密权限来源任务数据，禁止回退字段');
    END IF;

    SELECT COUNT(1) INTO V_COUNT
    FROM SMT_SECURITY_AUTH_APPLY
    WHERE CURRENT_DISPATCH_BATCH_ID IS NOT NULL;
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, '存在保密权限申请批次数据，禁止回退字段');
    END IF;

    SELECT COUNT(1) INTO V_COUNT
    FROM SMT_SECURITY_TASK_DETAILS
    WHERE DISPATCH_BATCH_ID IS NOT NULL;
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, '存在保密权限明细批次数据，禁止回退字段');
    END IF;

    SELECT COUNT(1) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SEC_AUTH_DETAIL_BATCH';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'DROP INDEX IDX_SEC_AUTH_DETAIL_BATCH'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_ISC_TASK_SECURITY_BATCH';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'DROP INDEX IDX_ISC_TASK_SECURITY_BATCH'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_ISC_TASK_SECURITY_INTENT';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'DROP INDEX IDX_ISC_TASK_SECURITY_INTENT'; END IF;

    SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'INTENT_KEY';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN INTENT_KEY'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'SOURCE_DETAIL_ID';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN SOURCE_DETAIL_ID'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'SOURCE_ID';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN SOURCE_ID'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'SOURCE_TYPE';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN SOURCE_TYPE'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_SECURITY_TASK_DETAILS' AND COLUMN_NAME = 'DISPATCH_BATCH_ID';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_TASK_DETAILS DROP COLUMN DISPATCH_BATCH_ID'; END IF;
    SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_SECURITY_AUTH_APPLY' AND COLUMN_NAME = 'CURRENT_DISPATCH_BATCH_ID';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_AUTH_APPLY DROP COLUMN CURRENT_DISPATCH_BATCH_ID'; END IF;
END;
/
