-- 手工数据库回滚：人员海康 ISC 实体卡主表。
-- 可重复执行：对象不存在时跳过。执行后会删除数据，请仅在回滚时整段执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_STAFF_CARD_PARK'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SMT_ISC_STAFF_CARD_PARK';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_STAFF_CARD_BADGE'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SMT_ISC_STAFF_CARD_BADGE';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_STAFF_CARD_STAFF'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SMT_ISC_STAFF_CARD_STAFF';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_STAFF_CARD_ACTIVE'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX UK_SMT_ISC_STAFF_CARD_ACTIVE';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP TABLE SMT_ISC_STAFF_CARD';
	END IF;
END;
