-- 手工数据库变更：海康 ISC 卡片初始化导入批次与明细。
-- 当前平台没有数据库自动迁移机制。
-- 本脚本只记录“从海康 ISC 到本地”的初始化导入审计，不写入 SMT_ISC_CARD_TASK。
-- Oracle 低版本不支持 CREATE TABLE IF NOT EXISTS，本脚本使用单个 PL/SQL 匿名块做存在性判断。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_CARD_IMPORT_BATCH';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE q'[
			CREATE TABLE SMT_ISC_CARD_IMPORT_BATCH (
				ID NUMBER(20) NOT NULL,
				IMPORT_MODE VARCHAR2(32) NOT NULL,
				STATUS VARCHAR2(32) NOT NULL,
				PARK_ID NUMBER(10) NOT NULL,
				PARK_NAME VARCHAR2(128),
				DISPATCHER_PARK_ID NUMBER(10) NOT NULL,
				DISPATCHER_PARK_NAME VARCHAR2(128),
				TOTAL_COUNT NUMBER(10) DEFAULT 0,
				SUCCESS_COUNT NUMBER(10) DEFAULT 0,
				SKIP_COUNT NUMBER(10) DEFAULT 0,
				CONFLICT_COUNT NUMBER(10) DEFAULT 0,
				FAIL_COUNT NUMBER(10) DEFAULT 0,
				CONSUME NUMBER(20),
				PARAMS_JSON CLOB,
				REMARK VARCHAR2(1000),
				START_TIME DATE,
				END_TIME DATE,
				CREATE_TIME DATE,
				UPDATE_TIME DATE,
				OPT_USER VARCHAR2(64),
				CONSTRAINT PK_SMT_ISC_CARD_IMPORT_BATCH PRIMARY KEY (ID)
			)
		]';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_CARD_IMPORT_BATCH'
	  AND COLUMN_NAME = 'IMPORT_MODE';
	IF V_COUNT = 0 THEN
		SELECT COUNT(1) INTO V_COUNT
		FROM USER_TAB_COLUMNS
		WHERE TABLE_NAME = 'SMT_ISC_CARD_IMPORT_BATCH'
		  AND COLUMN_NAME = 'MODE';
		IF V_COUNT > 0 THEN
			EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_CARD_IMPORT_BATCH RENAME COLUMN "MODE" TO IMPORT_MODE';
		ELSE
			RAISE_APPLICATION_ERROR(-20003, 'SMT_ISC_CARD_IMPORT_BATCH 存在但缺少 IMPORT_MODE/MODE 列，请先人工确认表结构');
		END IF;
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_CARD_IMPORT_DETAIL';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE q'[
			CREATE TABLE SMT_ISC_CARD_IMPORT_DETAIL (
				ID NUMBER(20) NOT NULL,
				BATCH_ID NUMBER(20) NOT NULL,
				STAFF_ID NUMBER(20),
				BADGE VARCHAR2(64),
				NAME VARCHAR2(128),
				PARK_ID NUMBER(10) NOT NULL,
				DISPATCHER_PARK_ID NUMBER(10) NOT NULL,
				PERSON_ID VARCHAR2(64),
				ISC_CARD_NO VARCHAR2(64),
				LOCAL_CARD_NO VARCHAR2(64),
				RESULT_CODE VARCHAR2(64) NOT NULL,
				RESULT_DESC VARCHAR2(128),
				REASON VARCHAR2(1000),
				CREATE_TIME DATE,
				UPDATE_TIME DATE,
				CONSTRAINT PK_SMT_ISC_CARD_IMPORT_DETAIL PRIMARY KEY (ID)
			)
		]';
	END IF;

	EXECUTE IMMEDIATE q'[COMMENT ON TABLE SMT_ISC_CARD_IMPORT_BATCH IS '海康 ISC 卡片初始化导入批次表']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.IMPORT_MODE IS '模式：DRY_RUN-预检，IMPORT-导入']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.STATUS IS '状态：INIT/RUNNING/SUCCESS/FAIL']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.PARK_ID IS '本系统业务园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.DISPATCHER_PARK_ID IS '用于分发服务路由目标海康 ISC 的园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.TOTAL_COUNT IS '明细总数']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.SUCCESS_COUNT IS '可导入或已导入数量']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.SKIP_COUNT IS '跳过数量']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.CONFLICT_COUNT IS '冲突数量']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.FAIL_COUNT IS '失败或异常数量']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.PARAMS_JSON IS '创建批次时的请求参数']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_BATCH.OPT_USER IS '操作人账号']';

	EXECUTE IMMEDIATE q'[COMMENT ON TABLE SMT_ISC_CARD_IMPORT_DETAIL IS '海康 ISC 卡片初始化导入明细表']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.BATCH_ID IS '导入批次 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.STAFF_ID IS '本系统员工 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.BADGE IS '员工工号 / ISC 工号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.PERSON_ID IS '海康 ISC 人员 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.ISC_CARD_NO IS '海康 ISC 返回的实体卡号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.LOCAL_CARD_NO IS '本地已存在的实体卡号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.RESULT_CODE IS '处理结果编码']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_IMPORT_DETAIL.REASON IS '处理原因']';

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IX_ISC_CARD_IMP_BAT_PARK'
	  AND TABLE_NAME = 'SMT_ISC_CARD_IMPORT_BATCH';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IX_ISC_CARD_IMP_BAT_PARK ON SMT_ISC_CARD_IMPORT_BATCH (PARK_ID, STATUS, CREATE_TIME)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IX_ISC_CARD_IMP_DET_BATCH'
	  AND TABLE_NAME = 'SMT_ISC_CARD_IMPORT_DETAIL';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IX_ISC_CARD_IMP_DET_BATCH ON SMT_ISC_CARD_IMPORT_DETAIL (BATCH_ID, RESULT_CODE, CREATE_TIME)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IX_ISC_CARD_IMP_DET_CARD'
	  AND TABLE_NAME = 'SMT_ISC_CARD_IMPORT_DETAIL';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IX_ISC_CARD_IMP_DET_CARD ON SMT_ISC_CARD_IMPORT_DETAIL (PARK_ID, BADGE, ISC_CARD_NO)';
	END IF;
END;
