-- 能耗日汇总投影表回滚脚本。
-- 只有正向脚本实际新建并以 20260805_ENERGY_PROJECTION marker 记录的表才允许删除。
-- marker 不存在、未匹配或已回滚时均显式跳过；保留 Oracle 默认可恢复窗口。

DECLARE
    v_marker_count NUMBER := 0; v_table_count NUMBER := 0;
BEGIN
    BEGIN EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL' INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_METER_DAY_LOCK', 'TABLE';
    EXCEPTION WHEN OTHERS THEN IF SQLCODE = -942 THEN v_marker_count := 0; ELSE RAISE; END IF; END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_METER_DAY_LOCK';
        IF v_table_count > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_METER_DAY_LOCK CASCADE CONSTRAINTS'; UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_METER_DAY_LOCK' AND OBJECT_TYPE = 'TABLE'; COMMIT;
        ELSE DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_METER_DAY_LOCK：marker 存在但表不存在，保留 marker 供审计。'); END IF;
    ELSE DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_METER_DAY_LOCK：未找到本发行的活动 marker。'); END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_PARK_DAY_LOCK', 'TABLE';
    EXCEPTION WHEN OTHERS THEN
        IF SQLCODE = -942 THEN v_marker_count := 0; ELSE RAISE; END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PARK_DAY_LOCK';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_PARK_DAY_LOCK CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_PARK_DAY_LOCK' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PARK_DAY_LOCK：marker 存在但表不存在，保留 marker 供审计。'); END IF;
    ELSE DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PARK_DAY_LOCK：未找到本发行的活动 marker。'); END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_PARK_DAY', 'TABLE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                v_marker_count := 0;
            ELSE
                RAISE;
            END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PARK_DAY';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_PARK_DAY CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_PARK_DAY' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PARK_DAY：marker 存在但表不存在，保留 marker 供审计。');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PARK_DAY：未找到本发行的活动 marker。');
    END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_PARK_DAY_ITEM', 'TABLE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                v_marker_count := 0;
            ELSE
                RAISE;
            END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PARK_DAY_ITEM';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_PARK_DAY_ITEM CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_PARK_DAY_ITEM' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PARK_DAY_ITEM：marker 存在但表不存在，保留 marker 供审计。');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PARK_DAY_ITEM：未找到本发行的活动 marker。');
    END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_METER_DAY_FACT', 'TABLE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                v_marker_count := 0;
            ELSE
                RAISE;
            END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_METER_DAY_FACT';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_METER_DAY_FACT CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_METER_DAY_FACT' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_METER_DAY_FACT：marker 存在但表不存在，保留 marker 供审计。');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_METER_DAY_FACT：未找到本发行的活动 marker。');
    END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_METER_SCOPE_RULE', 'TABLE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                v_marker_count := 0;
            ELSE
                RAISE;
            END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_METER_SCOPE_RULE';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_METER_SCOPE_RULE CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_METER_SCOPE_RULE' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_METER_SCOPE_RULE：marker 存在但表不存在，保留 marker 供审计。');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_METER_SCOPE_RULE：未找到本发行的活动 marker。');
    END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_PROJECTION_QUEUE', 'TABLE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                v_marker_count := 0;
            ELSE
                RAISE;
            END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PROJECTION_QUEUE';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_PROJECTION_QUEUE CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_PROJECTION_QUEUE' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PROJECTION_QUEUE：marker 存在但表不存在，保留 marker 供审计。');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_PROJECTION_QUEUE：未找到本发行的活动 marker。');
    END IF;
END;
/

DECLARE
    v_marker_count NUMBER := 0;
    v_table_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM SMT_ENERGY_RELEASE_MARKER WHERE RELEASE_KEY = :1 AND OBJECT_NAME = :2 AND OBJECT_TYPE = :3 AND ROLLED_BACK_AT IS NULL'
            INTO v_marker_count USING '20260805_ENERGY_PROJECTION', 'SMT_ENERGY_INGESTION_LEDGER', 'TABLE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -942 THEN
                v_marker_count := 0;
            ELSE
                RAISE;
            END IF;
    END;
    IF v_marker_count > 0 THEN
        SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_INGESTION_LEDGER';
        IF v_table_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE SMT_ENERGY_INGESTION_LEDGER CASCADE CONSTRAINTS';
            UPDATE SMT_ENERGY_RELEASE_MARKER SET ROLLED_BACK_AT = SYSTIMESTAMP
                WHERE RELEASE_KEY = '20260805_ENERGY_PROJECTION' AND OBJECT_NAME = 'SMT_ENERGY_INGESTION_LEDGER' AND OBJECT_TYPE = 'TABLE';
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_INGESTION_LEDGER：marker 存在但表不存在，保留 marker 供审计。');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('跳过 SMT_ENERGY_INGESTION_LEDGER：未找到本发行的活动 marker。');
    END IF;
END;
/
