-- Optional. Run this once in the current session before creating indexes.
ALTER SESSION SET DDL_LOCK_TIMEOUT = 600;

-- Step 1. Check the index first.
SELECT TABLE_NAME, INDEX_NAME, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME = 'IX_DEV_AUTH_REL_DEVICE_ID'
ORDER BY TABLE_NAME, INDEX_NAME;

-- Step 2. Generate CREATE INDEX statement only if missing.
WITH REQUIRED_INDEXES AS (
	SELECT
		'IX_DEV_AUTH_REL_DEVICE_ID' AS INDEX_NAME,
		'SMT_DEVICE_AUTHORITY_RELATION' AS TABLE_NAME,
		'CREATE INDEX IX_DEV_AUTH_REL_DEVICE_ID ON SMT_DEVICE_AUTHORITY_RELATION (DEVICE_ID)' AS DDL
	FROM DUAL
)
SELECT REQUIRED_INDEXES.INDEX_NAME, REQUIRED_INDEXES.TABLE_NAME, REQUIRED_INDEXES.DDL
FROM REQUIRED_INDEXES
WHERE NOT EXISTS (
	SELECT 1
	FROM USER_INDEXES EXISTING_INDEX
	WHERE EXISTING_INDEX.INDEX_NAME = REQUIRED_INDEXES.INDEX_NAME
	  AND EXISTING_INDEX.TABLE_NAME = REQUIRED_INDEXES.TABLE_NAME
);

-- Step 3. Manual fallback. Uncomment and run only if Step 2 returned the row.
-- CREATE INDEX IX_DEV_AUTH_REL_DEVICE_ID
-- ON SMT_DEVICE_AUTHORITY_RELATION (DEVICE_ID);
