-- 手工数据库变更：入厂申请照片拉取与状态回写批次模型。
-- 为 smt_isc_device_task 和 smt_admittance_apply 添加批次追踪字段。
-- Oracle 低版本不支持 CREATE TABLE IF NOT EXISTS，本脚本使用 PL/SQL 匿名块做存在性判断。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	-- 检查 smt_isc_device_task 表中 apply_id 列是否存在
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'APPLY_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (APPLY_ID NUMBER(20) NULL)';
		DBMS_OUTPUT.PUT_LINE('已添加 SMT_ISC_DEVICE_TASK.APPLY_ID 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_ISC_DEVICE_TASK.APPLY_ID 列已存在，跳过');
	END IF;

	-- 检查 smt_isc_device_task 表中 batch_id 列是否存在
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'BATCH_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (BATCH_ID NUMBER(20) NULL)';
		DBMS_OUTPUT.PUT_LINE('已添加 SMT_ISC_DEVICE_TASK.BATCH_ID 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_ISC_DEVICE_TASK.BATCH_ID 列已存在，跳过');
	END IF;

	-- 添加或验证 smt_isc_device_task (apply_id, batch_id) 复合索引
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_ISC_TASK_APPLY_BATCH'
	  AND TABLE_NAME = 'SMT_ISC_DEVICE_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISC_TASK_APPLY_BATCH ON SMT_ISC_DEVICE_TASK (APPLY_ID, BATCH_ID)';
		DBMS_OUTPUT.PUT_LINE('已创建索引 IDX_ISC_TASK_APPLY_BATCH');
	ELSE
		DBMS_OUTPUT.PUT_LINE('索引 IDX_ISC_TASK_APPLY_BATCH 已存在，跳过');
	END IF;

	-- 检查 smt_admittance_apply 表中 isc_submit_batch 列是否存在
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ADMITTANCE_APPLY'
	  AND COLUMN_NAME = 'ISC_SUBMIT_BATCH';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ADMITTANCE_APPLY ADD (ISC_SUBMIT_BATCH NUMBER(20) NULL)';
		DBMS_OUTPUT.PUT_LINE('已添加 SMT_ADMITTANCE_APPLY.ISC_SUBMIT_BATCH 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_ADMITTANCE_APPLY.ISC_SUBMIT_BATCH 列已存在，跳过');
	END IF;

	-- 添加表及列的中文备注
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_DEVICE_TASK.APPLY_ID IS '入厂申请单ID（非入厂申请来源为NULL）']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_DEVICE_TASK.BATCH_ID IS '下发批次号（同一次提交的任务集共享）']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ADMITTANCE_APPLY.ISC_SUBMIT_BATCH IS '最近一次成功提交ISC的批次号；NULL=从未完成提交（补偿边界依据）']';

	DBMS_OUTPUT.PUT_LINE('批次模型字段初始化完成');
END;
