-- 保密区权限最新下发接管：批次、来源和意图键字段。
-- 使用 Oracle 匿名 PL/SQL 块保证重复执行安全；请整段执行，不要按分号拆分。
-- BATCH_ID 通常由 2026-07-01-isc-batch-model.sql 创建；未执行旧脚本的环境在此补齐该字段。

DECLARE
	V_COUNT NUMBER;
BEGIN
	-- 先校验既有批次字段；未执行历史脚本的环境在这里补齐，避免迁移顺序成为上线阻塞。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'BATCH_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (BATCH_ID NUMBER(20) NULL)';
	END IF;

	-- 申请单当前有效批次，用于后续事务内串行化最新下发命令。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_SECURITY_AUTH_APPLY'
	  AND COLUMN_NAME = 'CURRENT_DISPATCH_BATCH_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_AUTH_APPLY ADD (CURRENT_DISPATCH_BATCH_ID NUMBER(20) NULL)';
	END IF;

	-- 明细批次字段同时作为 WAIT 明细的持久化待消费标记。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_SECURITY_TASK_DETAILS'
	  AND COLUMN_NAME = 'DISPATCH_BATCH_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_TASK_DETAILS ADD (DISPATCH_BATCH_ID NUMBER(20) NULL)';
	END IF;

	-- ISC 任务业务来源字段，保密区权限路径不得写入 APPLY_ID。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'SOURCE_TYPE';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (SOURCE_TYPE VARCHAR2(32) NULL)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'SOURCE_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (SOURCE_ID NUMBER(20) NULL)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'SOURCE_DETAIL_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (SOURCE_DETAIL_ID NUMBER(20) NULL)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'INTENT_KEY';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK ADD (INTENT_KEY VARCHAR2(256) NULL)';
	END IF;

	-- 明细领取和批次进度查询索引。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SEC_AUTH_DETAIL_BATCH'
	  AND TABLE_NAME = 'SMT_SECURITY_TASK_DETAILS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEC_AUTH_DETAIL_BATCH ON SMT_SECURITY_TASK_DETAILS (APPLY_ID, DISPATCH_BATCH_ID, STATUS)';
	END IF;

	-- 按业务来源、批次和状态隔离保密区 ISC 任务。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_ISC_TASK_SECURITY_BATCH'
	  AND TABLE_NAME = 'SMT_ISC_DEVICE_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISC_TASK_SECURITY_BATCH ON SMT_ISC_DEVICE_TASK (SOURCE_TYPE, SOURCE_ID, BATCH_ID, STATUS)';
	END IF;

	-- 旧任务接管按人员、权限策略和设备组成的意图键检索。
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_ISC_TASK_SECURITY_INTENT'
	  AND TABLE_NAME = 'SMT_ISC_DEVICE_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_ISC_TASK_SECURITY_INTENT ON SMT_ISC_DEVICE_TASK (SOURCE_TYPE, INTENT_KEY, STATUS)';
	END IF;

	-- 所有新增字段均写中文注释，便于现场排障关联三张表。
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_SECURITY_AUTH_APPLY.CURRENT_DISPATCH_BATCH_ID IS '当前保密区权限下发批次号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_SECURITY_TASK_DETAILS.DISPATCH_BATCH_ID IS '保密区权限明细所属下发批次号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_DEVICE_TASK.SOURCE_TYPE IS '业务来源类型，保密区权限下发为 SECURITY_AUTH']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_DEVICE_TASK.SOURCE_ID IS '业务来源主键，保密区权限下发对应申请单 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_DEVICE_TASK.SOURCE_DETAIL_ID IS '业务来源明细主键，保密区权限下发对应明细 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_DEVICE_TASK.INTENT_KEY IS '权限下发意图键：人员、权限策略和设备的组合']';
END;
/
