-- 回滚保密区权限最新下发接管的新增字段和索引。
-- BATCH_ID 由 2026-07-01-isc-batch-model.sql 创建，本回滚绝不删除该既有字段。
-- 使用 Oracle 匿名 PL/SQL 块保证重复执行安全；请整段执行，不要按分号拆分。

DECLARE
	V_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SEC_AUTH_DETAIL_BATCH'
	  AND TABLE_NAME = 'SMT_SECURITY_TASK_DETAILS';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SEC_AUTH_DETAIL_BATCH';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_ISC_TASK_SECURITY_BATCH'
	  AND TABLE_NAME = 'SMT_ISC_DEVICE_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_ISC_TASK_SECURITY_BATCH';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_ISC_TASK_SECURITY_INTENT'
	  AND TABLE_NAME = 'SMT_ISC_DEVICE_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_ISC_TASK_SECURITY_INTENT';
	END IF;

	-- 按依赖关系逆序删除 Task 1 新增字段；历史 BATCH_ID 保留给入厂申请批次模型。
	SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'INTENT_KEY';
	IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN INTENT_KEY'; END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'SOURCE_DETAIL_ID';
	IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN SOURCE_DETAIL_ID'; END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'SOURCE_ID';
	IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN SOURCE_ID'; END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK' AND COLUMN_NAME = 'SOURCE_TYPE';
	IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN SOURCE_TYPE'; END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_SECURITY_TASK_DETAILS' AND COLUMN_NAME = 'DISPATCH_BATCH_ID';
	IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_TASK_DETAILS DROP COLUMN DISPATCH_BATCH_ID'; END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_SECURITY_AUTH_APPLY' AND COLUMN_NAME = 'CURRENT_DISPATCH_BATCH_ID';
	IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_AUTH_APPLY DROP COLUMN CURRENT_DISPATCH_BATCH_ID'; END IF;
END;
/
