-- 手工数据库变更：独立海康 ISC 卡片同步任务。
-- 当前平台没有数据库自动迁移机制。
-- 表创建后，再通过 task.job.isc-card-task-sync=true 显式启用调度任务。
-- Oracle 低版本不支持 CREATE TABLE IF NOT EXISTS，本脚本使用单个 PL/SQL 匿名块做存在性判断。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE q'[
			CREATE TABLE SMT_ISC_CARD_TASK (
				ID NUMBER(20) NOT NULL,
				ACTION NUMBER(3) NOT NULL,
				PRIORITY NUMBER(10) DEFAULT 50 NOT NULL,
				STATUS NUMBER(3),
				PARK_ID NUMBER(10) NOT NULL,
				SOURCE_TYPE VARCHAR2(32),
				SOURCE_ID NUMBER(20),
				BADGE VARCHAR2(64),
				PERSON_ID VARCHAR2(64),
				CARD_NO VARCHAR2(64) NOT NULL,
				ACTIVE_KEY VARCHAR2(256),
				LEASE_TOKEN VARCHAR2(64),
				RUNNING_KEY VARCHAR2(128),
				CODE NUMBER(10),
				REMARK VARCHAR2(512),
				CONSUME NUMBER(20),
				TIMES NUMBER(10),
				OVER_TIME NUMBER(20) NOT NULL,
				CREATE_TIME DATE,
				UPDATE_TIME DATE,
				OPT_USER VARCHAR2(64),
				CONSTRAINT PK_SMT_ISC_CARD_TASK PRIMARY KEY (ID)
			)
		]';
	END IF;

	EXECUTE IMMEDIATE q'[COMMENT ON TABLE SMT_ISC_CARD_TASK IS '海康 ISC 卡片资源同步任务表']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.ID IS '主键']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.ACTION IS '任务动作：1-新增卡片，2-删除卡片']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.PRIORITY IS '任务优先级，数值越大越先执行']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.STATUS IS '任务状态：0-初始化，1-成功，2-失败，3-执行中，4-取消']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.PARK_ID IS '分发服务路由园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.SOURCE_TYPE IS '本系统业务来源类型，例如 STAFF']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.SOURCE_ID IS '本系统业务来源 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.BADGE IS '员工工号 / ISC 工号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.PERSON_ID IS '目标 ISC 平台解析到的人员 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.CARD_NO IS '海康 ISC 实体卡号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.ACTIVE_KEY IS '未完成任务唯一键，成功或取消后清空']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.LEASE_TOKEN IS '当前执行租约标识']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.RUNNING_KEY IS '同一业务来源当前执行任务唯一键']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.CODE IS '执行结果编码']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.REMARK IS '执行结果备注']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.CONSUME IS '执行耗时，单位毫秒']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.TIMES IS '重试次数']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.OVER_TIME IS '下次可执行时间，秒级时间戳']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.CREATE_TIME IS '创建时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.UPDATE_TIME IS '更新时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_CARD_TASK.OPT_USER IS '操作人账号']';

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_CARD_TASK_PENDING'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_CARD_TASK_PENDING ON SMT_ISC_CARD_TASK (STATUS, PRIORITY, OVER_TIME)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_CARD_TASK_CARD'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_CARD_TASK_CARD ON SMT_ISC_CARD_TASK (BADGE, PARK_ID, CARD_NO)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_CARD_TASK_SOURCE'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_CARD_TASK_SOURCE ON SMT_ISC_CARD_TASK (SOURCE_TYPE, SOURCE_ID, PARK_ID, STATUS)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_CARD_TASK_ACTIVE'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_SMT_ISC_CARD_TASK_ACTIVE ON SMT_ISC_CARD_TASK (ACTIVE_KEY)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_CARD_TASK_RUNNING'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_SMT_ISC_CARD_TASK_RUNNING ON SMT_ISC_CARD_TASK (RUNNING_KEY)';
	END IF;
END;
