-- Optional. Run this once in the current session before creating indexes.
ALTER SESSION SET DDL_LOCK_TIMEOUT = 600;

-- Step 1. Check all cleanup indexes first.
SELECT TABLE_NAME, INDEX_NAME, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME IN (
	'IX_ISC_DR_CLN_BASE',
	'IX_ISC_DR_CLN_PERSON',
	'IX_ISC_DR_CLN_BADGE',
	'IX_ISC_DR_CLN_CARD',
	'IX_ISC_DT_CLN_PERSON',
	'IX_ISC_DT_CLN_BADGE',
	'IX_ISC_DT_CLN_CARD'
)
ORDER BY TABLE_NAME, INDEX_NAME;

-- Step 2. Generate CREATE INDEX statements for missing indexes only.
-- Copy the generated DDL rows and execute them one by one.
WITH REQUIRED_INDEXES AS (
	SELECT
		'IX_ISC_DR_CLN_BASE' AS INDEX_NAME,
		'SMT_ISC_DOWN_RECORD' AS TABLE_NAME,
		'CREATE INDEX IX_ISC_DR_CLN_BASE ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, PARK_ID, OVER_TIME, DEVICE_CODE)' AS DDL
	FROM DUAL
	UNION ALL
	SELECT
		'IX_ISC_DR_CLN_PERSON',
		'SMT_ISC_DOWN_RECORD',
		'CREATE INDEX IX_ISC_DR_CLN_PERSON ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, DEVICE_CODE, PARK_ID, PERSON_ID, OVER_TIME)'
	FROM DUAL
	UNION ALL
	SELECT
		'IX_ISC_DR_CLN_BADGE',
		'SMT_ISC_DOWN_RECORD',
		'CREATE INDEX IX_ISC_DR_CLN_BADGE ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, DEVICE_CODE, PARK_ID, BADGE, OVER_TIME)'
	FROM DUAL
	UNION ALL
	SELECT
		'IX_ISC_DR_CLN_CARD',
		'SMT_ISC_DOWN_RECORD',
		'CREATE INDEX IX_ISC_DR_CLN_CARD ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, DEVICE_CODE, PARK_ID, CARD_NO, OVER_TIME)'
	FROM DUAL
	UNION ALL
	SELECT
		'IX_ISC_DT_CLN_PERSON',
		'SMT_ISC_DEVICE_TASK',
		'CREATE INDEX IX_ISC_DT_CLN_PERSON ON SMT_ISC_DEVICE_TASK (ACTION, DEVICE_TYPE, DEVICE_CODE, SERVICE_TYPE, PERSON_ID, STATUS)'
	FROM DUAL
	UNION ALL
	SELECT
		'IX_ISC_DT_CLN_BADGE',
		'SMT_ISC_DEVICE_TASK',
		'CREATE INDEX IX_ISC_DT_CLN_BADGE ON SMT_ISC_DEVICE_TASK (ACTION, DEVICE_TYPE, DEVICE_CODE, SERVICE_TYPE, BADGE, STATUS)'
	FROM DUAL
	UNION ALL
	SELECT
		'IX_ISC_DT_CLN_CARD',
		'SMT_ISC_DEVICE_TASK',
		'CREATE INDEX IX_ISC_DT_CLN_CARD ON SMT_ISC_DEVICE_TASK (ACTION, DEVICE_TYPE, DEVICE_CODE, SERVICE_TYPE, CARD_NO, STATUS)'
	FROM DUAL
)
SELECT REQUIRED_INDEXES.INDEX_NAME, REQUIRED_INDEXES.TABLE_NAME, REQUIRED_INDEXES.DDL
FROM REQUIRED_INDEXES
WHERE NOT EXISTS (
	SELECT 1
	FROM USER_INDEXES EXISTING_INDEX
	WHERE EXISTING_INDEX.INDEX_NAME = REQUIRED_INDEXES.INDEX_NAME
	  AND EXISTING_INDEX.TABLE_NAME = REQUIRED_INDEXES.TABLE_NAME
)
ORDER BY REQUIRED_INDEXES.TABLE_NAME, REQUIRED_INDEXES.INDEX_NAME;

-- Step 3. Manual fallback. Uncomment and run only the missing indexes from Step 2.
-- CREATE INDEX IX_ISC_DR_CLN_BASE
-- ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, PARK_ID, OVER_TIME, DEVICE_CODE);

-- CREATE INDEX IX_ISC_DR_CLN_PERSON
-- ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, DEVICE_CODE, PARK_ID, PERSON_ID, OVER_TIME);

-- CREATE INDEX IX_ISC_DR_CLN_BADGE
-- ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, DEVICE_CODE, PARK_ID, BADGE, OVER_TIME);

-- CREATE INDEX IX_ISC_DR_CLN_CARD
-- ON SMT_ISC_DOWN_RECORD (DEVICE_TYPE, SERVICE_TYPE, DEVICE_CODE, PARK_ID, CARD_NO, OVER_TIME);

-- CREATE INDEX IX_ISC_DT_CLN_PERSON
-- ON SMT_ISC_DEVICE_TASK (ACTION, DEVICE_TYPE, DEVICE_CODE, SERVICE_TYPE, PERSON_ID, STATUS);

-- CREATE INDEX IX_ISC_DT_CLN_BADGE
-- ON SMT_ISC_DEVICE_TASK (ACTION, DEVICE_TYPE, DEVICE_CODE, SERVICE_TYPE, BADGE, STATUS);

-- CREATE INDEX IX_ISC_DT_CLN_CARD
-- ON SMT_ISC_DEVICE_TASK (ACTION, DEVICE_TYPE, DEVICE_CODE, SERVICE_TYPE, CARD_NO, STATUS);
