-- 手工数据库变更：人员海康 ISC 实体卡主数据。
-- 新代码将卡片保存到 SMT_ISC_STAFF_CARD，不再保存到 SMT_STAFF.ISC_CARD_NO。
-- 本功能不要在 SMT_STAFF 上新增 ISC 卡号字段。
-- Oracle 低版本不支持 CREATE TABLE IF NOT EXISTS，本脚本使用单个 PL/SQL 匿名块做存在性判断。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
	V_DUP_COUNT NUMBER;
	V_ACTIVE_KEY_INDEX_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE q'[
			CREATE TABLE SMT_ISC_STAFF_CARD (
				ID NUMBER(20) NOT NULL,
				STAFF_ID NUMBER(20) NOT NULL,
				BADGE VARCHAR2(64) NOT NULL,
				PARK_ID NUMBER(10) NOT NULL,
				PARK_NAME VARCHAR2(128),
				DISPATCHER_PARK_ID NUMBER(10) NOT NULL,
				DISPATCHER_PARK_NAME VARCHAR2(128),
				CARD_NO VARCHAR2(64) NOT NULL,
				DEL_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
				ACTIVE_KEY VARCHAR2(128),
				REMARK VARCHAR2(512),
				SYNC_STATUS NUMBER(3) DEFAULT 0,
				LAST_TASK_ID NUMBER(20),
				LAST_SYNC_CODE NUMBER(10),
				LAST_SYNC_REMARK VARCHAR2(512),
				LAST_SYNC_TIME DATE,
				CREATE_TIME DATE,
				UPDATE_TIME DATE,
				DELETE_TIME DATE,
				OPT_USER VARCHAR2(64),
				CONSTRAINT PK_SMT_ISC_STAFF_CARD PRIMARY KEY (ID)
			)
		]';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND COLUMN_NAME = 'ACTIVE_KEY';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD ACTIVE_KEY VARCHAR2(128)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND COLUMN_NAME = 'SYNC_STATUS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD SYNC_STATUS NUMBER(3)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND COLUMN_NAME = 'LAST_TASK_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD LAST_TASK_ID NUMBER(20)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND COLUMN_NAME = 'LAST_SYNC_CODE';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD LAST_SYNC_CODE NUMBER(10)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND COLUMN_NAME = 'LAST_SYNC_REMARK';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD LAST_SYNC_REMARK VARCHAR2(512)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND COLUMN_NAME = 'LAST_SYNC_TIME';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD LAST_SYNC_TIME DATE';
	END IF;

	EXECUTE IMMEDIATE q'[COMMENT ON TABLE SMT_ISC_STAFF_CARD IS '人员海康 ISC 实体卡主表']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.ID IS '主键']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.STAFF_ID IS '本系统人员 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.BADGE IS '员工工号 / ISC 工号']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.PARK_ID IS '本系统园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.PARK_NAME IS '本系统园区名称']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.DISPATCHER_PARK_ID IS '用于分发服务路由目标 ISC 平台的园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.DISPATCHER_PARK_NAME IS '分发服务路由园区名称']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.CARD_NO IS '海康 ISC 实体卡号；999 开头的 ISC 虚拟卡不入库']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.DEL_FLAG IS '软删除标记：0-有效，1-已删除']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.ACTIVE_KEY IS '有效记录唯一键；有效时为目标 ISC 园区 ID 和卡号组合，软删除后置空']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.REMARK IS '备注']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.SYNC_STATUS IS 'ISC同步状态：0-待同步，1-已同步，2-同步失败，3-本地取消']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.LAST_TASK_ID IS '最近一次ISC卡片同步任务ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.LAST_SYNC_CODE IS '最近一次ISC同步结果编码']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.LAST_SYNC_REMARK IS '最近一次ISC同步结果备注']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.LAST_SYNC_TIME IS '最近一次ISC同步结果时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.CREATE_TIME IS '创建时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.UPDATE_TIME IS '更新时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.DELETE_TIME IS '软删除时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_STAFF_CARD.OPT_USER IS '操作人账号']';

	EXECUTE IMMEDIATE q'[UPDATE SMT_ISC_STAFF_CARD SET ACTIVE_KEY = TO_CHAR(DISPATCHER_PARK_ID) || ':' || CARD_NO WHERE DEL_FLAG = 0]';
	EXECUTE IMMEDIATE 'UPDATE SMT_ISC_STAFF_CARD SET ACTIVE_KEY = NULL WHERE DEL_FLAG <> 0';
	EXECUTE IMMEDIATE q'[
		UPDATE SMT_ISC_STAFF_CARD
		SET SYNC_STATUS = 1
		WHERE DEL_FLAG = 0
		  AND SYNC_STATUS IS NULL
		  AND CARD_NO IS NOT NULL
		  AND REGEXP_LIKE(CARD_NO, '^[0-9A-Z]{8,20}$')
		  AND CARD_NO NOT LIKE '999%'
	]';
	EXECUTE IMMEDIATE 'UPDATE SMT_ISC_STAFF_CARD SET SYNC_STATUS = 3 WHERE DEL_FLAG <> 0 AND SYNC_STATUS IS NULL';
	EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD MODIFY SYNC_STATUS DEFAULT 0';

	EXECUTE IMMEDIATE q'[
		SELECT COUNT(1)
		FROM SMT_ISC_STAFF_CARD
		WHERE DEL_FLAG = 0
		  AND (
			CARD_NO IS NULL
			OR NOT REGEXP_LIKE(CARD_NO, '^[0-9A-Z]{8,20}$')
			OR CARD_NO LIKE '999%'
		  )
	]' INTO V_COUNT;
	IF V_COUNT > 0 THEN
		RAISE_APPLICATION_ERROR(-20004, 'SMT_ISC_STAFF_CARD 存在不符合海康ISC规则的有效卡号，请先执行 20260610_cleanup_invalid_isc_staff_cards.sql');
	END IF;

	EXECUTE IMMEDIATE q'[
		SELECT COUNT(1)
		FROM (
			SELECT ACTIVE_KEY
			FROM SMT_ISC_STAFF_CARD
			WHERE ACTIVE_KEY IS NOT NULL
			GROUP BY ACTIVE_KEY
			HAVING COUNT(1) > 1
		)
	]' INTO V_DUP_COUNT;
	IF V_DUP_COUNT > 0 THEN
		RAISE_APPLICATION_ERROR(-20002, 'SMT_ISC_STAFF_CARD 存在重复有效卡片，请先清理重复数据');
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_STAFF_CARD_ACTIVE'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT > 0 THEN
		SELECT COUNT(1) INTO V_ACTIVE_KEY_INDEX_COUNT
		FROM USER_IND_COLUMNS
		WHERE INDEX_NAME = 'UK_SMT_ISC_STAFF_CARD_ACTIVE'
		  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD'
		  AND COLUMN_NAME = 'ACTIVE_KEY';
		IF V_ACTIVE_KEY_INDEX_COUNT = 0 THEN
			EXECUTE IMMEDIATE 'DROP INDEX UK_SMT_ISC_STAFF_CARD_ACTIVE';
			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_SMT_ISC_STAFF_CARD_ACTIVE ON SMT_ISC_STAFF_CARD (ACTIVE_KEY)';
		END IF;
	ELSE
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_SMT_ISC_STAFF_CARD_ACTIVE ON SMT_ISC_STAFF_CARD (ACTIVE_KEY)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_CONSTRAINTS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND CONSTRAINT_NAME = 'CK_SMT_ISC_STAFF_CARD_SYNC';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_STAFF_CARD ADD CONSTRAINT CK_SMT_ISC_STAFF_CARD_SYNC CHECK (SYNC_STATUS IN (0, 1, 2, 3))';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_CONSTRAINTS
	WHERE TABLE_NAME = 'SMT_ISC_STAFF_CARD'
	  AND CONSTRAINT_NAME = 'CK_SMT_ISC_STAFF_CARD_NO';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE q'[ALTER TABLE SMT_ISC_STAFF_CARD ADD CONSTRAINT CK_SMT_ISC_STAFF_CARD_NO CHECK (
			DEL_FLAG <> 0 OR (
				CARD_NO IS NOT NULL
				AND REGEXP_LIKE(CARD_NO, '^[0-9A-Z]{8,20}$')
				AND CARD_NO NOT LIKE '999%'
			)
		)]';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_STAFF_CARD_STAFF'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_STAFF_CARD_STAFF ON SMT_ISC_STAFF_CARD (STAFF_ID, DEL_FLAG, CREATE_TIME)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_STAFF_CARD_BADGE'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_STAFF_CARD_BADGE ON SMT_ISC_STAFF_CARD (BADGE, DISPATCHER_PARK_ID, DEL_FLAG)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_STAFF_CARD_PARK'
	  AND TABLE_NAME = 'SMT_ISC_STAFF_CARD';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_STAFF_CARD_PARK ON SMT_ISC_STAFF_CARD (PARK_ID, DISPATCHER_PARK_ID, DEL_FLAG)';
	END IF;
END;
