-- 手工数据库回滚：海康 ISC 卡片资源同步任务。
-- 可重复执行：对象不存在时跳过。执行后会删除数据，请仅在回滚时整段执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_CARD_TASK_SOURCE'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SMT_ISC_CARD_TASK_SOURCE';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_CARD_TASK_CARD'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SMT_ISC_CARD_TASK_CARD';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_CARD_TASK_PENDING'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_SMT_ISC_CARD_TASK_PENDING';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_CARD_TASK_RUNNING'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX UK_SMT_ISC_CARD_TASK_RUNNING';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_CARD_TASK_ACTIVE'
	  AND TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX UK_SMT_ISC_CARD_TASK_ACTIVE';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_CARD_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP TABLE SMT_ISC_CARD_TASK';
	END IF;
END;
