-- 回滚脚本：删除保密权限微信推送失败重试计数列。
-- 目标模式：tech_platform。
-- 注意：须先回滚应用代码（实体仍有 msgRetryCount 字段时删列会导致 updateById 报 ORA-00904）。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_SECURITY_AUTH_APPLY'
	  AND COLUMN_NAME = 'MSG_RETRY_COUNT';
	IF V_COUNT = 1 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_SECURITY_AUTH_APPLY DROP COLUMN MSG_RETRY_COUNT';
		DBMS_OUTPUT.PUT_LINE('已删除 SMT_SECURITY_AUTH_APPLY.MSG_RETRY_COUNT 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_SECURITY_AUTH_APPLY.MSG_RETRY_COUNT 列不存在，跳过');
	END IF;
END;
