-- 能耗日汇总投影表。
-- 本脚本仅创建不存在的对象；若目标表已存在，部署前应由 DBA 核对其字段和约束是否符合本脚本。
-- 重复入队由后续服务先尝试唯一键去重插入，再仅对已存在行更新队列状态，避免并发首次入队产生重复主键。
-- 回滚仅删除被本发行 marker 明确记录为新建的表，marker 表作为审计记录永久保留。

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_RELEASE_MARKER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_RELEASE_MARKER (
                RELEASE_KEY VARCHAR2(64) NOT NULL,
                OBJECT_NAME VARCHAR2(30) NOT NULL,
                OBJECT_TYPE VARCHAR2(16) NOT NULL,
                CREATED_AT TIMESTAMP(6) NOT NULL,
                ROLLED_BACK_AT TIMESTAMP(6),
                CONSTRAINT PK_SMT_ENERGY_REL_MARKER PRIMARY KEY (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PARK_DAY_LOCK';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_PARK_DAY_LOCK (
                PARK_ID NUMBER(20) NOT NULL,
                STAT_DATE DATE NOT NULL,
                RESOURCE_TYPE VARCHAR2(32) NOT NULL,
                UNIT VARCHAR2(32) NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_PD_LOCK PRIMARY KEY (PARK_ID, STAT_DATE, RESOURCE_TYPE, UNIT)
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_PARK_DAY_LOCK' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_METER_DAY_LOCK';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_METER_DAY_LOCK (
                METER_SOURCE VARCHAR2(16) NOT NULL,
                METER_ID NUMBER(20) NOT NULL,
                STAT_DATE DATE NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_MD_LOCK PRIMARY KEY (METER_SOURCE, METER_ID, STAT_DATE)
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_METER_DAY_LOCK' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_INGESTION_LEDGER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_INGESTION_LEDGER (
                ID NUMBER(20) NOT NULL,
                SOURCE_EVENT_ID VARCHAR2(128) NOT NULL,
                EVENT_TYPE VARCHAR2(32) NOT NULL,
                PARK_ID NUMBER(20),
                METER_SOURCE VARCHAR2(16),
                METER_ID NUMBER(20),
                EVENT_TIME TIMESTAMP(6),
                PAYLOAD_HASH VARCHAR2(64) NOT NULL,
                EVENT_PAYLOAD CLOB,
                INGESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_LEDGER PRIMARY KEY (ID),
                CONSTRAINT UK_SMT_ENERGY_LEDGER_EVENT UNIQUE (SOURCE_EVENT_ID)
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_INGESTION_LEDGER' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PROJECTION_QUEUE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_PROJECTION_QUEUE (
                ID NUMBER(20) NOT NULL,
                METER_SOURCE VARCHAR2(16) NOT NULL,
                METER_ID NUMBER(20) NOT NULL,
                STAT_DATE DATE NOT NULL,
                QUEUE_STATUS VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
                REQUEST_COUNT NUMBER(10) DEFAULT 1 NOT NULL,
                LAST_REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                PROCESSED_AT TIMESTAMP(6),
                LEASE_TOKEN VARCHAR2(64),
                RETRY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
                NEXT_RETRY_AT TIMESTAMP(6),
                LAST_ERROR VARCHAR2(1000),
                CONSTRAINT PK_SMT_ENERGY_QUEUE PRIMARY KEY (ID),
                CONSTRAINT UK_SMT_ENERGY_QUEUE_METER_DAY UNIQUE (METER_SOURCE, METER_ID, STAT_DATE),
                CONSTRAINT CK_SMT_ENERGY_QUEUE_SOURCE CHECK (METER_SOURCE IN ('ELE', 'WATER'))
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_PROJECTION_QUEUE' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

-- 兼容本发行早期已建表但尚未含租约令牌的环境；列存在时不重复执行 ALTER。
DECLARE
    v_table_count NUMBER;
    v_column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PROJECTION_QUEUE';
    IF v_table_count = 1 THEN
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS
            WHERE TABLE_NAME = 'SMT_ENERGY_PROJECTION_QUEUE' AND COLUMN_NAME = 'LEASE_TOKEN';
        IF v_column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ENERGY_PROJECTION_QUEUE ADD (LEASE_TOKEN VARCHAR2(64))'; END IF;
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ENERGY_PROJECTION_QUEUE' AND COLUMN_NAME = 'RETRY_COUNT';
        IF v_column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ENERGY_PROJECTION_QUEUE ADD (RETRY_COUNT NUMBER(10) DEFAULT 0 NOT NULL)'; END IF;
        SELECT COUNT(*) INTO v_column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SMT_ENERGY_PROJECTION_QUEUE' AND COLUMN_NAME = 'NEXT_RETRY_AT';
        IF v_column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SMT_ENERGY_PROJECTION_QUEUE ADD (NEXT_RETRY_AT TIMESTAMP(6))'; END IF;
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_METER_SCOPE_RULE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_METER_SCOPE_RULE (
                ID NUMBER(20) NOT NULL,
                PARK_ID NUMBER(20) NOT NULL,
                METER_SOURCE VARCHAR2(16) NOT NULL,
                METER_ID NUMBER(20) NOT NULL,
                RESOURCE_TYPE VARCHAR2(32) NOT NULL,
                UNIT VARCHAR2(32) NOT NULL,
                EFFECTIVE_START_DATE DATE NOT NULL,
                EFFECTIVE_END_DATE DATE,
                INCLUDE_FLAG NUMBER(1) NOT NULL,
                METER_GROUP_ID NUMBER(20),
                PARENT_METER_ID NUMBER(20),
                RULE_VERSION NUMBER(10) NOT NULL,
                REASON VARCHAR2(500),
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_RULE PRIMARY KEY (ID),
                CONSTRAINT UK_SMT_ENERGY_RULE_VERSION UNIQUE (METER_SOURCE, METER_ID, EFFECTIVE_START_DATE, RULE_VERSION),
                CONSTRAINT CK_SMT_ENERGY_RULE_SOURCE CHECK (METER_SOURCE IN ('ELE', 'WATER')),
                CONSTRAINT CK_SMT_ENERGY_RULE_INCLUDE CHECK (INCLUDE_FLAG IN (0, 1)),
                CONSTRAINT CK_SMT_ENERGY_RULE_DATES CHECK (EFFECTIVE_END_DATE IS NULL OR EFFECTIVE_END_DATE >= EFFECTIVE_START_DATE)
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_METER_SCOPE_RULE' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_METER_DAY_FACT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_METER_DAY_FACT (
                ID NUMBER(20) NOT NULL,
                PARK_ID NUMBER(20) NOT NULL,
                METER_SOURCE VARCHAR2(16) NOT NULL,
                METER_ID NUMBER(20) NOT NULL,
                RESOURCE_TYPE VARCHAR2(32) NOT NULL,
                UNIT VARCHAR2(32) NOT NULL,
                STAT_DATE DATE NOT NULL,
                DAY_START_HISTORY_ID NUMBER(20),
                DAY_START_TIME TIMESTAMP(6),
                DAY_START_READING NUMBER(20, 6),
                DAY_END_HISTORY_ID NUMBER(20),
                DAY_END_TIME TIMESTAMP(6),
                DAY_END_READING NUMBER(20, 6),
                MULTIPLIER_SNAPSHOT NUMBER(20, 6) NOT NULL,
                RAW_DELTA NUMBER(20, 6),
                USAGE_VALUE NUMBER(20, 6),
                QUALITY_CODE VARCHAR2(32) NOT NULL,
                QUALITY_DETAIL VARCHAR2(1000),
                SOURCE_HASH VARCHAR2(64) NOT NULL,
                CALCULATED_AT TIMESTAMP(6) NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_FACT PRIMARY KEY (ID),
                CONSTRAINT UK_SMT_ENERGY_FACT_METER_DAY UNIQUE (METER_SOURCE, METER_ID, STAT_DATE),
                CONSTRAINT CK_SMT_ENERGY_FACT_SOURCE CHECK (METER_SOURCE IN ('ELE', 'WATER'))
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_METER_DAY_FACT' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PARK_DAY_ITEM';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_PARK_DAY_ITEM (
                ID NUMBER(20) NOT NULL,
                PARK_ID NUMBER(20) NOT NULL,
                STAT_DATE DATE NOT NULL,
                RESOURCE_TYPE VARCHAR2(32) NOT NULL,
                UNIT VARCHAR2(32) NOT NULL,
                METER_SOURCE VARCHAR2(16) NOT NULL,
                METER_ID NUMBER(20) NOT NULL,
                METER_DAY_FACT_ID NUMBER(20) NOT NULL,
                USAGE_VALUE NUMBER(20, 6),
                RULE_ID NUMBER(20),
                RULE_VERSION NUMBER(10),
                RULE_DECISION VARCHAR2(16) NOT NULL,
                RULE_REASON VARCHAR2(500),
                CALCULATED_AT TIMESTAMP(6) NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_ITEM PRIMARY KEY (ID),
                CONSTRAINT UK_SMT_ENERGY_ITEM_METER_DAY UNIQUE (PARK_ID, STAT_DATE, RESOURCE_TYPE, UNIT, METER_SOURCE, METER_ID),
                CONSTRAINT CK_SMT_ENERGY_ITEM_SOURCE CHECK (METER_SOURCE IN ('ELE', 'WATER'))
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_PARK_DAY_ITEM' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ENERGY_PARK_DAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE SMT_ENERGY_PARK_DAY (
                ID NUMBER(20) NOT NULL,
                PARK_ID NUMBER(20) NOT NULL,
                STAT_DATE DATE NOT NULL,
                RESOURCE_TYPE VARCHAR2(32) NOT NULL,
                UNIT VARCHAR2(32) NOT NULL,
                USAGE_VALUE NUMBER(20, 6),
                METER_COUNT NUMBER(10) NOT NULL,
                QUALITY_SUMMARY VARCHAR2(1000),
                CALCULATED_AT TIMESTAMP(6) NOT NULL,
                CONSTRAINT PK_SMT_ENERGY_PARK_DAY PRIMARY KEY (ID),
                CONSTRAINT UK_SMT_ENERGY_PARK_DAY UNIQUE (PARK_ID, STAT_DATE, RESOURCE_TYPE, UNIT)
            )
        ]';
        MERGE INTO SMT_ENERGY_RELEASE_MARKER target
        USING (SELECT '20260805_ENERGY_PROJECTION' RELEASE_KEY, 'SMT_ENERGY_PARK_DAY' OBJECT_NAME, 'TABLE' OBJECT_TYPE FROM DUAL) source
        ON (target.RELEASE_KEY = source.RELEASE_KEY AND target.OBJECT_NAME = source.OBJECT_NAME AND target.OBJECT_TYPE = source.OBJECT_TYPE)
        WHEN MATCHED THEN UPDATE SET target.CREATED_AT = SYSTIMESTAMP, target.ROLLED_BACK_AT = NULL
        WHEN NOT MATCHED THEN INSERT (RELEASE_KEY, OBJECT_NAME, OBJECT_TYPE, CREATED_AT, ROLLED_BACK_AT)
            VALUES (source.RELEASE_KEY, source.OBJECT_NAME, source.OBJECT_TYPE, SYSTIMESTAMP, NULL);
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SMT_ENERGY_LEDGER_TIME';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ENERGY_LEDGER_TIME ON SMT_ENERGY_INGESTION_LEDGER (METER_SOURCE, METER_ID, EVENT_TIME)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SMT_ENERGY_QUEUE_STATUS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ENERGY_QUEUE_STATUS ON SMT_ENERGY_PROJECTION_QUEUE (QUEUE_STATUS, LAST_REQUESTED_AT)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SMT_ENERGY_RULE_LOOKUP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ENERGY_RULE_LOOKUP ON SMT_ENERGY_METER_SCOPE_RULE (METER_SOURCE, METER_ID, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SMT_ENERGY_FACT_PARK_DAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ENERGY_FACT_PARK_DAY ON SMT_ENERGY_METER_DAY_FACT (PARK_ID, STAT_DATE, RESOURCE_TYPE, UNIT)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SMT_ENERGY_ITEM_PARK_DAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ENERGY_ITEM_PARK_DAY ON SMT_ENERGY_PARK_DAY_ITEM (PARK_ID, STAT_DATE, RESOURCE_TYPE, UNIT)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_SMT_ENERGY_PARK_DAY_DATE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ENERGY_PARK_DAY_DATE ON SMT_ENERGY_PARK_DAY (STAT_DATE, RESOURCE_TYPE, UNIT)';
    END IF;
END;
/
