-- 回滚脚本：撤销 2026-07-01-isc-batch-model.sql 的批次模型变更。
-- 删除相关字段和索引。
-- Oracle 低版本不支持 CREATE TABLE IF NOT EXISTS，本脚本使用 PL/SQL 匿名块做存在性判断。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
BEGIN
	-- 删除索引 IDX_ISC_TASK_APPLY_BATCH
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_ISC_TASK_APPLY_BATCH'
	  AND TABLE_NAME = 'SMT_ISC_DEVICE_TASK';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX IDX_ISC_TASK_APPLY_BATCH';
		DBMS_OUTPUT.PUT_LINE('已删除索引 IDX_ISC_TASK_APPLY_BATCH');
	ELSE
		DBMS_OUTPUT.PUT_LINE('索引 IDX_ISC_TASK_APPLY_BATCH 不存在，跳过');
	END IF;

	-- 删除 smt_isc_device_task 表中 apply_id 列
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'APPLY_ID';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN APPLY_ID';
		DBMS_OUTPUT.PUT_LINE('已删除 SMT_ISC_DEVICE_TASK.APPLY_ID 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_ISC_DEVICE_TASK.APPLY_ID 列不存在，跳过');
	END IF;

	-- 删除 smt_isc_device_task 表中 batch_id 列
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_DEVICE_TASK'
	  AND COLUMN_NAME = 'BATCH_ID';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_DEVICE_TASK DROP COLUMN BATCH_ID';
		DBMS_OUTPUT.PUT_LINE('已删除 SMT_ISC_DEVICE_TASK.BATCH_ID 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_ISC_DEVICE_TASK.BATCH_ID 列不存在，跳过');
	END IF;

	-- 删除 smt_admittance_apply 表中 isc_submit_batch 列
	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ADMITTANCE_APPLY'
	  AND COLUMN_NAME = 'ISC_SUBMIT_BATCH';
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ADMITTANCE_APPLY DROP COLUMN ISC_SUBMIT_BATCH';
		DBMS_OUTPUT.PUT_LINE('已删除 SMT_ADMITTANCE_APPLY.ISC_SUBMIT_BATCH 列');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SMT_ADMITTANCE_APPLY.ISC_SUBMIT_BATCH 列不存在，跳过');
	END IF;

	DBMS_OUTPUT.PUT_LINE('批次模型回滚完成');
END;
