-- 手工数据库变更：海康 ISC 园区绑定配置。
-- Oracle 低版本不支持 CREATE TABLE IF NOT EXISTS，本脚本使用单个 PL/SQL 匿名块做存在性判断。
-- 执行时请整段执行本文件，不要按分号逐句执行。

DECLARE
	V_COUNT NUMBER;
	V_DUP_COUNT NUMBER;
	V_ACTIVE_KEY_INDEX_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'SMT_ISC_PARK_CONFIG';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE q'[
			CREATE TABLE SMT_ISC_PARK_CONFIG (
				ID NUMBER(20) NOT NULL,
				PARK_ID NUMBER(10) NOT NULL,
				PARK_NAME VARCHAR2(128),
				DISPATCHER_PARK_ID NUMBER(10) NOT NULL,
				DISPATCHER_PARK_NAME VARCHAR2(128),
				CARD_SYNC_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
				DEL_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
				ACTIVE_KEY VARCHAR2(64),
				REMARK VARCHAR2(512),
				CREATE_TIME DATE DEFAULT SYSDATE,
				UPDATE_TIME DATE,
				OPT_USER VARCHAR2(64),
				CONSTRAINT PK_SMT_ISC_PARK_CONFIG PRIMARY KEY (ID)
			)
		]';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'SMT_ISC_PARK_CONFIG'
	  AND COLUMN_NAME = 'ACTIVE_KEY';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE SMT_ISC_PARK_CONFIG ADD ACTIVE_KEY VARCHAR2(64)';
	END IF;

	EXECUTE IMMEDIATE q'[COMMENT ON TABLE SMT_ISC_PARK_CONFIG IS '海康 ISC 园区绑定配置表']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.ID IS '主键']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.PARK_ID IS '本系统园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.PARK_NAME IS '本系统园区名称']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.DISPATCHER_PARK_ID IS '用于分发服务路由目标 ISC 平台的园区 ID']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.DISPATCHER_PARK_NAME IS '分发服务路由园区名称']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.CARD_SYNC_ENABLED IS '卡片同步开关：1-启用，0-停用']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.DEL_FLAG IS '软删除标记：0-有效，1-已删除']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.ACTIVE_KEY IS '有效记录唯一键；有效时为园区 ID，软删除后置空']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.REMARK IS '备注']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.CREATE_TIME IS '创建时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.UPDATE_TIME IS '更新时间']';
	EXECUTE IMMEDIATE q'[COMMENT ON COLUMN SMT_ISC_PARK_CONFIG.OPT_USER IS '操作人账号']';

	EXECUTE IMMEDIATE 'UPDATE SMT_ISC_PARK_CONFIG SET ACTIVE_KEY = TO_CHAR(PARK_ID) WHERE DEL_FLAG = 0';
	EXECUTE IMMEDIATE 'UPDATE SMT_ISC_PARK_CONFIG SET ACTIVE_KEY = NULL WHERE DEL_FLAG <> 0';

	EXECUTE IMMEDIATE q'[
		SELECT COUNT(1)
		FROM (
			SELECT ACTIVE_KEY
			FROM SMT_ISC_PARK_CONFIG
			WHERE ACTIVE_KEY IS NOT NULL
			GROUP BY ACTIVE_KEY
			HAVING COUNT(1) > 1
		)
	]' INTO V_DUP_COUNT;
	IF V_DUP_COUNT > 0 THEN
		RAISE_APPLICATION_ERROR(-20001, 'SMT_ISC_PARK_CONFIG 存在重复有效园区配置，请先清理重复数据');
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'UK_SMT_ISC_PARK_CONFIG_PARK'
	  AND TABLE_NAME = 'SMT_ISC_PARK_CONFIG';
	IF V_COUNT > 0 THEN
		SELECT COUNT(1) INTO V_ACTIVE_KEY_INDEX_COUNT
		FROM USER_IND_COLUMNS
		WHERE INDEX_NAME = 'UK_SMT_ISC_PARK_CONFIG_PARK'
		  AND TABLE_NAME = 'SMT_ISC_PARK_CONFIG'
		  AND COLUMN_NAME = 'ACTIVE_KEY';
		IF V_ACTIVE_KEY_INDEX_COUNT = 0 THEN
			EXECUTE IMMEDIATE 'DROP INDEX UK_SMT_ISC_PARK_CONFIG_PARK';
			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_SMT_ISC_PARK_CONFIG_PARK ON SMT_ISC_PARK_CONFIG (ACTIVE_KEY)';
		END IF;
	ELSE
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_SMT_ISC_PARK_CONFIG_PARK ON SMT_ISC_PARK_CONFIG (ACTIVE_KEY)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_PARK_CONFIG_SYNC'
	  AND TABLE_NAME = 'SMT_ISC_PARK_CONFIG';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_PARK_CONFIG_SYNC ON SMT_ISC_PARK_CONFIG (PARK_ID, CARD_SYNC_ENABLED, DEL_FLAG)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM USER_INDEXES
	WHERE INDEX_NAME = 'IDX_SMT_ISC_PARK_CONFIG_TARGET'
	  AND TABLE_NAME = 'SMT_ISC_PARK_CONFIG';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX IDX_SMT_ISC_PARK_CONFIG_TARGET ON SMT_ISC_PARK_CONFIG (DISPATCHER_PARK_ID, CARD_SYNC_ENABLED, DEL_FLAG)';
	END IF;
END;
