-- 仅本机独立合成验收；执行前必须核 PHASE 为原42列且两列均不存在，禁止盲重跑。
ALTER TABLE SMT_AUTH_TRANSPORT_PHASE ADD CREDENTIAL_VERSION NUMBER(10);
ALTER TABLE SMT_AUTH_TRANSPORT_PHASE ADD CREDENTIAL_SNAPSHOT CLOB;
CREATE TABLE SMT_AUTH_DIRECT_CLAIM (
 ID VARCHAR2(64 BYTE) NOT NULL,
 DEVICE_ID VARCHAR2(128 BYTE) NOT NULL,
 KEY_KIND VARCHAR2(16 BYTE) NOT NULL,
 KEY_VALUE VARCHAR2(256 BYTE) NOT NULL,
 SUBJECT_TYPE VARCHAR2(32 BYTE) NOT NULL,
 SUBJECT_ID VARCHAR2(128 BYTE) NOT NULL,
 PARK_ID NUMBER(10) NOT NULL,
 INSTANCE_ID VARCHAR2(128 BYTE) NOT NULL,
 RESOURCE_ID VARCHAR2(64 BYTE) NOT NULL,
 WIRE_HASH VARCHAR2(64 BYTE) NOT NULL,
 FIRST_PHASE_ID NUMBER(19) NOT NULL,
 PROOF_KIND VARCHAR2(32 BYTE) NOT NULL,
 CREATE_TIME TIMESTAMP NOT NULL,
 CONSTRAINT PK_AUTH_DIRECT_CLAIM PRIMARY KEY (ID),
 CONSTRAINT UK_AUTH_DIRECT_CLAIM UNIQUE (DEVICE_ID,KEY_KIND,KEY_VALUE),
 CONSTRAINT CK_AUTH_DIRECT_KEY CHECK (KEY_KIND IN ('CARD_NO','PLATE')),
 CONSTRAINT CK_AUTH_DIRECT_PROOF CHECK (PROOF_KIND IN ('PHASE_INTENT','PHASE_HISTORY')),
 CONSTRAINT FK_AUTH_DIRECT_PHASE FOREIGN KEY (FIRST_PHASE_ID) REFERENCES SMT_AUTH_TRANSPORT_PHASE(ID)
);
CREATE INDEX IX_AUTH_DIRECT_PHASE ON SMT_AUTH_DIRECT_CLAIM(FIRST_PHASE_ID);
CREATE INDEX IX_AUTH_DIRECT_REVIEW ON SMT_AUTH_DIRECT_CLAIM(PARK_ID,ID);
