-- 仅本机合成验证；生产须按发布流程迁移，既有历史不能当作无首建证据。
CREATE TABLE SMT_AUTH_PERSON_OWNER (
 ID VARCHAR2(64) NOT NULL, INSTANCE_ID VARCHAR2(128) NOT NULL,
 SUBJECT_TYPE VARCHAR2(32) NOT NULL,SUBJECT_ID VARCHAR2(128) NOT NULL,
 OPERATION_KEY VARCHAR2(128) NOT NULL,IDENTITY_HASH VARCHAR2(64) NOT NULL,IDENTITY_CANONICAL VARCHAR2(2048 CHAR) NOT NULL,
 ORIGIN_PARK NUMBER(10) NOT NULL,OWNER_PHASE_ID NUMBER(19),OWNER_TOKEN VARCHAR2(128) NOT NULL,
 STATE VARCHAR2(32) NOT NULL,REQUEST_KEY VARCHAR2(64),PERSON_ID VARCHAR2(128),REASON VARCHAR2(128),CREATE_TIME TIMESTAMP,UPDATE_TIME TIMESTAMP,
 CONSTRAINT PK_AUTH_PERSON_OWNER PRIMARY KEY(ID),
 CONSTRAINT UK_AUTH_PERSON_SUBJECT UNIQUE(INSTANCE_ID,SUBJECT_TYPE,SUBJECT_ID),
 CONSTRAINT UK_AUTH_PERSON_PHASE UNIQUE(OWNER_PHASE_ID),
 CONSTRAINT FK_AUTH_PERSON_PHASE FOREIGN KEY(OWNER_PHASE_ID) REFERENCES SMT_AUTH_TRANSPORT_PHASE(ID)
);
CREATE INDEX IX_AUTH_PERSON_REVIEW ON SMT_AUTH_PERSON_OWNER(INSTANCE_ID,STATE,ID);
CREATE INDEX IX_AUTH_PERSON_HISTORY ON SMT_AUTH_TRANSPORT_PHASE(INSTANCE_ID,SUBJECT_TYPE,SUBJECT_ID,PHASE,ID);

CREATE INDEX IX_AUTH_PERSON_REVIEW_TIME ON SMT_AUTH_PERSON_OWNER(INSTANCE_ID,STATE,UPDATE_TIME,ID);
