-- 仅用于本机临时 Oracle 合成验证；不删除或重建现有表。
-- 普通DEFAULT仅兼容旧员工SQL省略新增列；新通用SQL显式NULL仍由NOT NULL拒绝，不用DEFAULT ON NULL。
CREATE TABLE SMT_AUTH_SELECTION_SOURCE (
 BATCH_ID NUMBER(19) NOT NULL,
 ORDINAL NUMBER(19) NOT NULL,
 OPERATION_KEY VARCHAR2(100) NOT NULL,
 PARK_ID NUMBER(10) NOT NULL,
 SUBJECT_ID VARCHAR2(256 BYTE) NOT NULL,
 AUTH_ID VARCHAR2(128 BYTE),
 STABLE_KEY VARCHAR2(300) NOT NULL,
 SOURCE_ROW_ID VARCHAR2(400) NOT NULL,
 FINGERPRINT VARCHAR2(64) NOT NULL,
 DESIRED_ACTION VARCHAR2(10) NOT NULL,
 IMAGE_ID VARCHAR2(256),
 PERSON_SNAPSHOT VARCHAR2(4000 CHAR),
 BADGE VARCHAR2(512),
 STATE VARCHAR2(20) NOT NULL,
 VERIFICATION_REASON VARCHAR2(512),
 OLD_ID NUMBER(10),
 OLD_CREATE_TIME TIMESTAMP(6),
 OLD_START_TIME TIMESTAMP(6),
 OLD_END_TIME TIMESTAMP(6),
 OLD_AUTH_TYPE NUMBER(10),
 NEW_CREATE_TIME TIMESTAMP(6),
 NEW_START_TIME TIMESTAMP(6),
 NEW_END_TIME TIMESTAMP(6),
 NEW_AUTH_TYPE NUMBER(10),
 SOURCE_COORD_ID VARCHAR2(64),
 SOURCE_GENERATION NUMBER(19),
 SOURCE_KIND VARCHAR2(64 BYTE) DEFAULT 'STAFF_AUTH' NOT NULL,
 SUBJECT_TYPE VARCHAR2(64 BYTE) DEFAULT 'STAFF' NOT NULL,
 SNAPSHOT_VERSION NUMBER(10) DEFAULT 0 NOT NULL,
 BUSINESS_SNAPSHOT CLOB,
 PARENT_KIND VARCHAR2(64 BYTE),
 PARENT_ROW_ID VARCHAR2(128 BYTE),
 CONSTRAINT PK_AUTH_SEL_SOURCE PRIMARY KEY(BATCH_ID,ORDINAL),
 CONSTRAINT UK_AUTH_SEL_STABLE UNIQUE(BATCH_ID,PARK_ID,SOURCE_KIND,STABLE_KEY)
);
CREATE INDEX IX_AUTH_SEL_PENDING ON SMT_AUTH_SELECTION_SOURCE(PARK_ID,SUBJECT_TYPE,SUBJECT_ID,STATE,AUTH_ID);
CREATE INDEX IX_AUTH_SEL_OPERATION ON SMT_AUTH_SELECTION_SOURCE(OPERATION_KEY);
CREATE UNIQUE INDEX UK_AUTH_SEL_COORD ON SMT_AUTH_SELECTION_SOURCE(SOURCE_COORD_ID,SOURCE_GENERATION);
CREATE TABLE SMT_AUTH_SELECTION_RESOURCE (
 BATCH_ID NUMBER(19) NOT NULL,
 ORDINAL NUMBER(19) NOT NULL,
 SOURCE_ORDINAL NUMBER(19) NOT NULL,
 PARK_ID NUMBER(10) NOT NULL,
 SUBJECT_ID VARCHAR2(256 BYTE) NOT NULL,
 DEVICE_ID VARCHAR2(128) NOT NULL,
 ACCESS_TYPE VARCHAR2(16) NOT NULL,
 RESOURCE_TYPE VARCHAR2(32) NOT NULL,
 RESOURCE_ID VARCHAR2(256) NOT NULL,
 SERVICE_TYPE VARCHAR2(64) NOT NULL,
 CREDENTIAL_CHANNEL VARCHAR2(64) NOT NULL,
 PARTICIPATION VARCHAR2(16) NOT NULL,
 VALID_FROM TIMESTAMP(6),
 VALID_TO TIMESTAMP(6),
 RESOURCE_COORD_ID VARCHAR2(64),
 SUBJECT_TYPE VARCHAR2(64 BYTE) DEFAULT 'STAFF' NOT NULL,
 CREDENTIAL_VERSION NUMBER(10) DEFAULT 0 NOT NULL,
 CREDENTIAL_SNAPSHOT CLOB,
 CONSTRAINT PK_AUTH_SEL_RESOURCE PRIMARY KEY(BATCH_ID,ORDINAL),
 CONSTRAINT FK_AUTH_SEL_RESOURCE FOREIGN KEY(BATCH_ID,SOURCE_ORDINAL) REFERENCES SMT_AUTH_SELECTION_SOURCE(BATCH_ID,ORDINAL)
);
CREATE INDEX IX_AUTH_SEL_LANE ON SMT_AUTH_SELECTION_RESOURCE(BATCH_ID,RESOURCE_COORD_ID);
CREATE INDEX IX_AUTH_SEL_AUTH ON SMT_AUTH_SELECTION_SOURCE(PARK_ID,SOURCE_KIND,AUTH_ID,STATE);
CREATE INDEX IX_AUTH_SEL_STABLE_STATE ON SMT_AUTH_SELECTION_SOURCE(PARK_ID,SOURCE_KIND,STABLE_KEY,STATE);
