-- 仅本机合成验收；生产发布需要正式迁移及旧数据接管验收。
CREATE TABLE SMT_AUTH_TRANSPORT_PHASE (
 ID NUMBER(19) NOT NULL,
 TARGET_ID NUMBER(19) NOT NULL,
 ATTEMPT_ID NUMBER(19) NOT NULL,
 ATTEMPT_NO NUMBER(10),
 LEASE_TOKEN VARCHAR2(128),
 SOURCE_ID VARCHAR2(64),
 SOURCE_GENERATION NUMBER(19),
 RESOURCE_ID VARCHAR2(64),
 RESOURCE_GENERATION NUMBER(19),
 REQUEST_ID NUMBER(19),
 PARK_ID NUMBER(10) NOT NULL,
 INSTANCE_ID VARCHAR2(128) NOT NULL,
 ACCESS_TYPE VARCHAR2(16) NOT NULL,
 PHASE VARCHAR2(32) NOT NULL,
 STATE VARCHAR2(32) NOT NULL,
 TASK_ID VARCHAR2(64) NOT NULL,
 SERIAL_NO VARCHAR2(64),
 REQUEST_KEY VARCHAR2(64),
 EXTERNAL_ID VARCHAR2(128),
 ERROR_CODE VARCHAR2(128),
 DEVICE_ID VARCHAR2(128),
 SUBJECT_TYPE VARCHAR2(32),
 SUBJECT_ID VARCHAR2(128),
 ACTION VARCHAR2(16),
 RESOURCE_TYPE VARCHAR2(32),
 SERVICE_TYPE VARCHAR2(32),
 CREDENTIAL_CHANNEL VARCHAR2(64),
 CARD_NO VARCHAR2(128),
 BADGE VARCHAR2(128),
 PERSON_ID VARCHAR2(128),
 IMAGE_ID VARCHAR2(128),
 START_TIME NUMBER(19),
 OVER_TIME NUMBER(19),
 CHANNEL_NO NUMBER(10),
 PAGE_NO NUMBER(10),
 CREATE_TIME TIMESTAMP,
 UPDATE_TIME TIMESTAMP,
 PERSON_SNAPSHOT CLOB, ORG_INDEX_CODE VARCHAR2(128),
 PERSON_OPERATION_KEY VARCHAR2(128), PERSON_IDENTITY_HASH VARCHAR2(64), PERSON_PROOF_PHASE_ID NUMBER(19),
 CONSTRAINT PK_AUTH_TRANSPORT_PHASE PRIMARY KEY(ID),
 CONSTRAINT UK_AUTH_TRANSPORT_PHASE UNIQUE(ATTEMPT_ID,PHASE)
);
CREATE INDEX IX_AUTH_TRANSPORT_SCAN ON SMT_AUTH_TRANSPORT_PHASE(PARK_ID,INSTANCE_ID,PHASE,STATE,ID);
CREATE INDEX IX_AUTH_TRANSPORT_TASK ON SMT_AUTH_TRANSPORT_PHASE(ACCESS_TYPE,TASK_ID);
CREATE INDEX IX_AUTH_TRANSPORT_GROUP ON SMT_AUTH_TRANSPORT_PHASE(PARK_ID,INSTANCE_ID,REQUEST_KEY,PHASE);
CREATE TABLE SMT_AUTH_TRANSPORT_REVIEW (
 ID VARCHAR2(64) PRIMARY KEY, PARK_ID NUMBER(10), ACCESS_TYPE VARCHAR2(32), DEVICE_ID VARCHAR2(128),
 TASK_KEY VARCHAR2(128), REASON VARCHAR2(128), STATE VARCHAR2(32), CREATE_TIME TIMESTAMP
);
CREATE INDEX IX_AUTH_TRANSPORT_REVIEW ON SMT_AUTH_TRANSPORT_REVIEW(PARK_ID,ID);

-- 同一接入实例的外部人员只可由一个本地主体占有，跨进程首次绑定由唯一键仲裁。
CREATE TABLE SMT_AUTH_TRANSPORT_IDENTITY (
 INSTANCE_ID VARCHAR2(128) NOT NULL, PERSON_ID VARCHAR2(128) NOT NULL,
 SUBJECT_TYPE VARCHAR2(32) NOT NULL, SUBJECT_ID VARCHAR2(128) NOT NULL,
 PARK_ID NUMBER(10) NOT NULL, PHASE_ID NUMBER(19) NOT NULL, CREATE_TIME TIMESTAMP,
 CONSTRAINT PK_AUTH_TRANSPORT_IDENTITY PRIMARY KEY(INSTANCE_ID,PERSON_ID)
);
