-- 仅供本机SMART_AUTH_TEST新增缺失表的合成候选；未授权执行，不重建既有表。
-- 真实生产类型/索引须另核metadata；以下为本core查询所需列，不代表全PB入口fixture。
CREATE TABLE SMT_VISITOR (
 ID NUMBER(19) PRIMARY KEY,PARK_ID NUMBER(10),CREATE_TIME TIMESTAMP(6),START_TIME TIMESTAMP(6),END_TIME TIMESTAMP(6),
 CAUSE NUMBER(10),CERT_TYPE NUMBER(10),CERT_NO VARCHAR2(256 CHAR),VISITOR_NAME VARCHAR2(256 CHAR),VISITOR_PHOTO_ID VARCHAR2(256 CHAR),
 IS_VEHICLE NUMBER(10),VEHICLE_PLATE VARCHAR2(128 CHAR),PROCESS_ID VARCHAR2(256 CHAR),RECEPTIONIST_BADGE VARCHAR2(256 CHAR),PROMOTER_BADGE VARCHAR2(256 CHAR),STATUS NUMBER(10),DEL_FLAG NUMBER(10)
);
CREATE TABLE SMT_FELLOW_VISITOR (
 ID NUMBER(19) PRIMARY KEY,VISITOR_ID NUMBER(19),CERT_TYPE NUMBER(10),CERT_NO VARCHAR2(256 CHAR),FELLOW_NAME VARCHAR2(256 CHAR),FELLOW_PHOTO_ID VARCHAR2(256 CHAR)
);
CREATE INDEX IX_VISITOR_CORE_FELLOW ON SMT_FELLOW_VISITOR(VISITOR_ID,ID);
CREATE INDEX IX_VISITOR_CORE_EXPIRY ON SMT_VISITOR(PARK_ID,STATUS,END_TIME,ID);
-- 保留能造孤儿历史反例的能力，不以测试FK掩盖业务归属门禁。
CREATE TABLE SMT_SNAP_PERSON (
 ID NUMBER(10) PRIMARY KEY,PARK_ID NUMBER(10),DEVICE_ID VARCHAR2(128 CHAR),PERSON_ID NUMBER(19),PERSON_TYPE NUMBER(10),EVENT_TYPE NUMBER(10),SNAP_TIME TIMESTAMP(6)
);
CREATE TABLE SMT_SNAP_VEHICLE (
 ID NUMBER(19) PRIMARY KEY,PARK_ID NUMBER(10),DEVICE_ID VARCHAR2(128 CHAR),DRIVER_ID NUMBER(19),DRIVER_TYPE NUMBER(10),VEHICLE_ASCRIPTION NUMBER(10),CARD_NO VARCHAR2(256 CHAR),VEHICLE_PLATE VARCHAR2(128 CHAR),EVENT_TYPE NUMBER(10),SNAP_TIME TIMESTAMP(6)
);
-- SMT_DEVICE与既有selection表使用已安装fixture，本文件不复制或修改。
