-- 本任务隔离Oracle的新增受理header建议；执行前必须确认目标schema与同名表，禁止盲重建。
CREATE TABLE SMT_AUTH_REQUEST_INTAKE (
 OPERATION_KEY VARCHAR2(100 BYTE) NOT NULL,
 ACTOR_ID NUMBER(10) NOT NULL,
 REQUEST_KEY VARCHAR2(64 BYTE) NOT NULL,
 REQUEST_KIND VARCHAR2(32 BYTE) NOT NULL,
 FINGERPRINT_VERSION NUMBER(10) NOT NULL,
 REQUEST_FINGERPRINT VARCHAR2(64 BYTE) NOT NULL,
 AUTH_SCOPE VARCHAR2(4000 BYTE),
 OUTCOME VARCHAR2(16 BYTE),
 CHILD_COUNT NUMBER(10),
 CHILD_MANIFEST_HASH VARCHAR2(64 BYTE),
 CREATE_TIME TIMESTAMP(6) NOT NULL,
 ACCEPTED_AT TIMESTAMP(6),
 CONSTRAINT PK_AUTH_INTAKE PRIMARY KEY (OPERATION_KEY),
 CONSTRAINT UK_AUTH_INTAKE_ACTOR_KEY UNIQUE (ACTOR_ID,REQUEST_KEY),
 CONSTRAINT CK_AUTH_INTAKE_ACTOR CHECK (ACTOR_ID>0),
 CONSTRAINT CK_AUTH_INTAKE_KEY CHECK (REGEXP_LIKE(REQUEST_KEY,'^[A-Za-z0-9_-]{16,64}$')),
 CONSTRAINT CK_AUTH_INTAKE_KIND CHECK (REQUEST_KIND IN ('REMOVE_ROWS','CLEAR_AUTHORITY')),
 CONSTRAINT CK_AUTH_INTAKE_FP CHECK (FINGERPRINT_VERSION=1 AND REGEXP_LIKE(REQUEST_FINGERPRINT,'^[0-9a-f]{64}$')),
 CONSTRAINT CK_AUTH_INTAKE_CHILD_HASH CHECK (CHILD_MANIFEST_HASH IS NULL OR REGEXP_LIKE(CHILD_MANIFEST_HASH,'^[0-9a-f]{64}$')),
 CONSTRAINT CK_AUTH_INTAKE_FINAL CHECK (
  (OUTCOME IS NULL AND AUTH_SCOPE IS NULL AND CHILD_COUNT IS NULL AND CHILD_MANIFEST_HASH IS NULL AND ACCEPTED_AT IS NULL)
  OR (OUTCOME IS NOT NULL AND AUTH_SCOPE IS NOT NULL AND CHILD_COUNT IS NOT NULL AND CHILD_MANIFEST_HASH IS NOT NULL AND ACCEPTED_AT IS NOT NULL
   AND ((OUTCOME='ACCEPTED' AND CHILD_COUNT>0) OR (OUTCOME='NO_CHANGE' AND CHILD_COUNT=0))))
);
-- SOURCE_ID/PARK_ID/ID索引须先检查实际库是否已有等价索引，本fixture不盲目创建。
-- 可重放承诺期间保留header与child稳定元数据；不能删header后重用旧请求键。

-- 父代理已只读核实不存在 SOURCE_ID 前导等价索引；用于读取完整 child 全集。
CREATE INDEX IX_AUTH_BATCH_SOURCE ON SMT_AUTH_OPERATION_BATCH(SOURCE_ID,ID);
