-- 仅供本任务隔离 Oracle 的合成持久批次基线，不代表生产迁移。
-- 只创建 SMT_AUTH_* 新表；不得删除或重建已有九张 legacy 表。

CREATE TABLE SMT_AUTH_OPERATION_BATCH (
    ID NUMBER(19) PRIMARY KEY,
    PARK_ID NUMBER(10) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128 CHAR) NOT NULL,
    ACTION VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_ID VARCHAR2(128 CHAR),
    SELECTION_SNAPSHOT CLOB NOT NULL,
    -- 由受理命令的动作、来源和稳定选择快照计算；同键复用必须先校验指纹。
    PAYLOAD_FINGERPRINT VARCHAR2(128 CHAR) NOT NULL,
    EXPECTED_COUNT NUMBER(10) NOT NULL,
    EXPANDED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    EXPANSION_CURSOR NUMBER(19) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(32 CHAR) DEFAULT 'PREPARING' NOT NULL,
    FAILURE_REASON VARCHAR2(512 CHAR),
    ACCEPTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EXPANSION_FINISHED_AT TIMESTAMP(6),
    DISPATCHED_AT TIMESTAMP(6),
    CONFIRMED_AT TIMESTAMP(6),
    CONVERGED_AT TIMESTAMP(6),
    FINISHED_AT TIMESTAMP(6),
    DEADLINE_AT TIMESTAMP(6),
    CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_AUTH_BATCH_IDEMPOTENT UNIQUE (PARK_ID, IDEMPOTENCY_KEY)
);

-- 批次 ID 与园区组成父键，供子表复合外键同时校验租户归属。
ALTER TABLE SMT_AUTH_OPERATION_BATCH
    ADD CONSTRAINT UK_AUTH_BATCH_ID_PARK UNIQUE (ID, PARK_ID);

CREATE INDEX IX_AUTH_BATCH_QUEUE
    ON SMT_AUTH_OPERATION_BATCH (PARK_ID, STATUS, EXPANSION_CURSOR, ID);

CREATE TABLE SMT_AUTH_DELETE_REQUEST (
    ID NUMBER(19) PRIMARY KEY,
    BATCH_ID NUMBER(19) NOT NULL,
    PARK_ID NUMBER(10) NOT NULL,
    SUBJECT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    SOURCE_ROW_ID VARCHAR2(128 CHAR),
    SOURCE_IDENTITY_KEY VARCHAR2(256 CHAR) NOT NULL,
    IDENTITY_SNAPSHOT CLOB NOT NULL,
    GENERATION NUMBER(19) NOT NULL,
    DEADLINE_AT TIMESTAMP(6),
    STATUS VARCHAR2(32 CHAR) DEFAULT 'PREPARING' NOT NULL,
    FAILURE_REASON VARCHAR2(512 CHAR),
    FINISHED_AT TIMESTAMP(6),
    CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AUTH_REQUEST_BATCH_PARK FOREIGN KEY (BATCH_ID, PARK_ID)
        REFERENCES SMT_AUTH_OPERATION_BATCH (ID, PARK_ID),
    CONSTRAINT UK_AUTH_REQUEST_SOURCE UNIQUE
        (BATCH_ID, SOURCE_TYPE, SOURCE_IDENTITY_KEY, GENERATION)
);

ALTER TABLE SMT_AUTH_DELETE_REQUEST
    ADD CONSTRAINT UK_AUTH_REQUEST_SCOPE UNIQUE (ID, BATCH_ID, PARK_ID);

ALTER TABLE SMT_AUTH_DELETE_REQUEST
    ADD CONSTRAINT CK_AUTH_REQUEST_SOURCE_ROW CHECK
        (SOURCE_ROW_ID IS NOT NULL OR SOURCE_TYPE = '7');

CREATE INDEX IX_AUTH_REQUEST_STATUS
    ON SMT_AUTH_DELETE_REQUEST (PARK_ID, STATUS, DEADLINE_AT, ID);

CREATE TABLE SMT_AUTH_OPERATION_TARGET (
    ID NUMBER(19) PRIMARY KEY,
    BATCH_ID NUMBER(19) NOT NULL,
    REQUEST_ID NUMBER(19),
    PARK_ID NUMBER(10) NOT NULL,
    TARGET_KEY VARCHAR2(256 CHAR) NOT NULL,
    SUBJECT_TYPE VARCHAR2(32 CHAR) NOT NULL,
    SUBJECT_ID VARCHAR2(128 CHAR) NOT NULL,
    SUBJECT_SNAPSHOT CLOB,
    RESOURCE_TYPE VARCHAR2(32 CHAR) NOT NULL,
    -- DEVICE_ID 是实际物理设备；RESOURCE_ID 是设备内的权限资源/通道。
    DEVICE_ID VARCHAR2(128 CHAR) NOT NULL,
    RESOURCE_ID VARCHAR2(128 CHAR) NOT NULL,
    -- ACCESS_TYPE 是接入适配器（例如 ISC/DIRECT），队列用于业务调度公平性。
    ACCESS_TYPE VARCHAR2(32 CHAR) NOT NULL,
    OPERATION_QUEUE VARCHAR2(64 CHAR) NOT NULL,
    ACTION VARCHAR2(32 CHAR) NOT NULL,
    VALID_FROM TIMESTAMP(6),
    VALID_TO TIMESTAMP(6),
    OPERATION_VERSION NUMBER(19) NOT NULL,
    LEGACY_TASK_ID VARCHAR2(128 CHAR),
    STATE VARCHAR2(32 CHAR) DEFAULT 'PREPARING' NOT NULL,
    RESULT_SUMMARY VARCHAR2(1000 CHAR),
    FAILURE_REASON VARCHAR2(512 CHAR),
    ACCEPTED_AT TIMESTAMP(6),
    DISPATCHED_AT TIMESTAMP(6),
    CONFIRMED_AT TIMESTAMP(6),
    CONVERGED_AT TIMESTAMP(6),
    LEASE_TOKEN VARCHAR2(128 CHAR),
    LEASE_UNTIL TIMESTAMP(6),
    NEXT_ATTEMPT_AT TIMESTAMP(6),
    CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AUTH_TARGET_BATCH_PARK FOREIGN KEY (BATCH_ID, PARK_ID)
        REFERENCES SMT_AUTH_OPERATION_BATCH (ID, PARK_ID),
    CONSTRAINT FK_AUTH_TARGET_REQUEST_SCOPE FOREIGN KEY
        (REQUEST_ID, BATCH_ID, PARK_ID)
        REFERENCES SMT_AUTH_DELETE_REQUEST (ID, BATCH_ID, PARK_ID),
    CONSTRAINT UK_AUTH_TARGET_KEY UNIQUE (BATCH_ID, TARGET_KEY),
    CONSTRAINT UK_AUTH_TARGET_IDENTITY UNIQUE
        (BATCH_ID, SUBJECT_TYPE, SUBJECT_ID, DEVICE_ID, RESOURCE_TYPE,
         RESOURCE_ID, ACCESS_TYPE, OPERATION_VERSION, ACTION)
);

CREATE INDEX IX_AUTH_TARGET_CLAIM
    ON SMT_AUTH_OPERATION_TARGET (PARK_ID, OPERATION_QUEUE, STATE, NEXT_ATTEMPT_AT, ID);

CREATE INDEX IX_AUTH_TARGET_BATCH_STATE
    ON SMT_AUTH_OPERATION_TARGET (BATCH_ID, STATE, ID);

CREATE TABLE SMT_AUTH_OPERATION_ATTEMPT (
    ID NUMBER(19) PRIMARY KEY,
    TARGET_ID NUMBER(19) NOT NULL,
    ATTEMPT_NO NUMBER(10) NOT NULL,
    ACCESS_TYPE VARCHAR2(32 CHAR) NOT NULL,
    TASK_ID VARCHAR2(128 CHAR),
    EXTERNAL_BATCH_ID VARCHAR2(128 CHAR),
    EXTERNAL_COMMAND_ID VARCHAR2(128 CHAR),
    STATUS VARCHAR2(32 CHAR) NOT NULL,
    LEASE_TOKEN VARCHAR2(128 CHAR),
    LEASE_UNTIL TIMESTAMP(6),
    NEXT_ATTEMPT_AT TIMESTAMP(6),
    ERROR_CODE VARCHAR2(64 CHAR),
    ERROR_MESSAGE VARCHAR2(1000 CHAR),
    RESULT_EVENT_ID NUMBER(19),
    DISPATCHED_AT TIMESTAMP(6),
    CONFIRMED_AT TIMESTAMP(6),
    CONVERGED_AT TIMESTAMP(6),
    CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AUTH_ATTEMPT_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES SMT_AUTH_OPERATION_TARGET (ID),
    CONSTRAINT UK_AUTH_ATTEMPT_NO UNIQUE (TARGET_ID, ATTEMPT_NO)
);

ALTER TABLE SMT_AUTH_OPERATION_ATTEMPT
    ADD CONSTRAINT UK_AUTH_ATTEMPT_TARGET_REF UNIQUE (ID, TARGET_ID);

CREATE INDEX IX_AUTH_ATTEMPT_EXTERNAL
    ON SMT_AUTH_OPERATION_ATTEMPT (ACCESS_TYPE, EXTERNAL_BATCH_ID, EXTERNAL_COMMAND_ID);

CREATE TABLE SMT_AUTH_RESULT_EVENT (
    ID NUMBER(19) PRIMARY KEY,
    TARGET_ID NUMBER(19) NOT NULL,
    ATTEMPT_ID NUMBER(19) NOT NULL,
    EVENT_KEY VARCHAR2(256 CHAR) NOT NULL,
    EVENT_NAMESPACE VARCHAR2(64 CHAR) NOT NULL,
    ACCESS_TYPE VARCHAR2(32 CHAR) NOT NULL,
    EXTERNAL_BATCH_ID VARCHAR2(128 CHAR),
    EXTERNAL_COMMAND_ID VARCHAR2(128 CHAR),
    OPERATION_VERSION NUMBER(19) NOT NULL,
    EVIDENCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
    RESULT_STATUS VARCHAR2(32 CHAR) NOT NULL,
    EVIDENCE_BODY CLOB,
    RECEIVED_AT TIMESTAMP(6) NOT NULL,
    CONVERGED CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    FAILURE_REASON VARCHAR2(512 CHAR),
    CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AUTH_EVENT_TARGET FOREIGN KEY (TARGET_ID)
        REFERENCES SMT_AUTH_OPERATION_TARGET (ID),
    CONSTRAINT FK_AUTH_EVENT_ATTEMPT_REF FOREIGN KEY (ATTEMPT_ID, TARGET_ID)
        REFERENCES SMT_AUTH_OPERATION_ATTEMPT (ID, TARGET_ID),
    CONSTRAINT UK_AUTH_EVENT_ATTEMPT_KEY UNIQUE (ATTEMPT_ID, EVENT_KEY),
    CONSTRAINT CK_AUTH_EVENT_CONVERGED CHECK (CONVERGED IN ('Y', 'N'))
);

CREATE INDEX IX_AUTH_EVENT_TARGET
    ON SMT_AUTH_RESULT_EVENT (TARGET_ID, RECEIVED_AT, ID);
