-- 仅用于任务隔离 Oracle 的调度状态，不代表生产迁移。
CREATE TABLE SMT_AUTH_SCHEDULER_STATE (
 INSTANCE_ID VARCHAR2(100 CHAR) PRIMARY KEY,
 WINDOW_KEY VARCHAR2(14 CHAR),
 POLICY_KEY VARCHAR2(64 CHAR),
 TOTAL_USED NUMBER(10) DEFAULT 0 NOT NULL,
 DELETE_USED NUMBER(10) DEFAULT 0 NOT NULL,
 ADD_USED NUMBER(10) DEFAULT 0 NOT NULL,
 CONFIG_USED NUMBER(10) DEFAULT 0 NOT NULL,
 RECEIPT_USED NUMBER(10) DEFAULT 0 NOT NULL,
 BORROW_USED NUMBER(10) DEFAULT 0 NOT NULL
);
-- 归属变更必须显式运维迁移，应用只允许幂等登记，不能自动覆盖。
CREATE TABLE SMT_AUTH_SCHEDULER_ROUTE (
 PARK_ID NUMBER(10) NOT NULL,
 ACCESS_TYPE VARCHAR2(16 CHAR) NOT NULL,
 INSTANCE_ID VARCHAR2(100 CHAR) NOT NULL,
 DIRECT_TAKEOVER_VERSION NUMBER(2) DEFAULT 0 NOT NULL,
 CONSTRAINT CK_AUTH_ROUTE_DIRECT_CAP CHECK(DIRECT_TAKEOVER_VERSION IN (0,1) AND (ACCESS_TYPE='DIRECT' OR DIRECT_TAKEOVER_VERSION=0)),
 CONSTRAINT PK_AUTH_SCHED_ROUTE PRIMARY KEY(PARK_ID,ACCESS_TYPE),
 CONSTRAINT CK_AUTH_SCHED_ROUTE_PARK CHECK(PARK_ID>0),
 CONSTRAINT CK_AUTH_SCHED_ROUTE_ACCESS CHECK(ACCESS_TYPE IN ('ISC','DIRECT')),
 CONSTRAINT FK_AUTH_SCHED_ROUTE FOREIGN KEY(INSTANCE_ID) REFERENCES SMT_AUTH_SCHEDULER_STATE(INSTANCE_ID)
);
CREATE TABLE SMT_AUTH_SCHEDULER_JOB (
 INSTANCE_ID VARCHAR2(100 CHAR) NOT NULL,
 LANE VARCHAR2(128 CHAR) NOT NULL,
 LEASE_TOKEN VARCHAR2(36 CHAR),LEASE_UNTIL TIMESTAMP(6),NEXT_ATTEMPT_AT TIMESTAMP(6),LAST_ADVANCED_AT TIMESTAMP(6),
 DEVICE_CURSOR VARCHAR2(256 CHAR),NUMBER_CURSOR NUMBER(19),TEXT_CURSOR VARCHAR2(256 CHAR),
 PARK_INDEX NUMBER(10) DEFAULT 0 NOT NULL,FAILURES NUMBER(10) DEFAULT 0 NOT NULL,
 CONSTRAINT PK_AUTH_SCHED_JOB PRIMARY KEY(INSTANCE_ID,LANE),
 CONSTRAINT FK_AUTH_SCHED_JOB FOREIGN KEY(INSTANCE_ID) REFERENCES SMT_AUTH_SCHEDULER_STATE(INSTANCE_ID)
);
CREATE TABLE SMT_AUTH_SCHEDULER_QUOTA (
 INSTANCE_ID VARCHAR2(100 CHAR) NOT NULL,
 PARK_ID NUMBER(10) NOT NULL,
 DEVICE_ID VARCHAR2(128 CHAR) NOT NULL,
 SCOPE_TYPE VARCHAR2(8 CHAR) NOT NULL,
 LANE VARCHAR2(16 CHAR) NOT NULL,
 WINDOW_KEY VARCHAR2(14 CHAR) NOT NULL,
 USED NUMBER(10) NOT NULL,
 CONSTRAINT PK_AUTH_SCHED_QUOTA PRIMARY KEY(INSTANCE_ID,PARK_ID,DEVICE_ID,SCOPE_TYPE,LANE),
 CONSTRAINT FK_AUTH_SCHED_QUOTA FOREIGN KEY(INSTANCE_ID) REFERENCES SMT_AUTH_SCHEDULER_STATE(INSTANCE_ID)
);
CREATE INDEX IX_AUTH_TARGET_FAIR ON SMT_AUTH_OPERATION_TARGET(PARK_ID,ACCESS_TYPE,STATE,DEVICE_ID,ID);
CREATE INDEX IX_AUTH_CONTRIB_PRIORITY ON SMT_AUTH_SOURCE_RESOURCE(TARGET_ID,SOURCE_ACTION);
