-- 主体锁只覆盖本地短事务，不在锁内下发设备或展开整批。
CREATE TABLE SMT_AUTH_SUBJECT_COORD (
  ID VARCHAR2(64 CHAR) NOT NULL, PARK_ID NUMBER(19) NOT NULL,
  SUBJECT_TYPE VARCHAR2(64 CHAR) NOT NULL, SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
  CREATE_TIME TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_ASUB PRIMARY KEY (ID),
  CONSTRAINT UK_ASUB_NAT UNIQUE (PARK_ID,SUBJECT_TYPE,SUBJECT_ID)
);
-- 仅用于显式授权的本机合成 Oracle；不包含 DROP，不代表生产迁移。
CREATE TABLE SMT_AUTH_SOURCE_COORD (
  ID VARCHAR2(64 CHAR) NOT NULL,
  PARK_ID NUMBER(19) NOT NULL,
  SOURCE_KIND VARCHAR2(64 CHAR) NOT NULL,
  STABLE_KEY VARCHAR2(1024 CHAR) NOT NULL,
  SUBJECT_TYPE VARCHAR2(64 CHAR) NOT NULL,
  SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
  SOURCE_ROW_ID VARCHAR2(256 CHAR),
  SOURCE_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  GENERATION NUMBER(19) NOT NULL,
  INTENT_KEY VARCHAR2(256 CHAR) NOT NULL,
  INTENT_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  BATCH_ID NUMBER(19) NOT NULL,
  ACTION VARCHAR2(64 CHAR) NOT NULL,
  STATE VARCHAR2(64 CHAR) NOT NULL,
  EXPANDED NUMBER(19) NOT NULL,
  WINDOWS CLOB NOT NULL,
  CREATE_TIME TIMESTAMP(6) NOT NULL,
  UPDATE_TIME TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_ASC PRIMARY KEY (ID),
  CONSTRAINT UK_ASC_NAT UNIQUE (PARK_ID, SOURCE_KIND, STABLE_KEY),
  CONSTRAINT CK_ASC_ACT CHECK (ACTION IN ('ADD','DELETE')),
  CONSTRAINT CK_ASC_GEN CHECK (GENERATION > 0 AND EXPANDED IN (0,1))
);
CREATE TABLE SMT_AUTH_RESOURCE_COORD (
  ID VARCHAR2(64 CHAR) NOT NULL,
  PARK_ID NUMBER(19) NOT NULL,
  SUBJECT_TYPE VARCHAR2(64 CHAR) NOT NULL,
  SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
  ACCESS_TYPE VARCHAR2(64 CHAR) NOT NULL,
  DEVICE_ID VARCHAR2(256 CHAR) NOT NULL,
  RESOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
  RESOURCE_ID VARCHAR2(256 CHAR) NOT NULL,
  SERVICE_TYPE VARCHAR2(64 CHAR) NOT NULL,
  CREDENTIAL_CHANNEL VARCHAR2(64 CHAR) NOT NULL,
  RESOURCE_KEY VARCHAR2(1024 CHAR) NOT NULL,
  GENERATION NUMBER(19) NOT NULL,
  APPLIED_GENERATION NUMBER(19) NOT NULL,
  ACTION VARCHAR2(64 CHAR) NOT NULL,
  WINDOWS CLOB NOT NULL,
  DESIRED_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  BASIS_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  BLOCKING_TARGET_ID NUMBER(19),
  BLOCKING_ATTEMPT_ID NUMBER(19),
  BLOCK_REASON VARCHAR2(64 CHAR),
  CREATE_TIME TIMESTAMP(6) NOT NULL,
  UPDATE_TIME TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_ARC PRIMARY KEY (ID),
  CONSTRAINT UK_ARC_KEY UNIQUE (RESOURCE_KEY),
  CONSTRAINT CK_ARC_GEN CHECK (GENERATION >= APPLIED_GENERATION AND APPLIED_GENERATION >= 0),
  CONSTRAINT CK_ARC_ACT CHECK (ACTION IN ('ADD','DELETE')),
  CONSTRAINT CK_ARC_BLK CHECK ((BLOCKING_TARGET_ID IS NULL AND BLOCKING_ATTEMPT_ID IS NULL) OR (BLOCKING_TARGET_ID IS NOT NULL AND BLOCKING_ATTEMPT_ID IS NOT NULL))
);
CREATE TABLE SMT_AUTH_SOURCE_RESOURCE (
  BINDING_REVISION NUMBER(19) DEFAULT 0 NOT NULL,
  SOURCE_ACTION VARCHAR2(64 CHAR) DEFAULT 'ADD' NOT NULL,
  INTENT_KEY VARCHAR2(256 CHAR) NOT NULL,
  INTENT_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  ID VARCHAR2(64 CHAR) NOT NULL,
  SOURCE_COORD_ID VARCHAR2(64 CHAR) NOT NULL,
  SOURCE_GENERATION NUMBER(19) NOT NULL,
  RESOURCE_COORD_ID VARCHAR2(64 CHAR) NOT NULL,
  RESOURCE_GENERATION NUMBER(19) NOT NULL,
  SOURCE_ROW_ID VARCHAR2(256 CHAR),
  SOURCE_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  WINDOWS CLOB NOT NULL,
  ACTION VARCHAR2(64 CHAR) NOT NULL,
  STATE VARCHAR2(64 CHAR) NOT NULL,
  REQUEST_ID NUMBER(19) NOT NULL,
  TARGET_ID NUMBER(19),
  ATTEMPT_ID NUMBER(19),
  CREATE_TIME TIMESTAMP(6) NOT NULL,
  UPDATE_TIME TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_ASR PRIMARY KEY (ID),
  CONSTRAINT UK_ASR_GEN UNIQUE (SOURCE_COORD_ID, SOURCE_GENERATION, RESOURCE_COORD_ID, BINDING_REVISION),
  CONSTRAINT FK_ASR_SRC FOREIGN KEY (SOURCE_COORD_ID) REFERENCES SMT_AUTH_SOURCE_COORD(ID),
  CONSTRAINT FK_ASR_RES FOREIGN KEY (RESOURCE_COORD_ID) REFERENCES SMT_AUTH_RESOURCE_COORD(ID)
);
CREATE TABLE SMT_AUTH_IDENTITY_ALIAS (
  ID VARCHAR2(64 CHAR) NOT NULL,
  PARK_ID NUMBER(19) NOT NULL,
  ACCESS_TYPE VARCHAR2(64 CHAR) NOT NULL,
  DEVICE_ID VARCHAR2(256 CHAR) NOT NULL,
  RESOURCE_TYPE VARCHAR2(64 CHAR) NOT NULL,
  RESOURCE_VALUE VARCHAR2(256 CHAR) NOT NULL,
  SERVICE_TYPE VARCHAR2(64 CHAR) NOT NULL,
  CREDENTIAL_CHANNEL VARCHAR2(64 CHAR) NOT NULL,
  SUBJECT_TYPE VARCHAR2(64 CHAR) NOT NULL,
  SUBJECT_ID VARCHAR2(256 CHAR) NOT NULL,
  RESOURCE_COORD_ID VARCHAR2(64 CHAR) NOT NULL,
  RESOURCE_GENERATION NUMBER(19) NOT NULL,
  ALIAS_KIND VARCHAR2(64 CHAR) NOT NULL,
  ALIAS_VALUE VARCHAR2(256 CHAR) NOT NULL,
  CREATE_TIME TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_AIA PRIMARY KEY (ID),
  CONSTRAINT UK_AIA_HIST UNIQUE (RESOURCE_COORD_ID, RESOURCE_GENERATION, ALIAS_KIND, ALIAS_VALUE),
  CONSTRAINT FK_AIA_RES FOREIGN KEY (RESOURCE_COORD_ID) REFERENCES SMT_AUTH_RESOURCE_COORD(ID)
);
CREATE INDEX IX_ASC_PENDING ON SMT_AUTH_SOURCE_COORD(PARK_ID, STATE, ID);
CREATE INDEX IX_ASR_RESOURCE ON SMT_AUTH_SOURCE_RESOURCE(RESOURCE_COORD_ID, SOURCE_COORD_ID, SOURCE_GENERATION);
CREATE INDEX IX_ASR_TARGET ON SMT_AUTH_SOURCE_RESOURCE(TARGET_ID, ATTEMPT_ID);
CREATE INDEX IX_AIA_LOOKUP ON SMT_AUTH_IDENTITY_ALIAS(PARK_ID, ACCESS_TYPE, DEVICE_ID, RESOURCE_TYPE, RESOURCE_VALUE, SUBJECT_TYPE, ALIAS_KIND, ALIAS_VALUE);
CREATE INDEX IX_ASR_INTENT ON SMT_AUTH_SOURCE_RESOURCE(SOURCE_COORD_ID, INTENT_KEY, SOURCE_GENERATION);
-- 负修订保存旧可信attempt的一次性补偿失效，不占当前贡献或历史target绑定修订。
CREATE UNIQUE INDEX UK_ASR_STALE ON SMT_AUTH_SOURCE_RESOURCE (
  CASE WHEN BINDING_REVISION < 0 THEN RESOURCE_COORD_ID END,
  CASE WHEN BINDING_REVISION < 0 THEN ATTEMPT_ID END
);
