-- 仅供独立测试 schema；持久页指纹与贡献、请求、游标在同一事务提交。
CREATE TABLE SMT_AUTH_WORKFLOW_SHARD (
  BATCH_ID NUMBER(19) NOT NULL,
  PREVIOUS_CURSOR NUMBER(19) NOT NULL,
  NEXT_CURSOR NUMBER(19) NOT NULL,
  SHARD_KIND VARCHAR2(8 CHAR) NOT NULL,
  CONTENT_FINGERPRINT VARCHAR2(64 CHAR) NOT NULL,
  SOURCE_COORD_ID VARCHAR2(64 CHAR),
  SOURCE_GENERATION NUMBER(19),
  CREATE_TIME TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_AUTH_WORKFLOW_SHARD PRIMARY KEY (BATCH_ID,PREVIOUS_CURSOR,NEXT_CURSOR),
  CONSTRAINT UK_AUTH_WORKFLOW_START UNIQUE (BATCH_ID,PREVIOUS_CURSOR),
  CONSTRAINT FK_AUTH_WORKFLOW_BATCH FOREIGN KEY (BATCH_ID) REFERENCES SMT_AUTH_OPERATION_BATCH(ID),
  CONSTRAINT CK_AUTH_WORKFLOW_CURSOR CHECK (PREVIOUS_CURSOR>=0 AND NEXT_CURSOR>PREVIOUS_CURSOR),
  CONSTRAINT CK_AUTH_WORKFLOW_KIND CHECK (SHARD_KIND IN ('STAGE','BIND')),
  CONSTRAINT CK_AUTH_WORKFLOW_SOURCE CHECK ((SHARD_KIND='STAGE' AND SOURCE_COORD_ID IS NOT NULL AND SOURCE_GENERATION IS NOT NULL AND SOURCE_GENERATION>0)
    OR (SHARD_KIND='BIND' AND SOURCE_COORD_ID IS NULL AND SOURCE_GENERATION IS NULL))
);
