
package com.tce.smart.data.webservice.newservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "RequestServicePortType", targetNamespace = "http://localhost/services/RequestService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RequestServicePortType {


    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns com.tce.smart.data.webservice.newservice.ArrayOfRequestBase
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getPendingRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetPendingRequestBySearch")
    @ResponseWrapper(localName = "getPendingRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetPendingRequestBySearchResponse")
    ArrayOfRequestBase getPendingRequestBySearch(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3);

    /**
     *
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "forwardFlow1", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.ForwardFlow1")
    @ResponseWrapper(localName = "forwardFlow1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.ForwardFlow1Response")
    String forwardFlow1(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
            String in4,
            @WebParam(name = "in5", targetNamespace = "http://localhost/services/RequestService")
            String in5);

    /**
     *
     * @param in0
     * @return
     *     returns com.tce.smart.data.webservice.newservice.AnyType2AnyTypeMap
     */
    @WebMethod(operationName = "LoadTemplateProp")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "LoadTemplateProp", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.LoadTemplateProp")
    @ResponseWrapper(localName = "LoadTemplatePropResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.LoadTemplatePropResponse")
    AnyType2AnyTypeMap loadTemplateProp(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            String in0);

    /**
     *
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "createRequest", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.CreateRequest")
    @ResponseWrapper(localName = "createRequestResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.CreateRequestResponse")
    String createRequest(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            RequestInfo in0);

    /**
     *
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "doForceOver", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.DoForceOver")
    @ResponseWrapper(localName = "doForceOverResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.DoForceOverResponse")
    String doForceOver(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1);

    /**
     *
     * @param in0
     * @return
     *     returns com.tce.smart.data.webservice.newservice.RequestInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest")
    @ResponseWrapper(localName = "getRequestResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequestResponse")
    RequestInfo getRequest(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0);

    /**
     *
     * @param in0
     * @param in1
     */
    @WebMethod
    @RequestWrapper(localName = "writeLog1", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.WriteLog1")
    @ResponseWrapper(localName = "writeLog1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.WriteLog1Response")
    void writeLog1(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            Object in1);

    /**
     *
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRightMenu", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRightMenu")
    @ResponseWrapper(localName = "getRightMenuResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRightMenuResponse")
    String getRightMenu(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            int in3,
            @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
            int in4,
            @WebParam(name = "in5", targetNamespace = "http://localhost/services/RequestService")
            boolean in5);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns com.tce.smart.data.webservice.newservice.ArrayOfRequestBase
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getHendledRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetHendledRequestBySearch")
    @ResponseWrapper(localName = "getHendledRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetHendledRequestBySearchResponse")
    ArrayOfRequestBase getHendledRequestBySearch(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "nextNodeBySubmit", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.NextNodeBySubmit")
    @ResponseWrapper(localName = "nextNodeBySubmitResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.NextNodeBySubmitResponse")
    boolean nextNodeBySubmit(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            RequestInfo in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns com.tce.smart.data.webservice.newservice.ArrayOfRequestBase
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getMyRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetMyRequestBySearch")
    @ResponseWrapper(localName = "getMyRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetMyRequestBySearchResponse")
    ArrayOfRequestBase getMyRequestBySearch(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3);

    /**
     *
     * @param in0
     * @param in1
     * @return
     *     returns com.tce.smart.data.webservice.newservice.RequestInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest2", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest2")
    @ResponseWrapper(localName = "getRequest2Response", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest2Response")
    RequestInfo getRequest2(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "nextNodeByReject", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.NextNodeByReject")
    @ResponseWrapper(localName = "nextNodeByRejectResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.NextNodeByRejectResponse")
    boolean nextNodeByReject(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2);

    /**
     *
     * @param in0
     * @return
     *     returns com.tce.smart.data.webservice.newservice.RequestInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest1", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest1")
    @ResponseWrapper(localName = "getRequest1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest1Response")
    RequestInfo getRequest1(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            RequestManager in0);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "nextNodeBySubmit1", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.NextNodeBySubmit1")
    @ResponseWrapper(localName = "nextNodeBySubmit1Response", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.NextNodeBySubmit1Response")
    boolean nextNodeBySubmit1(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            RequestInfo in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
            String in4);

    /**
     *
     * @param in0
     * @param in1
     * @return
     *     returns com.tce.smart.data.webservice.newservice.RequestInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequest3", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest3")
    @ResponseWrapper(localName = "getRequest3Response", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequest3Response")
    RequestInfo getRequest3(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            RequestManager in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1);

    /**
     *
     * @param in0
     */
    @WebMethod
    @RequestWrapper(localName = "writeLog", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.WriteLog")
    @ResponseWrapper(localName = "writeLogResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.WriteLogResponse")
    void writeLog(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            Object in0);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "forwardFlow", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.ForwardFlow")
    @ResponseWrapper(localName = "forwardFlowResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.ForwardFlowResponse")
    boolean forwardFlow(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
            String in4);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns com.tce.smart.data.webservice.newservice.ArrayOfLog
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getRequestLogs", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequestLogs")
    @ResponseWrapper(localName = "getRequestLogsResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetRequestLogsResponse")
    ArrayOfLog getRequestLogs(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            int in2);

    /**
     *
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getPropValue", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetPropValue")
    @ResponseWrapper(localName = "getPropValueResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetPropValueResponse")
    String getPropValue(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            String in1);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "givingOpinions", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GivingOpinions")
    @ResponseWrapper(localName = "givingOpinionsResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GivingOpinionsResponse")
    String givingOpinions(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "whetherMustInputRemark", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.WhetherMustInputRemark")
    @ResponseWrapper(localName = "whetherMustInputRemarkResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.WhetherMustInputRemarkResponse")
    boolean whetherMustInputRemark(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            int in3,
            @WebParam(name = "in4", targetNamespace = "http://localhost/services/RequestService")
            int in4);

    /**
     *
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.DeleteRequestResponse")
    boolean deleteRequest(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0);

    /**
     *
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns com.tce.smart.data.webservice.newservice.ArrayOfRequestBase
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/RequestService")
    @RequestWrapper(localName = "getProcessedRequestBySearch", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetProcessedRequestBySearch")
    @ResponseWrapper(localName = "getProcessedRequestBySearchResponse", targetNamespace = "http://localhost/services/RequestService", className = "com.tce.smart.data.webservice.newservice.GetProcessedRequestBySearchResponse")
    ArrayOfRequestBase getProcessedRequestBySearch(
            @WebParam(name = "in0", targetNamespace = "http://localhost/services/RequestService")
            int in0,
            @WebParam(name = "in1", targetNamespace = "http://localhost/services/RequestService")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://localhost/services/RequestService")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://localhost/services/RequestService")
            String in3);

}
