
package com.tce.smart.data.webservice.newservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "RequestService", targetNamespace = "http://localhost/services/RequestService", wsdlLocation = "http://10.0.20.69/services/RequestService?wsdl")
public class RequestService
    extends Service
{

    private final static URL REQUESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUESTSERVICE_EXCEPTION;
    private final static QName REQUESTSERVICE_QNAME = new QName("http://localhost/services/RequestService", "RequestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.20.69/services/RequestService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REQUESTSERVICE_WSDL_LOCATION = url;
        REQUESTSERVICE_EXCEPTION = e;
    }

    public RequestService() {
        super(__getWsdlLocation(), REQUESTSERVICE_QNAME);
    }

    public RequestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REQUESTSERVICE_QNAME, features);
    }

    public RequestService(URL wsdlLocation) {
        super(wsdlLocation, REQUESTSERVICE_QNAME);
    }

    public RequestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REQUESTSERVICE_QNAME, features);
    }

    public RequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RequestServicePortType
     */
    @WebEndpoint(name = "RequestServiceHttpPort")
    public RequestServicePortType getRequestServiceHttpPort() {
        return super.getPort(new QName("http://localhost/services/RequestService", "RequestServiceHttpPort"), RequestServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestServicePortType
     */
    @WebEndpoint(name = "RequestServiceHttpPort")
    public RequestServicePortType getRequestServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/services/RequestService", "RequestServiceHttpPort"), RequestServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REQUESTSERVICE_EXCEPTION!= null) {
            throw REQUESTSERVICE_EXCEPTION;
        }
        return REQUESTSERVICE_WSDL_LOCATION;
    }

}
