package com.tce.smart.platform.service.print;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tce.smart.platform.core.entity.print.*;
import com.tce.smart.platform.core.mapper.PrintJobMapper;
import org.springframework.stereotype.Service;
import java.util.*;
import static com.tce.smart.platform.service.print.PrintJobTransactions.*;
/** 真实人员预览使用独立私有制品，不创建打印任务也不授予设备领取权。 */
@Service public class PrintJobPreviewService {
 final PrintJobMapper db;final PrintAccessPolicy access;final PrintJobTransactions tx;final PrintJobPreparation preparation;final PrintRendererClient renderer;final PrintJobRenderer artifacts;
 public PrintJobPreviewService(PrintJobMapper db,PrintAccessPolicy access,PrintJobTransactions tx,PrintJobPreparation preparation,PrintRendererClient renderer,PrintJobRenderer artifacts){this.db=db;this.access=access;this.tx=tx;this.preparation=preparation;this.renderer=renderer;this.artifacts=artifacts;}
 public Map<String,Object> preview(ObjectNode request){String park=access.resolvePark(request.path("parkId").asText(null));access.require("preview",park);PrintPrinter p=db.findPrinter(request.path("printerProfileId").asText());if(p==null)throw error(404,"PRINTER_PROFILE_NOT_FOUND");if(!park.equals(p.getParkId()))throw error(403,"PRINT_SCOPE_DENIED");String id=id();ObjectNode profile=PrintPrinterService.snapshot(p);ObjectNode frozen=tx.atomic(()->preparation.freeze(request,id,profile,true));ObjectNode details=PrintJson.object().put("previewId",id);ObjectNode summary=PrintJson.object();for(String k:Arrays.asList("subjectId","subjectType","personType","classificationCode","employeeGradeCode","employeeGradeName","employeeGradeSource"))if(frozen.has(k))summary.set(k,frozen.get(k));details.set("subjectSummary",summary);details.set("resolution",PrintJobService.publicResolution(frozen.path("resolution")));JsonNode rendered=null;try{rendered=renderer.renderFrozen(frozen.path("renderRequest"));}catch(PrintApiException e){if(e.getStatus()!=422)throw e;details.put("status","RENDER_FAILED").put("errorCode",e.getCode());details.putArray("artifacts");}final JsonNode result=rendered;return tx.atomic(()->{if(result!=null){details.setAll(artifacts.store(id,park,result));details.put("status","READY");details.set("confirmation",PrintJobConfirmation.evidence(frozen,profile,request.path("printMode").asText(profile.path("defaultPrintMode").asText())));}PrintJobPreview row=new PrintJobPreview();row.setPreviewId(id);row.setParkId(park);row.setCreatedBy(access.actor());row.setDetailsJson(PrintJson.canonical(details));db.insertJobPreview(row);return view(row);});}
 public Map<String,Object> detail(String id){return view(authorized(id));}
 PrintJobPreview authorized(String id){PrintAccessPolicy.uuid(id);PrintJobPreview row=db.findJobPreview(id);if(row==null)throw error(404,"PRINT_PREVIEW_NOT_FOUND");access.require("preview",row.getParkId());if(!access.actor().equals(row.getCreatedBy()))throw error(403,"PRINT_SCOPE_DENIED");return row;}
 Map<String,Object> view(PrintJobPreview row){ObjectNode details=(ObjectNode)PrintJson.read(row.getDetailsJson());details.remove("confirmation");for(JsonNode a:details.path("artifacts"))url(row.getPreviewId(),(ObjectNode)a);if(details.hasNonNull("combinedArtifact"))url(row.getPreviewId(),(ObjectNode)details.get("combinedArtifact"));return PrintJson.map(details);}
 void url(String id,ObjectNode a){a.remove(Arrays.asList("objectId","contentBase64"));a.put("downloadPath","/platform/print/v1/print-jobs/previews/"+id+"/artifacts/"+a.path("artifactId").asText());}
 public byte[] artifact(String id,String artifact){PrintJobPreview row=authorized(id);access.require("resource",row.getParkId());PrintAccessPolicy.uuid(artifact);JsonNode details=PrintJson.read(row.getDetailsJson());List<JsonNode> all=new ArrayList<>();details.path("artifacts").forEach(all::add);if(details.hasNonNull("combinedArtifact"))all.add(details.get("combinedArtifact"));for(JsonNode a:all)if(artifact.equals(a.path("artifactId").asText())){PrintJobArtifact stored=db.findJobArtifact(artifact);if(stored==null||!id.equals(stored.getOwnerId())||!row.getParkId().equals(stored.getParkId())||!PrintJson.hashBytes(stored.getContentBytes()).equals(a.path("sha256").asText()))throw error(422,"PRINT_RESOURCE_HASH_MISMATCH");return stored.getContentBytes();}throw error(403,"PRINT_SCOPE_DENIED");}
}
