package com.tce.smart.platform.service.print;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tce.smart.platform.core.entity.print.*;
import com.tce.smart.platform.core.mapper.PrintJobMapper;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Service;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import static com.tce.smart.platform.service.print.PrintJobTransactions.*;
import static com.tce.smart.platform.service.print.PrintJobService.*;
/** 独立设备身份和同事务物理占用；租约永不授予第二次提交权。 */
@Service public class PrintClientService {
 final PrintJobMapper db;final PrintJobTransactions tx;final PrintExecutionProperties execution;
 public PrintClientService(PrintJobMapper db,PrintJobTransactions tx,PrintExecutionProperties execution){this.db=db;this.tx=tx;this.execution=execution;}
 PrintPrinter printer(PrintClientIdentity device,String id){PrintAccessPolicy.uuid(id);PrintPrinter p=db.findPrinter(id);if(p==null)throw error(404,"PRINTER_PROFILE_NOT_FOUND");if(p.getActiveJobId()!=null){PrintJob active=db.findJob(p.getActiveJobId());if(active==null)throw error(409,"JOB_STATE_CONFLICT");device.require(active.getParkId(),id,active.getDeviceIdentity());}else device.require(p.getParkId(),id,p.getDeviceIdentity());return p;}
 PrintJob job(PrintClientIdentity device,String id){PrintAccessPolicy.uuid(id);PrintJob j=db.findJob(id);if(j==null)throw error(404,"PRINT_JOB_NOT_FOUND");device.require(j.getParkId(),j.getPrinterProfileId(),j.getDeviceIdentity());return j;}
 public PrintMutationResult claim(PrintClientIdentity device,ObjectNode body,String key){String printerId=body.path("printerProfileId").asText();printer(device,printerId);if(!device.deviceIdentity.equals(body.path("deviceIdentity").asText()))throw error(403,"PRINT_SCOPE_DENIED");PrintAccessPolicy.uuid(body.path("clientInstanceId").asText());if(!body.path("clientVersion").asText().matches("[A-Za-z0-9.+-]{1,64}"))throw error(422,"INVALID_REQUEST");return tx.command(device.principal(),key,"DEVICE_CLAIM",body,()->{PrintPrinter p=db.lockPrinter(printerId);PrintJob j;if(p.getActiveJobId()!=null){if(!p.getActiveJobId().equals(body.path("resumeJobId").asText()))throw error(409,"PRINTER_OCCUPIED");j=db.lockJob(p.getActiveJobId());device.require(j.getParkId(),j.getPrinterProfileId(),j.getDeviceIdentity());checkCapabilities(j,body);j.setClientInstanceId(body.path("clientInstanceId").asText());j.setLeaseExpiresAt(lease());db.updateJob(j);return action(j);}
  if(!execution.isEnabled())throw error(503,"PRINT_EXECUTION_DISABLED");if(!"ENABLED".equals(p.getStatus()))throw error(409,"PRINTER_DISABLED");if(body.hasNonNull("resumeJobId")){j=job(device,body.path("resumeJobId").asText());if(!printerId.equals(j.getPrinterProfileId()))throw error(403,"PRINT_SCOPE_DENIED");j=db.lockJob(j.getJobId());if(!"READY".equals(j.getStatus()))throw error(409,"JOB_STATE_CONFLICT");}else{List<PrintJob> ready=db.listJobs(p.getParkId(),null,printerId,"READY",new RowBounds(0,1));if(ready.isEmpty())return Collections.singletonMap("action",Collections.singletonMap("type","NONE"));j=db.lockJob(ready.get(0).getJobId());if(!"READY".equals(j.getStatus()))throw error(409,"JOB_STATE_CONFLICT");}checkCapabilities(j,body);if(!device.deviceIdentity.equals(j.getDeviceIdentity()))throw error(403,"PRINT_SCOPE_DENIED");p.setActiveJobId(j.getJobId());db.updatePrinter(p);j.setClaimId(id());j.setClientInstanceId(body.path("clientInstanceId").asText());j.setLeaseExpiresAt(lease());newAttempt(db,j,"AUTO_DUPLEX".equals(j.getPrintMode())?"BOTH":"FRONT");j.setUpdatedAt(now());db.updateJob(j);audit(device,j,"DEVICE_CLAIMED");return action(j);});}
 void checkCapabilities(PrintJob j,JsonNode body){if(!j.getPrinterSnapshotHash().equals(body.path("capabilitySnapshotHash").asText()))throw error(409,"PRINTER_SNAPSHOT_MISMATCH");boolean supports=false;for(JsonNode mode:body.path("supportedPrintModes"))if(j.getPrintMode().equals(mode.asText()))supports=true;if(!supports)throw error(422,"PRINTER_MODE_NOT_ALLOWED");}
 public Map<String,Object> current(PrintClientIdentity device,String claim){PrintAccessPolicy.uuid(claim);PrintJob j=db.findClaim(claim);if(j==null)throw error(404,"PRINT_CLAIM_NOT_FOUND");device.require(j.getParkId(),j.getPrinterProfileId(),j.getDeviceIdentity());return action(j);}
 public PrintMutationResult renew(PrintClientIdentity device,String claim,ObjectNode body,String key){PrintAccessPolicy.uuid(claim);PrintJob initial=db.findClaim(claim);if(initial==null)throw error(404,"PRINT_CLAIM_NOT_FOUND");device.require(initial.getParkId(),initial.getPrinterProfileId(),initial.getDeviceIdentity());return tx.command(device.principal(),key,"CLAIM_RENEW:"+claim,body,()->{PrintJob j=db.lockJob(initial.getJobId());if(!device.deviceIdentity.equals(body.path("deviceIdentity").asText())||!Objects.equals(j.getClientInstanceId(),body.path("clientInstanceId").asText()))throw error(403,"PRINT_SCOPE_DENIED");if(!j.getLeaseExpiresAt().toInstant().toString().equals(body.path("leaseExpiresAt").asText()))throw error(409,"CLAIM_LEASE_CONFLICT");j.setLeaseExpiresAt(lease());db.updateJob(j);audit(device,j,"CLAIM_RENEWED");return action(j);});}
 static Timestamp lease(){return Timestamp.from(Instant.now().plusSeconds(60));}
 public PrintMutationResult event(PrintClientIdentity device,String id,ObjectNode body,String key){PrintJob initial=job(device,id);PrintJson.limit(body,65536);String eventId=body.path("eventId").asText();PrintAccessPolicy.uuid(eventId);if(!body.path("clientSequence").isIntegralNumber()||body.path("clientSequence").asLong()<1)throw error(422,"INVALID_REQUEST");try{Instant.parse(body.path("occurredAt").asText());}catch(Exception e){throw error(422,"INVALID_REQUEST");}String hash=PrintJson.hash(body);return tx.command(device.principal(),key,"DEVICE_EVENT:"+id,body,()->{db.lockPrinter(initial.getPrinterProfileId());PrintJob j=db.lockJob(id);PrintJobEvent prior=db.findJobEvent(eventId);if(prior!=null){if(!id.equals(prior.getJobId())||!hash.equals(prior.getBodyHash()))throw error(409,"IDEMPOTENCY_KEY_REUSED");return PrintJson.map(PrintJson.read(prior.getResponseJson()));}PrintJobAttempt a=db.findJobAttempt(body.path("attemptId").asText());if(a==null||!id.equals(a.getJobId())||!a.getCommandId().equals(body.path("commandId").asText()))throw error(409,"JOB_STATE_CONFLICT");JsonNode artifact=artifactMetadata(j,"BOTH".equals(a.getFace())?"combined":a.getFace());if(!artifact.path("sha256").asText().equals(body.path("artifactHash").asText()))throw error(422,"PRINT_RESOURCE_HASH_MISMATCH");String type=body.path("eventType").asText();if(!Arrays.asList("INTENT_RECORDED","COMMAND_SENT","DRIVER_REJECTED","DEVICE_ACCEPTED","DEVICE_COMPLETED","DEVICE_DISCONNECTED","OUTPUT_UNKNOWN","COMMAND_RETIRED","DEVICE_CLEARED").contains(type))throw error(422,"INVALID_REQUEST");ObjectNode s=state(a);boolean late=!a.getAttemptId().equals(j.getCurrentAttemptId());boolean wasTerminal=terminal(j);JsonNode payload=body.path("payload");
  // 当前命令出现新的提交或未知风险时，先前无卡检查失效；后续只能重新人工核对。
  if(!late&&Arrays.asList("COMMAND_SENT","DEVICE_ACCEPTED","DEVICE_COMPLETED","DEVICE_DISCONNECTED","OUTPUT_UNKNOWN").contains(type)){j.setOperatorCheckId(null);s.remove(Arrays.asList("operatorCheckId","operatorPhysicalState"));}

  if("COMMAND_RETIRED".equals(type)){if(!payload.path("queueCleared").asBoolean()||!payload.path("localCommandRetired").asBoolean()||!payload.path("sameCardFaceVerified").asBoolean())throw error(422,"OUTPUT_CHECK_INCOMPLETE");s.put("retired",true);}
  else if("DEVICE_CLEARED".equals(type)){clear(j,payload);}
  else if(late){if(Arrays.asList("DEVICE_ACCEPTED","DEVICE_COMPLETED","COMMAND_SENT").contains(type)&&!wasTerminal){PrintJobAttempt active=db.findJobAttempt(j.getCurrentAttemptId());
   // 已人工确认的正面回执与正常翻面相符；同面退休后矛盾出卡仍须暂停当前尝试。
   boolean confirmedFront="MANUAL_DUPLEX".equals(j.getPrintMode())&&"FRONT".equals(a.getFace())&&"BACK".equals(active.getFace())&&s.path("confirmedOut").asBoolean()&&!s.path("retired").asBoolean();
   if(!confirmedFront){j.setStatus("RESULT_UNKNOWN");j.setOperatorCheckId(null);ObjectNode activeState=state(active);activeState.put("unknown",true).put("lateConflict",true);activeState.remove(Arrays.asList("operatorCheckId","operatorPhysicalState"));active.setStateJson(PrintJson.canonical(activeState));db.updateJobAttempt(active);}}}
  else if(!wasTerminal){
   if("DRIVER_REJECTED".equals(type)){s.put("rejectedNotSubmitted",payload.path("submissionAccepted").isBoolean()&&!payload.path("submissionAccepted").asBoolean());j.setStatus("RESULT_UNKNOWN");}
   else if(Arrays.asList("OUTPUT_UNKNOWN","DEVICE_DISCONNECTED").contains(type)){s.put("unknown",true);j.setStatus("RESULT_UNKNOWN");}
   else if(Arrays.asList("DEVICE_ACCEPTED","DEVICE_COMPLETED").contains(type)){s.put("accepted",true);if("DEVICE_COMPLETED".equals(type))s.put("completedEvidence",true);if(!"RESULT_UNKNOWN".equals(j.getStatus())&&!"AWAITING_FLIP".equals(j.getStatus()))j.setStatus("MANUAL_DUPLEX".equals(j.getPrintMode())&&"FRONT".equals(a.getFace())?"AWAITING_FRONT_CHECK":"AWAITING_OUTPUT_CHECK");}
   else if("COMMAND_SENT".equals(type)){s.put("sent",true);}
   else s.put("intentRecorded",true);
  }
  if(!late)s.put("status",j.getStatus());a.setStateJson(PrintJson.canonical(s));db.updateJobAttempt(a);j.setUpdatedAt(now());db.updateJob(j);Map<String,Object> response=new LinkedHashMap<>();response.put("jobId",id);response.put("status",j.getStatus());response.put("eventAccepted",true);response.put("late",late);response.put("nextAction",action(j).get("action"));PrintJobEvent e=new PrintJobEvent();e.setEventId(eventId);e.setJobId(id);e.setAttemptId(a.getAttemptId());e.setCommandId(a.getCommandId());e.setEventType(type);e.setBodyHash(hash);e.setResponseJson(PrintJson.canonical(response));Map<String,Object> summary=auditSummary(j,Collections.emptyMap());summary.put("eventId",eventId);summary.put("attemptId",a.getAttemptId());summary.put("eventType",type);summary.put("bodyHash",hash);summary.put("late",late);e.setDetailsJson(PrintJson.canonical(summary));e.setCreatedAt(now());db.insertJobEvent(e);tx.audit(device.principal(),j.getParkId(),"DEVICE_EVENT",id,summary);return response;});}
 public PrintMutationResult deviceCleared(PrintClientIdentity device,String id,ObjectNode body,String key){PrintJob initial=job(device,id);return tx.command(device.principal(),key,"DEVICE_CLEAR:"+id,body,()->{db.lockPrinter(initial.getPrinterProfileId());PrintJob j=db.lockJob(id);if(!device.deviceIdentity.equals(body.path("deviceIdentity").asText()))throw error(403,"PRINT_SCOPE_DENIED");clear(j,body);audit(device,j,"DEVICE_CLEARED");return Collections.singletonMap("cleared",terminal(j));});}
 void clear(PrintJob j,JsonNode body){String physical=body.path("physicalState").asText(body.path("state").asText());if(!"NO_CARD_IN_DEVICE".equals(physical)||j.getOperatorCheckId()==null||!j.getOperatorCheckId().equals(body.path("operatorCheckId").asText()))throw error(409,"DEVICE_CLEARANCE_REQUIRED");PrintJobAttempt a=db.findJobAttempt(j.getCurrentAttemptId());if(a==null||!j.getOperatorCheckId().equals(state(a).path("operatorCheckId").asText())||!"NO_CARD_IN_DEVICE".equals(state(a).path("operatorPhysicalState").asText()))throw error(409,"DEVICE_CLEARANCE_REQUIRED");if(Arrays.asList("COMPLETED","CANCELLED","FAILED").contains(j.getStatus())){PrintPrinter p=db.lockPrinter(j.getPrinterProfileId());if(j.getJobId().equals(p.getActiveJobId())){p.setActiveJobId(null);db.updatePrinter(p);}}}
 public Map<String,Object> action(PrintJob j){return action(db,j);}
 /** 管理端人工推进与设备current共享冻结命令结构，避免返回不同的命令或制品字段。 */
 static Map<String,Object> action(PrintJobMapper db,PrintJob j){Map<String,Object> r=new LinkedHashMap<>();for(String k:Arrays.asList("jobId","status","deviceIdentity","printerProfileId","printMode","templateSnapshotHash","printerSnapshotHash"))r.put(k,view(j).get(k));r.put("claimId",j.getClaimId());r.put("leaseExpiresAt",j.getLeaseExpiresAt()==null?null:j.getLeaseExpiresAt().toInstant().toString());Map<String,Object>a=new LinkedHashMap<>();String type="NONE";if("AWAITING_FRONT_CHECK".equals(j.getStatus()))type="WAIT_FRONT_CHECK";else if("AWAITING_FLIP".equals(j.getStatus()))type="WAIT_FLIP";else if("AWAITING_OUTPUT_CHECK".equals(j.getStatus()))type="WAIT_OUTPUT_CHECK";else if("RESULT_UNKNOWN".equals(j.getStatus()))type="RESULT_UNKNOWN";PrintJobAttempt attempt=j.getCurrentAttemptId()==null?null:db.findJobAttempt(j.getCurrentAttemptId());if(attempt!=null){a.put("attemptId",attempt.getAttemptId());a.put("commandId",attempt.getCommandId());a.put("face",attempt.getFace());if(Arrays.asList("FRONT_IN_PROGRESS","BACK_IN_PROGRESS","AUTO_IN_PROGRESS").contains(j.getStatus())){type="PRINT_"+attempt.getFace();JsonNode metadata=artifactMetadata(j,"BOTH".equals(attempt.getFace())?"combined":attempt.getFace());Map<String,Object> artifact=PrintJson.map(metadata);artifact.remove("contentBase64");artifact.remove("objectId");artifact.put("downloadPath","/api/print-client/v1/jobs/"+j.getJobId()+"/artifacts/"+("BOTH".equals(attempt.getFace())?"combined":attempt.getFace())+"/download");JsonNode page=PrintJson.read(j.getSnapshotJson()).at("/renderRequest/faceSources/0/template/pageSpecJson");artifact.put("pageWidthMm",metadata.path("widthMm").asDouble(page.path("widthMm").asDouble()));artifact.put("pageHeightMm",metadata.path("heightMm").asDouble(page.path("heightMm").asDouble()));a.put("artifact",artifact);}}a.put("type",type);r.put("action",a);return r;}
 public byte[] artifact(PrintClientIdentity device,String id,String face){return readArtifact(db,job(device,id),face);}
 void audit(PrintClientIdentity d,PrintJob j,String action){tx.audit(d.principal(),j.getParkId(),action,j.getJobId(),auditSummary(j,Collections.emptyMap()));}
}
