package com.tce.smart.platform.service.print;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import com.tce.smart.platform.core.entity.print.*;
import com.tce.smart.platform.core.mapper.PrintJobMapper;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Service;
import java.util.*;
import static com.tce.smart.platform.service.print.PrintJobTransactions.*;
/** 一人一任务，冻结数据与物理状态分开持久；所有人工决定受事务保护。 */
@Service public class PrintJobService {
 final PrintJobMapper db;final PrintAccessPolicy access;final PrintJobTransactions tx;final PrintPrinterService printers;final PrintJobPreparation preparation;final PrintExecutionProperties execution;
 public PrintJobService(PrintJobMapper db,PrintAccessPolicy access,PrintJobTransactions tx,PrintPrinterService printers,PrintJobPreparation preparation,PrintExecutionProperties execution){this.db=db;this.access=access;this.tx=tx;this.printers=printers;this.preparation=preparation;this.execution=execution;}
 public PrintMutationResult create(ObjectNode request,String key){String park=authorizeCreate(request);return tx.command(access.actor(),key,"JOB_CREATE",request,()->{requireEnabled();PrintJob job=prepare(request,park);db.insertJob(job);audit(job,"JOB_CREATED");return view(job);});}
 public PrintMutationResult batch(ObjectNode request,String key){String park=authorizeCreate(request);return tx.command(access.actor(),key,"JOB_BATCH",request,()->{requireEnabled();JsonNode subjects=request.path("subjects");if(!subjects.isArray()||subjects.size()==0||subjects.size()>100)throw error(422,"INVALID_REQUEST");List<PrintJob> pending=new ArrayList<>();List<Map<String,Object>> invalid=new ArrayList<>();Set<String> seen=new HashSet<>();for(JsonNode subject:subjects){ObjectNode item=request.deepCopy();item.remove("subjects");if(!subject.isObject())throw error(422,"INVALID_REQUEST");for(String k:Arrays.asList("subjectId","subjectType","previewId"))item.set(k,subject.path(k));String signature=item.path("subjectType").asText()+":"+item.path("subjectId").asText();if(!seen.add(signature))throw error(422,"INVALID_REQUEST");try{pending.add(prepare(item,park));}catch(PrintApiException e){if(e.getStatus()==401||e.getStatus()==403||e.getStatus()>=500)throw e;Map<String,Object> failure=new LinkedHashMap<>();failure.put("subjectId",item.path("subjectId").asText());failure.put("code",e.getCode());invalid.add(failure);}}if(!invalid.isEmpty())throw new PrintApiException(422,"BATCH_VALIDATION_FAILED","批次存在未通过校验的人员",Collections.singletonMap("items",invalid));List<Map<String,Object>> results=new ArrayList<>();for(PrintJob job:pending){db.insertJob(job);audit(job,"JOB_CREATED");results.add(view(job));}return Collections.singletonMap("jobs",results);});}
 String authorizeCreate(ObjectNode request){PrintJson.limit(request,65536);String park=access.resolvePark(request.path("parkId").asText(null));access.require("execute",park);Set<String> keys=new HashSet<>(Arrays.asList("parkId","printItemType","personType","classificationCode","subjectType","subjectId","printerProfileId","printMode","selection","subjects","previewId"));request.fieldNames().forEachRemaining(k->{if(!keys.contains(k))throw error(422,"INVALID_REQUEST");});return park;}
 void requireEnabled(){if(!execution.isEnabled())throw error(503,"PRINT_EXECUTION_DISABLED");}
 PrintJob prepare(ObjectNode request,String park){PrintJobPreview preview=PrintJobConfirmation.require(db,request.path("previewId").asText(null),park,access.actor());PrintAccessPolicy.uuid(request.path("printerProfileId").asText());PrintPrinter p=db.lockPrinter(request.path("printerProfileId").asText());if(p==null)throw error(404,"PRINTER_PROFILE_NOT_FOUND");if(!park.equals(p.getParkId()))throw error(403,"PRINT_SCOPE_DENIED");if(!"ENABLED".equals(p.getStatus()))throw error(409,"PRINTER_DISABLED");String jobId=id();ObjectNode profile=PrintPrinterService.snapshot(p);ObjectNode frozen=preparation.freeze(request,jobId,profile,false);String item=request.path("printItemType").asText(frozen.path("printItemType").asText());String mode=request.path("printMode").asText(profile.path("defaultPrintMode").asText());PrintPrinterService.requireMode(profile,mode,item);PrintJobConfirmation.verify(preview,frozen,profile,mode);frozen.set("printerSnapshot",profile);PrintJob job=new PrintJob();job.setJobId(jobId);job.setParkId(park);job.setCreatedBy(access.actor());job.setPrinterProfileId(p.getPrinterProfileId());job.setDeviceIdentity(p.getDeviceIdentity());job.setSubjectType(request.path("subjectType").asText());job.setSubjectId(request.path("subjectId").asText());job.setPrintItemType(item);job.setPrintMode(mode);job.setStatus("QUEUED");job.setSnapshotJson(PrintJson.canonical(frozen));job.setTemplateSnapshotHash(PrintJson.hash(frozen.path("renderRequest").path("faceSources")));job.setPrinterSnapshotHash(PrintJson.hash(profile));job.setCreatedAt(now());job.setUpdatedAt(now());return job;}
 public Map<String,Object> list(String park,String printer,String status,int page,int size){park=access.resolvePark(park);access.require("execute",park);if(page<1||page>10000||size<1||size>100)throw error(422,"INVALID_REQUEST");List<Map<String,Object>> rows=new ArrayList<>();for(PrintJob j:db.listJobs(park,access.actor(),printer,status,new RowBounds((page-1)*size,size)))rows.add(view(j));Map<String,Object> result=new LinkedHashMap<>();result.put("records",rows);result.put("total",db.countJobs(park,access.actor(),printer,status));result.put("page",page);result.put("size",size);return result;}
 public Map<String,Object> list(com.tce.smart.platform.api.dto.req.print.PrintJobQuery query){String park=access.resolvePark(query.getParkId());access.require("execute",park);int page=query.getPage(),size=query.getSize();if(page<1||page>10000||size<1||size>100)throw error(422,"INVALID_REQUEST");Map<String,Object> params=new LinkedHashMap<>();params.put("park",park);params.put("owner",access.actor());params.put("printer",query.getPrinterProfileId());params.put("status",query.getStatus());params.put("subject",query.getSubjectId());params.put("item",query.getPrintItemType());try{java.time.Instant from=query.getCreatedFrom()==null?null:java.time.Instant.parse(query.getCreatedFrom()),to=query.getCreatedTo()==null?null:java.time.Instant.parse(query.getCreatedTo());if(from!=null&&to!=null&&!from.isBefore(to))throw error(422,"INVALID_REQUEST");params.put("from",from==null?null:java.sql.Timestamp.from(from));params.put("to",to==null?null:java.sql.Timestamp.from(to));}catch(java.time.format.DateTimeParseException failure){throw error(422,"INVALID_REQUEST");}List<Map<String,Object>> rows=new ArrayList<>();for(PrintJob j:db.queryJobs(params,new RowBounds((page-1)*size,size)))rows.add(view(j));Map<String,Object> result=new LinkedHashMap<>();result.put("records",rows);result.put("total",db.countQueryJobs(params));result.put("page",page);result.put("size",size);return result;}
 public Map<String,Object> detail(String id){PrintJob job=authorized(id,"execute",true);Map<String,Object> result=view(job);List<Map<String,Object>> attempts=new ArrayList<>();for(PrintJobAttempt a:db.attempts(id)){Map<String,Object>s=new LinkedHashMap<>();s.put("attemptId",a.getAttemptId());s.put("commandId",a.getCommandId());s.put("face",a.getFace());s.put("attemptNo",a.getAttemptNo());s.put("state",state(a).path("status").asText());attempts.add(s);}result.put("attempts",attempts);return result;}
 PrintJob authorized(String id,String permission,boolean own){access.user();PrintAccessPolicy.uuid(id);PrintJob j=db.findJob(id);if(j==null)throw error(404,"PRINT_JOB_NOT_FOUND");access.require(permission,j.getParkId());if(own&&!access.actor().equals(j.getCreatedBy()))access.require("recover",j.getParkId());return j;}
 PrintJob lock(PrintJob initial){PrintPrinter p=db.lockPrinter(initial.getPrinterProfileId());PrintJob j=db.lockJob(initial.getJobId());if(j.getCurrentAttemptId()!=null&&!j.getJobId().equals(p.getActiveJobId()))throw error(409,"PRINTER_OCCUPIED");return j;}
 public PrintMutationResult cancel(String id,ObjectNode body,String key){PrintJob initial=authorized(id,"execute",true);return tx.command(access.actor(),key,"JOB_CANCEL:"+id,body,()->{PrintJob j=lock(initial);if(terminal(j))throw error(409,"JOB_STATE_CONFLICT");requireText(body,"reason");j.setStateJson(PrintJson.canonical(PrintJson.object().put("cancelReason",body.path("reason").asText()).put("cancelledAt",now().toInstant().toString()).put("cancelledBy",access.actor())));j.setStatus("CANCELLED");if(j.getCurrentAttemptId()!=null){PrintJobAttempt attempt=db.findJobAttempt(j.getCurrentAttemptId());ObjectNode state=state(attempt);state.put("cancelReason",body.path("reason").asText()).put("cancelledAt",now().toInstant().toString()).put("cancelledBy",access.actor());attempt.setStateJson(PrintJson.canonical(state));db.updateJobAttempt(attempt);}save(j);audit(j,"JOB_CANCELLED");return view(j);});}
 public PrintMutationResult flip(String id,ObjectNode body,String key){PrintJob initial=authorized(id,"recover",false);return tx.command(access.actor(),key,"JOB_FLIP:"+id,body,()->{PrintJob j=lock(initial);if(!"MANUAL_DUPLEX".equals(j.getPrintMode())||!"AWAITING_FLIP".equals(j.getStatus())||!body.path("orientationConfirmed").asBoolean())throw error(409,"JOB_STATE_CONFLICT");operator(body);PrintJobAttempt a=current(j,body);if(!"FRONT".equals(a.getFace())||!state(a).path("confirmedOut").asBoolean())throw error(409,"OUTPUT_CHECK_REQUIRED");newAttempt(db,j,"BACK");save(j);audit(j,"FLIP_CONFIRMED");return commandResponse(j);});}
 public PrintMutationResult outputCheck(String id,ObjectNode body,String key){PrintJob initial=authorized(id,"recover",false);return tx.command(access.actor(),key,"JOB_OUTPUT_CHECK:"+id,body,()->{PrintJob j=lock(initial);boolean businessTerminal=Arrays.asList("COMPLETED","FAILED","CANCELLED").contains(j.getStatus());if(!Arrays.asList("AWAITING_FRONT_CHECK","AWAITING_OUTPUT_CHECK","RESULT_UNKNOWN").contains(j.getStatus())&&!businessTerminal)throw error(409,"JOB_STATE_CONFLICT");operator(body);PrintJobAttempt a=current(j,body);ObjectNode s=state(a);String decision=body.path("decision").asText(),resolution=body.path("resolution").asText();JsonNode physical=body.path("physicalCheck");if(!a.getFace().equals(body.path("face").asText())||!Arrays.asList("NO_CARD_IN_DEVICE","CARD_IN_DEVICE","STATE_UNKNOWN").contains(physical.path("state").asText())||physical.path("operatorNote").asText().trim().isEmpty())throw error(422,"OUTPUT_CHECK_INCOMPLETE");
  // 终态的再次无卡核对只补充物理清空证据，不覆盖原输出判定、取消理由或业务终态。
  if(businessTerminal){boolean clearance="DEVICE_CLEARANCE".equals(decision)&&"NONE".equals(resolution);boolean existingCancelCheck="CANCELLED".equals(j.getStatus())&&Arrays.asList("CONFIRMED_NOT_OUT","CONFIRMED_DAMAGED").contains(decision)&&"CANCEL".equals(resolution);if(!clearance&&!existingCancelCheck)throw error(409,"JOB_STATE_CONFLICT");if(!"NO_CARD_IN_DEVICE".equals(physical.path("state").asText()))throw error(422,"OUTPUT_CHECK_INCOMPLETE");}
  else if("CONFIRMED_OUT".equals(decision)&&"NONE".equals(resolution)){s.put("confirmedOut",true).put("status","CONFIRMED_OUT");if("MANUAL_DUPLEX".equals(j.getPrintMode())&&"FRONT".equals(a.getFace()))j.setStatus("AWAITING_FLIP");else{if("BACK".equals(a.getFace())&&!frontConfirmed(j))throw error(409,"OUTPUT_CHECK_REQUIRED");j.setStatus("COMPLETED");}}
  else if("CONFIRMED_NOT_OUT".equals(decision)&&"CONTINUE".equals(resolution)){boolean rejected=s.path("rejectedNotSubmitted").asBoolean()&&!s.path("accepted").asBoolean()&&!s.path("unknown").asBoolean()&&!s.path("completedEvidence").asBoolean();boolean retired="MANUAL_DUPLEX".equals(j.getPrintMode())&&s.path("retired").asBoolean()&&physical.path("sameCardFaceVerified").asBoolean();if(!"NO_CARD_IN_DEVICE".equals(physical.path("state").asText())||(!rejected&&!retired))throw error(409,"OUTPUT_CHECK_REQUIRED");s.put("status","RETIRED").put("retired",true);a.setStateJson(PrintJson.canonical(s));db.updateJobAttempt(a);newAttempt(db,j,a.getFace());}
  else if(Arrays.asList("CONFIRMED_NOT_OUT","CONFIRMED_DAMAGED").contains(decision)&&"CANCEL".equals(resolution)){requireText(body,"reason");j.setStateJson(PrintJson.canonical(PrintJson.object().put("cancelReason",body.path("reason").asText()).put("cancelledAt",now().toInstant().toString()).put("cancelledBy",access.actor())));j.setStatus("CANCELLED");s.put("status",decision);}
  else throw error(422,"OUTPUT_CHECK_INCOMPLETE");
  // 人工检查始终属于实际被核对的原attempt；续打的新attempt不能继承提交前的无卡证据。
  if(businessTerminal){s.set("clearancePhysicalCheck",physical.deepCopy());s.put("clearanceCheckedBy",access.actor()).put("clearanceCheckedAt",now().toInstant().toString());}else{s.set("operatorPhysicalCheck",physical.deepCopy());s.put("resolvedBy",access.actor()).put("resolvedAt",now().toInstant().toString());}
  String check=id();s.put("operatorCheckId",check).put("operatorPhysicalState",physical.path("state").asText());a.setStateJson(PrintJson.canonical(s));db.updateJobAttempt(a);
  j.setOperatorCheckId(a.getAttemptId().equals(j.getCurrentAttemptId())?check:null);save(j);Map<String,Object> summary=a.getAttemptId().equals(j.getCurrentAttemptId())?view(j):commandResponse(j);summary.put("operatorCheckId",check);summary.put("physicalState",physical.path("state").asText());summary.put("decision",decision);tx.audit(access.actor(),j.getParkId(),"OUTPUT_CHECKED",j.getJobId(),auditSummary(j,summary));return summary;});}
 /** 新命令在当前事务内形成完整响应，并由幂等记录保存；重放不再分配attempt。 */
 Map<String,Object> commandResponse(PrintJob j){Map<String,Object> response=view(j);Map<String,Object> envelope=PrintClientService.action(db,j);response.putAll(envelope);Map<?,?> command=(Map<?,?>)envelope.get("action");for(String key:Arrays.asList("attemptId","commandId","face","artifact"))response.put(key,command.get(key));return response;}
 boolean frontConfirmed(PrintJob j){for(PrintJobAttempt a:db.attempts(j.getJobId()))if("FRONT".equals(a.getFace())&&state(a).path("confirmedOut").asBoolean())return true;return false;}
 void operator(JsonNode body){if(body.hasNonNull("operatorId")&&!access.actor().equals(body.path("operatorId").asText()))throw error(403,"PRINT_SCOPE_DENIED");}
 static void requireText(JsonNode body,String key){if(body.path(key).asText().trim().isEmpty()||body.path(key).asText().length()>1000)throw error(422,"INVALID_REQUEST");}
 PrintJobAttempt current(PrintJob j,JsonNode body){if(j.getCurrentAttemptId()==null||!j.getCurrentAttemptId().equals(body.path("attemptId").asText()))throw error(409,"JOB_STATE_CONFLICT");return db.findJobAttempt(j.getCurrentAttemptId());}
 void save(PrintJob j){j.setUpdatedAt(now());db.updateJob(j);}
 void audit(PrintJob j,String action){tx.audit(access.actor(),j.getParkId(),action,j.getJobId(),auditSummary(j,Collections.emptyMap()));}
 static Map<String,Object> auditSummary(PrintJob j,Map<String,Object> extra){Map<String,Object> s=new LinkedHashMap<>();s.put("status",j.getStatus());s.put("jobId",j.getJobId());s.put("subjectId",j.getSubjectId());s.put("subjectType",j.getSubjectType());s.put("templateSnapshotHash",j.getTemplateSnapshotHash());s.put("printerSnapshotHash",j.getPrinterSnapshotHash());JsonNode frozen=PrintJson.read(j.getSnapshotJson());for(String k:Arrays.asList("employeeGradeCode","employeeGradeName","employeeGradeSource"))if(frozen.has(k))s.put(k,frozen.get(k));for(String k:Arrays.asList("operatorCheckId","physicalState","decision"))if(extra.containsKey(k))s.put(k,extra.get(k));return s;}
 static ObjectNode state(PrintJobAttempt a){return (ObjectNode)PrintJson.read(a.getStateJson());}
 static boolean terminal(PrintJob j){return Arrays.asList("COMPLETED","CANCELLED","FAILED","RENDER_FAILED").contains(j.getStatus());}
 static PrintJobAttempt newAttempt(PrintJobMapper db,PrintJob j,String face){PrintJobAttempt a=new PrintJobAttempt();a.setAttemptId(id());a.setJobId(j.getJobId());a.setCommandId(id());a.setFace(face);a.setAttemptNo(db.attempts(j.getJobId()).size()+1);a.setStateJson("{\"status\":\"CREATED\"}");db.insertJobAttempt(a);j.setOperatorCheckId(null);j.setCurrentAttemptId(a.getAttemptId());j.setStatus("BOTH".equals(face)?"AUTO_IN_PROGRESS":"BACK".equals(face)?"BACK_IN_PROGRESS":"FRONT_IN_PROGRESS");return a;}
 public static Map<String,Object> view(PrintJob j){Map<String,Object> r=new LinkedHashMap<>();r.put("jobId",j.getJobId());r.put("parkId",j.getParkId());r.put("subjectId",j.getSubjectId());r.put("subjectType",j.getSubjectType());r.put("printItemType",j.getPrintItemType());r.put("printMode",j.getPrintMode());r.put("printerProfileId",j.getPrinterProfileId());r.put("deviceIdentity",j.getDeviceIdentity());r.put("status",j.getStatus());r.put("currentAttemptId",j.getCurrentAttemptId());r.put("templateSnapshotHash",j.getTemplateSnapshotHash());r.put("printerSnapshotHash",j.getPrinterSnapshotHash());r.put("createdAt",j.getCreatedAt().toInstant().toString());r.put("updatedAt",j.getUpdatedAt().toInstant().toString());r.put("operatorCheckId",j.getOperatorCheckId());r.put("errorCode",j.getErrorCode());r.put("expectedFaceCount","STAFF_CARD".equals(j.getPrintItemType())?2:1);JsonNode snapshot=PrintJson.read(j.getSnapshotJson());ObjectNode subject=PrintJson.object();for(String k:Arrays.asList("subjectType","subjectId","personType","classificationCode","employeeGradeCode","employeeGradeName","employeeGradeSource"))if(snapshot.has(k))subject.set(k,snapshot.get(k));JsonNode fields=snapshot.path("fields");String displayName=fields.path("staffName").asText("");if(displayName.trim().isEmpty())displayName=fields.path("visitorName").asText("");if(displayName.trim().isEmpty())displayName=j.getSubjectId();subject.put("displayName",displayName);if(fields.path("staffNo").isTextual())subject.set("staffNo",fields.get("staffNo"));r.put("subjectSummary",subject);ObjectNode printerSummary=PrintJson.object();JsonNode printer=snapshot.path("printerSnapshot");for(String k:Arrays.asList("displayName","model"))if(printer.path(k).isTextual())printerSummary.set(k,printer.get(k));ObjectNode calibration=PrintJson.object();for(String k:Arrays.asList("frontFeedInstruction","backFeedInstruction"))if(printer.path("calibration").path(k).isTextual())calibration.set(k,printer.path("calibration").get(k));for(String k:Arrays.asList("frontRotation","backRotation"))if(printer.path("calibration").path(k).isIntegralNumber())calibration.set(k,printer.path("calibration").get(k));printerSummary.set("calibration",calibration);r.put("printerSummary",printerSummary);r.put("resolution",publicResolution(snapshot.path("resolution")));if(j.getArtifactsJson()!=null){ObjectNode artifacts=(ObjectNode)PrintJson.read(j.getArtifactsJson());publicArtifacts(artifacts,"/platform/print/v1/print-jobs/"+j.getJobId()+"/artifacts/");r.putAll(PrintJson.map(artifacts));}return r;}
 static JsonNode publicResolution(JsonNode source){ObjectNode r=PrintJson.object();for(String k:Arrays.asList("selection","frontTemplateVersionId","backTemplateVersionId","frontContentHash","backContentHash","pairRevision","bindingRuleId","bindingRevision","matchLevel","employeeGradeCode","employeeGradeName","employeeGradeSource","manualSelectionConfirmed","differsFromAutomatic","automaticResolution"))if(source.has(k))r.set(k,source.get(k));return r;}
 static void publicArtifacts(ObjectNode artifacts,String prefix){for(JsonNode a:artifacts.path("artifacts")){((ObjectNode)a).remove(Arrays.asList("contentBase64","objectId"));((ObjectNode)a).put("downloadPath",prefix+a.path("face").asText()+"/download");}if(artifacts.hasNonNull("combinedArtifact")){ObjectNode a=(ObjectNode)artifacts.get("combinedArtifact");a.remove(Arrays.asList("contentBase64","objectId"));a.put("downloadPath",prefix+"combined/download");}}
 public byte[] artifact(String id,String face){PrintJob j=authorized(id,"execute",true);access.require("resource",j.getParkId());return readArtifact(db,j,face);}
 public static byte[] readArtifact(PrintJobMapper db,PrintJob j,String face){JsonNode a=artifactMetadata(j,face);PrintJobArtifact stored=db.findJobArtifact(a.path("artifactId").asText());if(stored==null||!j.getJobId().equals(stored.getOwnerId())||!j.getParkId().equals(stored.getParkId())||!PrintJson.hashBytes(stored.getContentBytes()).equals(a.path("sha256").asText()))throw error(422,"PRINT_RESOURCE_HASH_MISMATCH");return stored.getContentBytes();}
 static JsonNode artifactMetadata(PrintJob j,String face){if(j.getArtifactsJson()==null)throw error(409,"PRINT_ARTIFACT_NOT_READY");JsonNode artifacts=PrintJson.read(j.getArtifactsJson());if("combined".equals(face)){if(artifacts.hasNonNull("combinedArtifact"))return artifacts.get("combinedArtifact");}else if(Arrays.asList("FRONT","BACK").contains(face)){for(JsonNode a:artifacts.path("artifacts"))if(face.equals(a.path("face").asText()))return a;}throw error(404,"PRINT_ARTIFACT_NOT_FOUND");}
 public List<JsonNode> events(String id){PrintJob j=authorized(id,"execute",true);List<JsonNode> r=new ArrayList<>();for(String row:db.jobAudit(j.getJobId(),new RowBounds(0,100)))r.add(PrintJson.read(row));return r;}
}
