package com.tce.smart.platform.service.print;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.tce.smart.platform.core.entity.print.PrintPrinter;
import com.tce.smart.platform.core.mapper.PrintJobMapper;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Service;
import java.util.*;
import static com.tce.smart.platform.service.print.PrintJobTransactions.*;
/** 档案修订仅影响新任务；活动任务继续冻结的设备配置。 */
@Service public class PrintPrinterService {
 final PrintJobMapper db; final PrintAccessPolicy access; final PrintJobTransactions tx;
 private static final Set<String> KEYS=new HashSet<>(Arrays.asList("parkId","name","displayName","driverVersion","sdkOrBridgeVersion","deviceIdentity","manufacturer","model","deviceType","connectionType","allowedPrintModes","defaultPrintMode","capabilityStatus","flipCapability","mediaSpec","calibration","capabilityEvidence","configRevision"));
 public PrintPrinterService(PrintJobMapper db,PrintAccessPolicy access,PrintJobTransactions tx){this.db=db;this.access=access;this.tx=tx;}
 public PrintMutationResult save(String id,ObjectNode input,String key){String park=id==null?access.resolvePark(input.path("parkId").asText(null)):authorized(id).getParkId();access.require("device",park);return tx.command(access.actor(),key,"PRINTER_SAVE:"+id,input,()->{PrintPrinter p=id==null?new PrintPrinter():db.lockPrinter(id);ObjectNode config=id==null?PrintJson.object():(ObjectNode)PrintJson.read(p.getConfigJson());input.fieldNames().forEachRemaining(k->{if(!KEYS.contains(k))throw error(422,"INVALID_REQUEST");});if(id!=null){if(!input.path("configRevision").isIntegralNumber()||input.path("configRevision").asLong()!=p.getConfigRevision())throw error(409,"PRINTER_CONFIG_REVISION_CONFLICT");if(input.hasNonNull("parkId")&&!park.equals(input.path("parkId").asText()))throw error(403,"PRINT_SCOPE_DENIED");}config.setAll(input);config.put("parkId",park);validate(config);if(id==null){p.setPrinterProfileId(id());p.setParkId(park);p.setConfigRevision(0L);p.setStatus("ENABLED");}else p.setConfigRevision(p.getConfigRevision()+1);p.setDeviceIdentity(config.path("deviceIdentity").asText());config.put("printerProfileId",p.getPrinterProfileId()).put("configRevision",p.getConfigRevision());p.setConfigJson(PrintJson.canonical(config));if(id==null)db.insertPrinter(p);else db.updatePrinter(p);tx.audit(access.actor(),park,"PRINTER_SAVED",p.getPrinterProfileId(),Collections.singletonMap("configRevision",p.getConfigRevision()));return view(p);});}
 public PrintMutationResult disable(String id,ObjectNode body,String key){PrintPrinter initial=authorized(id);return tx.command(access.actor(),key,"PRINTER_DISABLE:"+id,body,()->{PrintPrinter p=db.lockPrinter(id);if(!body.path("configRevision").isIntegralNumber()||body.path("configRevision").asLong()!=p.getConfigRevision())throw error(409,"PRINTER_CONFIG_REVISION_CONFLICT");String state=body.path("status").asText("DISABLED");if(!Arrays.asList("DISABLED","QUARANTINED").contains(state))throw error(422,"INVALID_REQUEST");p.setStatus(state);p.setConfigRevision(p.getConfigRevision()+1);ObjectNode c=(ObjectNode)PrintJson.read(p.getConfigJson());c.put("configRevision",p.getConfigRevision());p.setConfigJson(PrintJson.canonical(c));db.updatePrinter(p);tx.audit(access.actor(),initial.getParkId(),"PRINTER_DISABLED",id,Collections.singletonMap("configRevision",p.getConfigRevision()));return view(p);});}
 public Map<String,Object> detail(String id){return view(authorized(id));}
 public Map<String,Object> list(String park,int page,int size){park=access.resolvePark(park);access.require("device",park);if(page<1||size<1||size>100||page>10000)throw error(422,"INVALID_REQUEST");List<Map<String,Object>> rows=new ArrayList<>();for(PrintPrinter p:db.listPrinters(park,new RowBounds((page-1)*size,size)))rows.add(view(p));Map<String,Object> r=new LinkedHashMap<>();r.put("records",rows);r.put("total",db.countPrinters(park));r.put("page",page);r.put("size",size);return r;}
 PrintPrinter authorized(String id){access.user();PrintAccessPolicy.uuid(id);PrintPrinter p=db.findPrinter(id);if(p==null)throw error(404,"PRINTER_PROFILE_NOT_FOUND");access.require("device",p.getParkId());return p;}
 /** 打印候选只要求执行权限，白名单投影不暴露工作站身份和验收人员。 */
 public Map<String,Object> options(String park,int page,int size){
  park=access.resolvePark(park);access.require("execute",park);if(page<1||page>10000||size<1||size>100)throw error(422,"INVALID_REQUEST");
  List<Map<String,Object>> rows=new ArrayList<>();for(PrintPrinter printer:db.listPrinters(park,new RowBounds((page-1)*size,size))){
   Map<String,Object> item=new LinkedHashMap<>();JsonNode config=snapshot(printer);item.put("printerProfileId",printer.getPrinterProfileId());item.put("status",printer.getStatus());item.put("busy",printer.getActiveJobId()!=null);
   for(String key:Arrays.asList("displayName","deviceType","allowedPrintModes","defaultPrintMode"))item.put(key,config.path(key));rows.add(item);
  }
  Map<String,Object> result=new LinkedHashMap<>();result.put("records",rows);result.put("total",db.countPrinters(park));result.put("page",page);result.put("size",size);return result;
 }
 public static ObjectNode snapshot(PrintPrinter p){return ((ObjectNode)PrintJson.read(p.getConfigJson())).deepCopy();}
 static Map<String,Object> view(PrintPrinter p){Map<String,Object> r=PrintJson.map(snapshot(p));r.put("status",p.getStatus());r.put("activeJobId",p.getActiveJobId());r.put("printerSnapshotHash",PrintJson.hash(snapshot(p)));return r;}
 public static void validate(ObjectNode c){PrintJson.limit(c,65536);if(!c.hasNonNull("displayName")&&c.hasNonNull("name"))c.set("displayName",c.get("name"));PrintTemplateValidator.name(c.path("displayName").asText());if(!Arrays.asList("LABEL_PRINTER","CARD_PRINTER").contains(c.path("deviceType").asText())||!Arrays.asList("USB_LOCAL_CLIENT","LOCAL_AGENT").contains(c.path("connectionType").asText())||!Arrays.asList("UNVERIFIED","VERIFIED","REVOKED").contains(c.path("capabilityStatus").asText())||!Arrays.asList("NONE","MANUAL_ONLY","AUTO_VERIFIED").contains(c.path("flipCapability").asText()))throw error(422,"INVALID_REQUEST");for(String k:Arrays.asList("deviceIdentity","manufacturer","model","deviceType","connectionType","defaultPrintMode","capabilityStatus","flipCapability")){if(!c.path(k).isTextual()||c.path(k).asText().trim().isEmpty()||c.path(k).asText().length()>128)throw error(422,"INVALID_REQUEST");}if(!c.path("deviceIdentity").asText().matches("[\\x21-\\x7e]{1,128}"))throw error(422,"INVALID_REQUEST");if(!c.path("allowedPrintModes").isArray()||c.path("allowedPrintModes").size()==0||c.path("allowedPrintModes").size()>3||!c.path("mediaSpec").isObject()||!c.path("calibration").isObject()||!c.path("capabilityEvidence").isArray())throw error(422,"INVALID_REQUEST");Set<String> modes=new HashSet<>();for(JsonNode m:c.path("allowedPrintModes")){if(!Arrays.asList("SINGLE","MANUAL_DUPLEX","AUTO_DUPLEX").contains(m.asText())||!modes.add(m.asText()))throw error(422,"INVALID_REQUEST");}if(!modes.contains(c.path("defaultPrintMode").asText()))throw error(422,"INVALID_REQUEST");if(modes.contains("AUTO_DUPLEX")&&(!"VERIFIED".equals(c.path("capabilityStatus").asText())||!"AUTO_VERIFIED".equals(c.path("flipCapability").asText())||!verifiedFlipEvidence(c.path("capabilityEvidence"))))throw error(422,"PRINTER_CAPABILITY_UNVERIFIED");String model=c.path("model").asText().replace("-","").toUpperCase(Locale.ROOT);if(model.equals("QL800")){if(!modes.equals(Collections.singleton("SINGLE"))||c.at("/mediaSpec/maxPrintableWidthMm").asDouble()!=58)throw error(422,"PRINTER_CAPABILITY_UNVERIFIED");if(c.at("/mediaSpec/blackRed").asBoolean()&&(!c.at("/mediaSpec/blackRedMediaConfirmed").asBoolean()||!c.at("/mediaSpec/blackRedCapabilityVerified").asBoolean()))throw error(422,"PRINTER_CAPABILITY_UNVERIFIED");}}
 static boolean verifiedFlipEvidence(JsonNode evidence){for(JsonNode e:evidence){if("FLIP_MODULE".equals(e.path("type").asText())&&e.path("verified").asBoolean()&&e.path("evidenceId").asText().matches("[a-fA-F0-9-]{36}")&&!e.path("driverVersion").asText().trim().isEmpty()&&!e.path("verifiedBy").asText().trim().isEmpty()){try{java.time.Instant.parse(e.path("verifiedAt").asText());return true;}catch(Exception ignored){}}}return false;}
 public static void requireMode(JsonNode c,String mode,String item){boolean found=false;for(JsonNode m:c.path("allowedPrintModes"))if(mode.equals(m.asText()))found=true;if(!found||("STAFF_CARD".equals(item)&&!Arrays.asList("MANUAL_DUPLEX","AUTO_DUPLEX").contains(mode))||("VISITOR_SLIP".equals(item)&&!"SINGLE".equals(mode)))throw error(422,"PRINTER_MODE_NOT_ALLOWED");validate((ObjectNode)c);}
}
